Repository liam-hq/liam, pull requests merged in 2025-04, with the labels that each got.

#1037 ✨ Added index type logic to parser
  .changeset/odd-roses-rule.md
  frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
  frontend/packages/db-structure/src/parser/__tests__/testcase.ts
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
  frontend/packages/db-structure/src/parser/schemarb/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/parser.ts
  frontend/packages/db-structure/src/schema/dbStructure.ts
  frontend/packages/db-structure/src/schema/factories.ts
  frontend/packages/db-structure/src/schema/overrideDbStructure.test.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indexes/IndexesItem/IndexesItem.tsx
Labels: Review effort 2/5

#1048 fix: change init prompt text from "postgresql" to "postgres"
  .changeset/short-turtles-admire.md
  frontend/apps/docs/content/docs/cli/index.mdx
  frontend/packages/cli/src/cli/initCommand/index.ts
Labels: Review effort 1/5

#1063 Styled-knowledge-suggestion-page
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.module.css
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionsListPage/KnowledgeSuggestionsListPage.module.css
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionsListPage/KnowledgeSuggestionsListPage.tsx
Labels: Review effort 2/5

#1058 refactor: use structured output for `processGenerateReview`
  docs/packages-license.md
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/functions/processGenerateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#1062 feat: Updated routing definitions to reflect new schema file paths
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/erdViewer.tsx
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/page.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/pages/BranchDetailPage/BranchDetailPage.tsx
  frontend/apps/app/utils/routes/routeDefinitions.ts
Labels: Review effort 2/5

#1052 🔧 Fix path to associate the Knowledge Suggestion List page with `branchOrCommit`
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/knowledge-suggestions/[id]/page.tsx
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/knowledge-suggestions/page.tsx
  frontend/apps/app/features/projects/actions/approveKnowledgeSuggestion.ts
  frontend/apps/app/features/projects/pages/BranchDetailPage/BranchDetailPage.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionsListPage/KnowledgeSuggestionsListPage.tsx
  frontend/apps/app/utils/routes/routeDefinitions.ts
Labels: Review effort 2/5

#1056 ✨ Add tableGroups support to dbOverrideSchema via schema-meta.json
  .liam/schema-meta.json
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/erdViewer.tsx
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/page.tsx
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db-structure/src/schema/overrideDbStructure.test.ts
  frontend/packages/db-structure/src/schema/overrideDbStructure.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
  frontend/packages/erd-core/src/features/erd/utils/convertDBStructureToNodes.ts
Labels: Review effort 3/5

#1064 refactor: use structured output for `generateDocsSuggestion`
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/docsSuggestionSchema.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/generateDocsSuggestion.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/index.ts
Labels: Review effort 2/5

#1072 refactor: setup supabase for jobs
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/src/index.ts
  frontend/packages/db/supabase/migrations/20250401114825_add_missing_grants.sql
  frontend/packages/jobs/src/functions/__tests__/postComment.test.ts
  frontend/packages/jobs/src/functions/postComment.ts
  frontend/packages/jobs/src/libs/supabase.ts
Labels: Review effort 3/5

#1076 refactor: update prompt generation and add prompt-test package
  .changeset/config.json
  config/dependency_decisions.yml
  docs/packages-license.md
  frontend/packages/__mocks__/node-gtts/package.json
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/index.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/index.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
  frontend/packages/jobs/src/prompts/index.ts
  frontend/packages/prompt-test/.env.local
  frontend/packages/prompt-test/biome.jsonc
  frontend/packages/prompt-test/package.json
  frontend/packages/prompt-test/src/index.ts
  frontend/packages/prompt-test/tsconfig.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 3/5

#1053 🔧 Refactor E2E test conditions
  .github/workflows/e2e_tests.yml
Labels: Review effort 2/5

#1075 refactor: replace Prisma with Supabase for data fetching in various components
  frontend/apps/app/app/(app)/app/page.tsx
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/app/api/webhook/github/utils/__tests__/checkSchemaChanges.test.ts
  frontend/apps/app/app/api/webhook/github/utils/checkSchemaChanges.ts
  frontend/apps/app/features/projects/actions/addProject.ts
  frontend/apps/app/features/projects/actions/approveKnowledgeSuggestion.ts
  memory-bank/progress.md
  memory-bank/systemPatterns.md
  memory-bank/techContext.md
Labels: Review effort 3/5

#1069 feat: schema meta suggestions
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/functions/processGenerateSchemaMeta.ts
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/types/index.ts
  memory-bank/progress.md
  memory-bank/systemPatterns.md
  memory-bank/techContext.md
  pnpm-lock.yaml
Labels: Review effort 3/5

#1079 Update severity levels and scoring threshold
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
  frontend/packages/prompt-test/src/index.ts
Labels: Review effort 2/5

#1085 ✨ Add review issues display in `MigrationDetailPage`
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.module.css
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1092 🔧 Skip test for overall review creation error handling in `processSaveReview`
  frontend/packages/jobs/src/functions/__tests__/postComment.test.ts
  frontend/packages/jobs/src/functions/__tests__/processSaveReview.test.ts
Labels: Review effort 1/5

#1078 feat: Enhance review generation by adding issue comments and updating data structures
  frontend/packages/github/src/api.server.ts
  frontend/packages/jobs/src/functions/processGenerateReview.ts
  frontend/packages/jobs/src/functions/processSavePullRequest.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/trigger/flow.md
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/types/index.ts
  frontend/packages/prompt-test/src/index.ts
  memory-bank/progress.md
  memory-bank/systemPatterns.md
  memory-bank/techContext.md
Labels: Review effort 3/5

#1088 ✨ Add RadarChart component and integrate into MigrationDetailPage
  frontend/apps/app/features/migrations/components/RadarChart/RadarChart.module.css
  frontend/apps/app/features/migrations/components/RadarChart/RadarChart.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.module.css
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
Labels: Review effort 3/5

#1089 Add a test case: PR 1033
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1033/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1055/fixture.yaml
  frontend/packages/prompt-test/src/index.ts
Labels: Review effort 2/5

#1096 feat(jobs): Migrate from Prisma to Supabase
  frontend/packages/jobs/src/functions/getInstallationIdFromRepositoryId.ts
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateReview.ts
  frontend/packages/jobs/src/functions/processGenerateSchemaMeta.ts
  frontend/packages/jobs/src/functions/processSavePullRequest.ts
  frontend/packages/jobs/src/trigger/jobs.ts
Labels: Review effort 3/5

#1095 docs: Update coding guidelines to discourage type assertions and promote runtime validation with valibot
  .clinerules
  .cursorrules
Labels: Review effort 1/5

#1081 fix: rename to GithubSchemaFilePath
  .liam/schema-meta.json
  frontend/apps/app/app/api/webhook/github/utils/__tests__/checkSchemaChanges.test.ts
  frontend/apps/app/app/api/webhook/github/utils/checkSchemaChanges.ts
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/pages/BranchDetailPage/BranchDetailPage.tsx
  frontend/apps/app/package.json
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250402090351_rename_watch_schema_file_pattern.sql
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/functions/processSavePullRequest.ts
  memory-bank/progress.md
  memory-bank/systemPatterns.md
  memory-bank/techContext.md
  pnpm-lock.yaml
Labels: Review effort 3/5

#1094 🔧 Update prompt for scoring criteria of review issues
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
Labels: Review effort 2/5

#1087 fix: Update GitHub workflows and deployment scripts for jobs and database packages
  .github/workflows/trigger_dev_production.yml
  .github/workflows/trigger_dev_staging.yml
  frontend/packages/jobs/package.json
  package.json
  turbo.json
Labels: Review effort 2/5

#1082 ✨ Add table groups concept to dbStructure
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/page.tsx
  frontend/apps/app/app/erd/p/[...slug]/page.tsx
  frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
  frontend/packages/db-structure/src/parser/prisma/parser.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
  frontend/packages/db-structure/src/parser/tbls/parser.ts
  frontend/packages/db-structure/src/schema/dbStructure.ts
  frontend/packages/db-structure/src/schema/factories.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db-structure/src/schema/overrideDbStructure.test.ts
  frontend/packages/db-structure/src/schema/overrideDbStructure.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/extractDBStructureForTable.test.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/extractDBStructureForTable.ts
  frontend/packages/erd-core/src/stores/dbStructure/store.ts
Labels: Review effort 2/5

#1104 🐛 processSavePullRequest to simplify project mappings query by selecting only projectId
  frontend/packages/jobs/src/functions/processSavePullRequest.ts
Labels: Review effort 1/5

#1103 refactor(jobs): Simplify PR save process and payload structure
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/packages/jobs/src/functions/processSavePullRequest.ts
  frontend/packages/jobs/src/index.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/types/index.ts
Labels: Review effort 2/5

#1115 Save Suggestion in Save Review Job and Display in Migration Detail Page
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.module.css
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/packages/jobs/src/functions/processSaveReview.ts
Labels: Review effort 2/5

#1106 feat(db): Complete migration from Prisma to Supabase for database migrations
  frontend/packages/db/package.json
  frontend/packages/db/prisma/migrations/20250310052227_add_project/migration.sql
  frontend/packages/db/prisma/migrations/20250310092931_add_pull_request/migration.sql
  frontend/packages/db/prisma/migrations/20250311002649_change_pull_request_columns/migration.sql
  frontend/packages/db/prisma/migrations/20250311080742_add_repository_model/migration.sql
  frontend/packages/db/prisma/migrations/20250311115613_add_migration/migration.sql
  frontend/packages/db/prisma/migrations/20250312082348_delete_description_column/migration.sql
  frontend/packages/db/prisma/migrations/20250313054231_add_overall_review/migration.sql
  frontend/packages/db/prisma/migrations/20250314074412_add/migration.sql
  frontend/packages/db/prisma/migrations/20250314074636_delete_project_relation/migration.sql
  frontend/packages/db/prisma/migrations/20250314091509_make_overall_review_project_id_nullable/migration.sql
  frontend/packages/db/prisma/migrations/20250317054258_add_watch_schema_file_pattern/migration.sql
  frontend/packages/db/prisma/migrations/20250319101533_add_docs_feature/migration.sql
  frontend/packages/db/prisma/migrations/20250321012007_add_title_to_doc_version/migration.sql
  frontend/packages/db/prisma/migrations/20250327033040_add_branch_name_to_overall_review/migration.sql
  frontend/packages/db/prisma/migrations/20250327035547_add_knowledge_suggestion/migration.sql
  frontend/packages/db/prisma/migrations/20250327101710_add_github_doc_file_path_with_unique_constraint/migration.sql
  frontend/packages/db/prisma/migrations/20250328105323_add_branch_name_to_knowledge_suggestion/migration.sql
  frontend/packages/db/prisma/migrations/20250328121434_remove_doc_tables/migration.sql
  frontend/packages/db/prisma/migrations/20250331084247_allow_null_file_sha/migration.sql
  frontend/packages/db/prisma/migrations/20250401035900_add_review_score_and_review_issue/migration.sql
  frontend/packages/db/prisma/migrations/20250401081003_delete_overall_score_from_review_issue/migration.sql
  frontend/packages/db/prisma/migrations/migration_lock.toml
  frontend/packages/db/scripts/migrate-dev.sh
  memory-bank/progress.md
  memory-bank/techContext.md
Labels: Review effort 2/5

#1107 promptfoo PR comment
  .github/workflows/prompt-test.yml
  frontend/packages/prompt-test/.gitignore
  frontend/packages/prompt-test/package.json
  frontend/packages/prompt-test/src/index.ts
  package.json
  turbo.json
Labels: Review effort 2/5

#1108 refactor(database): Migrate Prisma to Supabase JS in project feature components
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectBranchesListPage/ProjectBranchesListPage.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.tsx
  memory-bank/progress.md
Labels: Review effort 3/5

#1127 feat: Update suggestion prompt instructions in generateReview
  .github/workflows/prompt-test.yml
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1033/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1055/fixture.yaml
  frontend/packages/prompt-test/src/index.ts
Labels: Review effort 2/5

#1124 ✨ allow users to group tables on ERD and commit updates to schema-meta.json
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/constants.ts
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/erdViewer.tsx
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/page.tsx
  frontend/apps/app/app/api/schema/override/route.ts
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/schema/dbStructure.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/ERDContent.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableGroupNode/TableGroupNode.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableGroupNode/TableGroupNode.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableGroupNode/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/DesktopToolbar.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/GroupButton/GroupButton.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/GroupButton/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/MobileToolbar/MobileToolbar.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/MobileToolbar/OpenedMobileToolbar.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/Toolbar.tsx
  frontend/packages/erd-core/src/hooks/index.ts
  frontend/packages/erd-core/src/hooks/useTableGroups.ts
  frontend/packages/erd-core/src/index.ts
Labels: Review effort 3/5

#1099 feat(schema-meta): Add context-aware schema metadata generation
  frontend/packages/jobs/src/functions/processGenerateSchemaMeta.ts
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
  memory-bank/progress.md
  memory-bank/techContext.md
Labels: Review effort 2/5

#1141 🔧 fix: migration page 404
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
Labels: Review effort 1/5

#1139 Fix promptfoo share command
  .github/workflows/prompt-test.yml
Labels: Review effort 2/5

#1118 docs(db): Add migrationOpsContext documentation
  docs/migrationOpsContext.md
Labels: Review effort 1/5

#1105 ✨ Add suggestion column to ReviewIssue table
  .github/workflows/prompt-test.yml
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.module.css
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250403161902_add_suggestion_to_review_issue.sql
  frontend/packages/jobs/src/functions/processSaveReview.ts
Labels: Review effort 2/5

#1122 🔧 add description to positive issue
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
Labels: Review effort 2/5

#1145 ✨feat(schema): Enhance metadata generation with actual schema content
  frontend/packages/jobs/src/functions/processGenerateSchemaMeta.ts
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
  frontend/packages/jobs/src/utils/githubFileUtils.ts
  memory-bank/progress.md
Labels: Review effort 2/5

#1091 fix/The hidden & active query parameter is not reflected in the ER diagram during back/forward navigation
  frontend/packages/e2e/tests/e2e/navigation.test.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/ERDContent.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/hooks/usePopStateListener.ts
Labels: Review effort 2/5

#1101 feat: Add suggestionSnippets field to review schema and prompts
  frontend/packages/jobs/src/functions/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1033/fixture.yaml
Labels: Review effort 2/5

#1157 fix: update document suggestion processing to retain filename and ensure .md extension
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
Labels: Review effort 2/5

#1151 🔧 Resolving 404 errors when there are no records in `overallreview`
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
Labels: Review effort 2/5

#1162 Fix review schema strictness and update test fixtures
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1033/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1055/fixture.yaml
  frontend/packages/prompt-test/src/index.ts
Labels: Review effort 2/5

#1174 🔧 Fix conditional logic to ensure expected tests run
  .github/workflows/e2e_tests.yml
Labels: Review effort 2/5

#1167 refactor & perf: declare `tv` outside the component to avoid recreating style at each render
  frontend/apps/docs/components/Banner/Banner.style.ts
  frontend/apps/docs/components/Banner/Banner.tsx
  frontend/apps/docs/components/Breadcrumb/Breadcrumb.style.ts
  frontend/apps/docs/components/Breadcrumb/Breadcrumb.tsx
  frontend/apps/docs/components/Callout/Callout.style.ts
  frontend/apps/docs/components/Callout/Callout.tsx
  frontend/apps/docs/components/FooterNavi/FooterNavi.style.ts
  frontend/apps/docs/components/FooterNavi/FooterNavi.tsx
  frontend/apps/docs/components/Heading/Heading.style.ts
  frontend/apps/docs/components/Heading/Heading.tsx
Labels: Review effort 2/5

#1166 chore: move `@types/diff` to `devDependencies` without modifying version
  frontend/apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 1/5

#1171 Refactor: Add Biome configuration for detecting and improving code complexity with implementation example
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/package.json
  frontend/apps/docs/package.json
  frontend/packages/cli/package.json
  frontend/packages/configs/biome.jsonc
  frontend/packages/db-structure/package.json
  frontend/packages/db/package.json
  frontend/packages/e2e/package.json
  frontend/packages/erd-core/package.json
  frontend/packages/figma-to-css-variables/package.json
  frontend/packages/ui/package.json
Labels: Review effort 3/5

#1180 refactor: switch deployment condition check from Bash to Ruby
  .github/workflows/e2e_tests.yml
Labels: Review effort 2/5

#1183 ✨(knowledge): Add mapping between knowledge suggestions and doc paths
  docs/migrationOpsContext.md
  docs/migrationPatterns.md
  docs/schemaPatterns.md
  frontend/apps/app/features/projects/actions/approveKnowledgeSuggestion.ts
  frontend/apps/app/libs/db/server.ts
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250407042343_add_knowledge_suggestion_doc_mapping.sql
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/libs/supabase.ts
  memory-bank/progress.md
Labels: Review effort 2/5

#1169 feat: add support for review suggestion snippets
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.module.css
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250407001855_review-suggestion-snippet.sql
  frontend/packages/jobs/src/functions/processSaveReview.ts
Labels: Review effort 3/5

#1190 🔧 Update `generateReview` to clarify summary length requirements
  frontend/packages/jobs/src/functions/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
Labels: Review effort 2/5

#1197 🔥(db): Remove Prisma dependencies
  frontend/packages/db/package.json
  frontend/packages/db/prisma/migrations/20250402104725_20250401035900_add_review_score_and_review_issue/migration.sql
  frontend/packages/db/prisma/schema.prisma
  pnpm-lock.yaml
Labels: Review effort 2/5

#1200 🔥(jobs): Remove Prisma dependencies
  frontend/packages/jobs/package.json
  frontend/packages/jobs/trigger.config.ts
  pnpm-lock.yaml
Labels: Review effort 1/5

#1192 🔧 Change field name from `issues` to `feedback` and update related description
  frontend/packages/jobs/src/functions/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/functions/processSaveReview.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1033/fixture.yaml
Labels: Review effort 2/5

#1204 Manually set valibot version to 1.0.0
  docs/packages-license.md
  frontend/apps/app/package.json
  frontend/packages/cli/package.json
  frontend/packages/db-structure/package.json
  frontend/packages/erd-core/package.json
  frontend/packages/jobs/package.json
  pnpm-lock.yaml
Labels: Review effort 1/5

#1193 ♻️(jobs): Optimize knowledge suggestion creation with content comparison
  .ai-agents/memory-bank/progress.md
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/trigger/jobs.ts
Labels: Review effort 3/5

#1213 doc: add `pnpm run fmt` to `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: Review effort 1/5

#1210 ✅ Add `bodyMarkdown` word / sentence length check regression tests
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1033/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1055/fixture.yaml
Labels: Review effort 1/5

#1216 chore: replace `pnpm run` with `concurrently` to maintain cross-platform tolerance
  frontend/apps/app/package.json
  frontend/apps/docs/package.json
  frontend/packages/cli/package.json
  frontend/packages/db-structure/package.json
  frontend/packages/db/package.json
  frontend/packages/e2e/package.json
  frontend/packages/erd-core/package.json
  frontend/packages/figma-to-css-variables/package.json
  frontend/packages/github/package.json
  frontend/packages/jobs/package.json
  frontend/packages/prompt-test/package.json
  frontend/packages/ui/package.json
  package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1201 ✅ Introduce a fixture test that asserts at least one feedback has a "POSITIVE" severity and the score is ≥ 1.
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1105/fixture.yaml
  frontend/packages/prompt-test/src/index.ts
Labels: Review effort 2/5

#1211 ✨(jobs): Update schema metadata generation logic
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
Labels: Review effort 3/5

#1223 📝(db): Document Supabase migration workflow and update context files
  .ai-agents/memory-bank/activeContext.md
  .ai-agents/memory-bank/progress.md
  .ai-agents/memory-bank/systemPatterns.md
  .ai-agents/memory-bank/techContext.md
  docs/migrationOpsContext.md
  docs/schemaPatterns.md
Labels: Review effort 2/5

#1237 Separating License Report updates from the License Compliance workflow
  .github/workflows/license-report-update.yml
  .github/workflows/license.yml
Labels: Review effort 2/5

#1222 🔧 Update date formatting in KnowledgeSuggestionPage
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionsListPage/KnowledgeSuggestionsListPage.tsx
Labels: Review effort 2/5

#1241 🔧 Fixed review scores to be calculated by system from prompts
  frontend/packages/jobs/src/functions/processSaveReview.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
Labels: Review effort 3/5

#1242 ♻️(llm): Migrate from OpenAI to Anthropic API
  .env.template
  CONTRIBUTING.md
  frontend/apps/app/package.json
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/generateDocsSuggestion.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
  frontend/packages/migration/prompts/.env.template
  pnpm-lock.yaml
Labels: Review effort 2/5

#1261 🔧(chore): Replace symbolic links with actual files
  .ai-agents/.clinerules/memory-bank.md
  .ai-agents/rules/general.md
  .clinerules/general.md
  .clinerules/memory-bank.md
Labels: Review effort 1/5

#1234 ✨(knowledgebase): Add reasoning field to KnowledgeSuggestion
  .ai-agents/memory-bank/activeContext.md
  .ai-agents/memory-bank/progress.md
  .ai-agents/memory-bank/techContext.md
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250408_add_reasoning_to_knowledge_suggestion.sql
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateSchemaMeta.ts
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/types/index.ts
Labels: Review effort 3/5

#1263 ✨ Add ERD view alongside diff editor in Knowledge Suggestion page
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/knowledge-suggestions/[id]/page.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/ErdViewer.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.module.css
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
Labels: Review effort 3/5

#1265 ✨(ai): Switch AI model from Anthropic to OpenAI
  .ai-agents/memory-bank/activeContext.md
  .ai-agents/memory-bank/progress.md
  .ai-agents/memory-bank/techContext.md
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/functions/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/generateDocsSuggestion.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#1269 🚚(routes): Update migration routes to include project and branch context
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/migrations/[migrationId]/page.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.tsx
  frontend/apps/app/utils/routes/routeDefinitions.ts
  frontend/packages/jobs/src/functions/postComment.ts
Labels: Review effort 2/5

#1271 🧪(tests): Remove score threshold assertions from test fixtures
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1033/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1055/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1105/fixture.yaml
Labels: Review effort 1/5

#1168 ✨ feat: enhance schema to adopt `constraints` data
  .changeset/swift-keys-design.md
  frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
  frontend/packages/db-structure/src/parser/prisma/parser.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/tbls/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/parser.ts
  frontend/packages/db-structure/src/schema/dbStructure.ts
  frontend/packages/db-structure/src/schema/factories.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db-structure/src/schema/overrideDbStructure.test.ts
Labels: Review effort 3/5

#1273 ✨ Update ERD display when content is saved
  frontend/apps/app/features/projects/actions/processOverrideContent.ts
  frontend/apps/app/features/projects/components/EditableContent/EditableContent.tsx
  frontend/apps/app/features/projects/components/EditableContent/index.ts
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeContentSection.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
Labels: Review effort 2/5

#1277 ✨ Sync table group creation in ERD with diff editor
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/ErdViewer.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeContentSection.tsx
Labels: Review effort 2/5

#1278 🔧 fix: enhance special character handling in docs content processing
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
Labels: Review effort 2/5

#1231 ✨(jobs): Improve docs generation process
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/docsSuggestionSchema.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/generateDocsSuggestion.ts
Labels: Review effort 3/5

#1275 Added `resolvedAt` and `resolutionComment` to ReviewIssue
  frontend/apps/app/app/api/review-issues/resolve/route.ts
  frontend/apps/app/features/migrations/components/ResolutionCommentModal/ResolutionCommentModal.module.css
  frontend/apps/app/features/migrations/components/ResolutionCommentModal/ResolutionCommentModal.tsx
  frontend/apps/app/features/migrations/components/ResolveButton/ResolveButton.module.css
  frontend/apps/app/features/migrations/components/ResolveButton/ResolveButton.tsx
  frontend/apps/app/features/migrations/components/ReviewIssuesList/ReviewIssuesList.module.css
  frontend/apps/app/features/migrations/components/ReviewIssuesList/ReviewIssuesList.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250409175500_add_resolved_columns_to_review_issue.sql
Labels: Review effort 3/5

#1258 ✨(knowledge): Add knowledge suggestions to migration detail page
  .ai-agents/memory-bank/activeContext.md
  .ai-agents/memory-bank/progress.md
  .ai-agents/memory-bank/systemPatterns.md
  .ai-agents/memory-bank/techContext.md
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.module.css
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250409041131_create_overall_review_knowledge_suggestion_mapping.sql
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateSchemaMeta.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/types/index.ts
Labels: Review effort 3/5

#1290 🔧 Update Copy function
  frontend/apps/app/components/CopyButton/CopyButton.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/migrations/utils/formatReviewIssue.ts
Labels: Review effort 2/5

#1276 Add-organization-tables
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250409164505_add_user_organization_tables.sql
  frontend/packages/db/supabase/migrations/20250410000000_add_auth_user_trigger.sql
Labels: Review effort 2/5

#1294 Set .limit(1) for GitHubSchemaFilePath
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
Labels: Review effort 1/5

#1299 ✨(knowledge): Add reasoning to KnowledgeSuggestion content
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/docsSuggestionSchema.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/generateDocsSuggestion.ts
  frontend/packages/jobs/src/trigger/jobs.ts
Labels: Review effort 2/5

#1305 🔧 introduce GridTable as a reusable component
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Columns/ColumnsItem/ColumnsItem.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Columns/ColumnsItem/ColumnsItem.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indexes/IndexesItem/IndexesItem.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indexes/IndexesItem/IndexesItem.tsx
  frontend/packages/ui/src/components/GridTable/GridTable.module.css
  frontend/packages/ui/src/components/GridTable/GridTable.tsx
  frontend/packages/ui/src/components/GridTable/index.ts
  frontend/packages/ui/src/components/index.ts
Labels: Review effort 2/5

#1300 🔧 Remove ReviewScore table; derive review scores from ReviewIssue
  frontend/apps/app/features/migrations/components/MigrationHealthClient/MigrationHealthClient.module.css
  frontend/apps/app/features/migrations/components/MigrationHealthClient/MigrationHealthClient.tsx
  frontend/apps/app/features/migrations/components/ReviewIssuesList/ReviewIssuesList.tsx
  frontend/apps/app/features/migrations/contexts/ReviewIssuesContext.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/migrations/utils/calculateScores.ts
  frontend/apps/app/features/migrations/utils/calculateScoresServer.ts
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250410174005_remove_review_score.sql
  frontend/packages/jobs/src/functions/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/functions/processSaveReview.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1105/fixture.yaml
Labels: Review effort 3/5

#1301 🛠️(schema): Store schema file format in database
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/page.tsx
  frontend/apps/app/app/api/webhook/github/utils/__tests__/checkSchemaChanges.test.ts
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/ContentForSchema.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/ContentForSchemaSection.tsx
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250410093421_add_format_to_github_schema_file_path.sql
Labels: Review effort 2/5

#1310 ✨(config): Add .clineignore file for build outputs and environment variables
  .clineignore
Labels: Review effort 1/5

#1311 🔧 Add `QUESTION` to ReviewIssue severity
  frontend/apps/app/features/migrations/components/ReviewIssuesList/ReviewIssuesList.module.css
  frontend/apps/app/features/migrations/utils/calculateScores.ts
  frontend/apps/app/features/migrations/utils/calculateScoresServer.ts
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250411111033_add_question_to_severity_enum.sql
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1105/fixture.yaml
Labels: Review effort 2/5

#1313 Add foreign key constraint from Project.organizationId to Organization.id
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250411025912_add_foreign_key_to_project.sql
  frontend/packages/db/supabase/migrations/20250411025913_add_index_to_project_organizationId.sql
Labels: Review effort 2/5

#1312 🔧 Fix `ReviewIssue` type to use Tables from database types
  frontend/apps/app/features/migrations/contexts/ReviewIssuesContext.tsx
Labels: Review effort 1/5

#1314 DO NOT MERGE: 🧹(db): Add unique constraint on GitHubSchemaFilePath.projectId
  .ai-agents/memory-bank/techContext.md
  frontend/apps/app/app/api/webhook/github/utils/checkSchemaChanges.ts
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/pages/BranchDetailPage/BranchDetailPage.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/ContentForSchema.tsx
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/migrations/20250411030135_add_unique_constraint_to_github_schema_file_path.sql
  frontend/packages/jobs/src/functions/postComment.ts
  frontend/packages/jobs/src/functions/processGenerateReview.ts
  frontend/packages/jobs/src/functions/processGenerateSchemaMeta.ts
  frontend/packages/jobs/src/functions/processSavePullRequest.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/types/index.ts
  frontend/packages/jobs/src/utils/githubFileUtils.ts
  frontend/packages/prompt-test/src/index.ts
Labels: Review effort 3/5

#1315 🔧 Update Cline rules
  .clinerules/general.md
Labels: Review effort 1/5

#1307 Migrate prompt test CI workflow from Promptfoo to Langfuse
  .github/workflows/prompt-test.yml
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/index.ts
  frontend/packages/prompt-test/.env
  frontend/packages/prompt-test/.gitignore
  frontend/packages/prompt-test/README.md
  frontend/packages/prompt-test/package.json
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1033/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1055/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1105/fixture.yaml
  frontend/packages/prompt-test/src/index.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#1316 🔧 Fix: exclude positive feedback from suggestion snippets
  frontend/packages/jobs/src/functions/processSaveReview.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
Labels: Review effort 2/5

#1326 refactor: type improvement of file `UserFeedbackComponent.tsx`
  frontend/apps/app/components/CookieConsent/CookieConsent.tsx
  frontend/apps/app/components/UserFeedbackComponent.tsx
Labels: Review effort 1/5

#1318 ✨(jobs): Use db-structure package's parser for schema files
  .gitignore
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/functions/processGenerateSchemaMeta.ts
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
  frontend/packages/jobs/src/utils/githubFileUtils.ts
  frontend/packages/jobs/trigger.config.ts
  frontend/packages/jobs/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#1339 ✨(schema): Apply database overrides when generating schema meta
  frontend/packages/jobs/src/functions/processGenerateSchemaMeta.ts
Labels: Review effort 2/5

#1322 ♻️ refactor: rename `ReviewIssue` to `ReviewFeedback`
  frontend/apps/app/features/migrations/actions/resolveReviewFeedback.ts
  frontend/apps/app/features/migrations/components/MigrationHealthClient/MigrationHealthClient.tsx
  frontend/apps/app/features/migrations/components/ResolveButton/ResolveButton.tsx
  frontend/apps/app/features/migrations/components/ReviewFeedbackList/ReviewFeedbackList.module.css
  frontend/apps/app/features/migrations/components/ReviewFeedbackList/ReviewFeedbackList.tsx
  frontend/apps/app/features/migrations/contexts/ReviewFeedbackContext.tsx
  frontend/apps/app/features/migrations/contexts/ReviewIssuesContext.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.module.css
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/migrations/utils/calculateScores.ts
  frontend/apps/app/features/migrations/utils/calculateScoresServer.ts
  frontend/apps/app/features/migrations/utils/formatReviewFeedback.ts
  frontend/apps/app/features/migrations/utils/formatReviewIssue.ts
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250411182646_rename_review_issue_to_review_feedback.sql
  frontend/packages/jobs/src/functions/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/functions/processSaveReview.ts
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1105/fixture.yaml
Labels: Review effort 2/5

#1342 ✨ Add comment function to review feedbacks
  frontend/apps/app/features/migrations/actions/reviewFeedbackComments.ts
  frontend/apps/app/features/migrations/components/ReviewFeedbackComments/CommentForm/CommentForm.module.css
  frontend/apps/app/features/migrations/components/ReviewFeedbackComments/CommentForm/CommentForm.tsx
  frontend/apps/app/features/migrations/components/ReviewFeedbackComments/CommentList/CommentList.module.css
  frontend/apps/app/features/migrations/components/ReviewFeedbackComments/CommentList/CommentList.tsx
  frontend/apps/app/features/migrations/components/ReviewFeedbackComments/CommentsModal/CommentsModal.module.css
  frontend/apps/app/features/migrations/components/ReviewFeedbackComments/CommentsModal/CommentsModal.tsx
  frontend/apps/app/features/migrations/components/ReviewFeedbackComments/ReviewFeedbackComments.module.css
  frontend/apps/app/features/migrations/components/ReviewFeedbackComments/ReviewFeedbackComments.tsx
  frontend/apps/app/features/migrations/components/ReviewFeedbackComments/index.ts
  frontend/apps/app/features/migrations/components/ReviewFeedbackList/ReviewFeedbackList.tsx
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250414133302_add_review_feedback_comments.sql
Labels: Review effort 3/5

#1345 Switch schema override file from JSON to YAML
  .liam/schema-meta.json
  .liam/schema-override.yml
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/constants.ts
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/page.tsx
  frontend/apps/app/app/api/schema/override/route.ts
  frontend/apps/app/package.json
  frontend/packages/jobs/src/constants.ts
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/utils/schemaUtils.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#1347 Rename some `structure` words
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/erdViewer.tsx
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/page.tsx
  frontend/apps/app/app/api/schema/override/route.ts
  frontend/apps/app/app/erd/p/[...slug]/erdViewer.tsx
  frontend/apps/app/app/erd/p/[...slug]/page.tsx
  frontend/apps/app/features/projects/actions/processOverrideContent.ts
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/ContentForSchema.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/ContentForSchemaSection.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/ErdViewer.tsx
  frontend/apps/docs/content/docs/contributing/adr/20241206-node-js-based-unified-db-schema-parsing.mdx
  frontend/packages/cli/src/App.tsx
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/parser/__tests__/testcase.ts
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/mergeSchemas.ts
  frontend/packages/db-structure/src/parser/tbls/index.test.ts
  frontend/packages/db-structure/src/parser/types.ts
  frontend/packages/db-structure/src/schema/factories.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db-structure/src/schema/overrideSchema.test.ts
  frontend/packages/db-structure/src/schema/overrideSchema.ts
  frontend/packages/db-structure/src/schema/schema.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/TableDetail.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/extractSchemaForTable.test.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/extractSchemaForTable.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/TableDetailDrawer/TableDetailDrawer.tsx
  frontend/packages/erd-core/src/features/erd/utils/convertSchemaToNodes.ts
  frontend/packages/erd-core/src/features/erd/utils/index.ts
  frontend/packages/erd-core/src/stores/dbStructure/actions.ts
  frontend/packages/erd-core/src/stores/dbStructure/hooks.ts
  frontend/packages/erd-core/src/stores/dbStructure/store.ts
  frontend/packages/erd-core/src/stores/index.ts
  frontend/packages/erd-core/src/stores/schema/actions.ts
  frontend/packages/erd-core/src/stores/schema/hooks.ts
  frontend/packages/erd-core/src/stores/schema/index.ts
  frontend/packages/erd-core/src/stores/schema/store.ts
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateSchemaMeta.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/generateDocsSuggestion.ts
  frontend/packages/jobs/src/prompts/generateSchemaMeta/generateSchemaMeta.ts
  frontend/packages/jobs/src/types/index.ts
  frontend/packages/jobs/src/utils/schemaUtils.ts
Labels: Review effort 2/5

#1344 ✨ Add GlobalNav component
  .ai-agents/memory-bank/activeContext.md
  .ai-agents/memory-bank/techContext.md
  .clinerules/general.md
  frontend/apps/app/components/CommonLayout/CommonLayout.module.css
  frontend/apps/app/components/CommonLayout/CommonLayout.tsx
  frontend/apps/app/components/CommonLayout/GlobalNav/GlobalNav.module.css
  frontend/apps/app/components/CommonLayout/GlobalNav/GlobalNav.tsx
  frontend/apps/app/components/CommonLayout/GlobalNav/Item.module.css
  frontend/apps/app/components/CommonLayout/GlobalNav/LinkItem.module.css
  frontend/apps/app/components/CommonLayout/GlobalNav/LinkItem.tsx
  frontend/apps/app/components/CommonLayout/GlobalNav/OrganizationItem.module.css
  frontend/apps/app/components/CommonLayout/GlobalNav/OrganizationItem.tsx
  frontend/apps/app/components/CommonLayout/GlobalNav/index.ts
  frontend/packages/ui/src/icons/Building.tsx
  frontend/packages/ui/src/icons/ChevronsUpDown.tsx
  frontend/packages/ui/src/icons/index.ts
  frontend/packages/ui/src/logos/LiamMigrationLogo.tsx
  frontend/packages/ui/src/logos/index.ts
  frontend/packages/ui/src/styles/Dark/variables.css
Labels: Review effort 2/5

#1351 🔄(jobs): Replace schema file with dynamic schema overrides
  frontend/packages/jobs/src/functions/processGenerateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1033/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1055/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1105/fixture.yaml
Labels: Review effort 2/5

#1350 🚸 Render logo text on hover in GlobalNav
  frontend/apps/app/components/CommonLayout/GlobalNav/GlobalNav.module.css
  frontend/apps/app/components/CommonLayout/GlobalNav/GlobalNav.tsx
  frontend/packages/ui/src/logos/LiamMigrationLogo.tsx
Labels: Review effort 2/5

#1356 🐛(jobs): Add src/tasks directory to trigger.config.ts
  frontend/packages/jobs/trigger.config.ts
Labels: Review effort 1/5

#1355 🔧(schema): Update schema overrides and improve validation error reporting
  .liam/schema-override.yml
  frontend/packages/db-structure/src/schema/schema.ts
Labels: Review effort 2/5

#1363 ✨ add TableGroupNode type and enhance styles with hover effects
  .changeset/flat-bats-grab.md
  .changeset/slimy-worms-share.md
  frontend/packages/e2e/tests/vrt/vrt.test.ts-snapshots/top-1-chromium-linux.png
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableGroupNode/TableGroupNode.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableGroupNode/TableGroupNode.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/FitviewButton/Fitview.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/GroupButton/GroupButton.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/TidyUpButton/TidyUpButton.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/ZoomControls/ZoomControls.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/ZoomControls/ZoomControls.tsx
  frontend/packages/erd-core/src/features/erd/types.ts
  frontend/packages/ui/src/icons/MessageSquareText.tsx
  frontend/packages/ui/src/icons/index.ts
  frontend/packages/ui/src/styles/Dark/variables.css
Labels: Review effort 2/5

#1353 Rename `schemaMeta` to `schemaOverride`
  .ai-agents/memory-bank/activeContext.md
  .ai-agents/memory-bank/progress.md
  .ai-agents/memory-bank/systemPatterns.md
  .ai-agents/memory-bank/techContext.md
  frontend/apps/app/app/api/schema/override/route.ts
  frontend/apps/app/app/erd/p/[...slug]/page.tsx
  frontend/apps/docs/content/docs/cli/ci-cd.mdx
  frontend/apps/docs/content/docs/contributing/adr/20250116-use-dmmf-for-prisma-schema-parsing.mdx
  frontend/apps/docs/content/docs/contributing/repository-architecture.mdx
  frontend/apps/docs/content/docs/parser/supported-formats/prisma.mdx
  frontend/apps/docs/content/docs/parser/supported-formats/rails.mdx
  frontend/apps/docs/content/docs/parser/supported-formats/tbls.mdx
  frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
  frontend/packages/jobs/src/functions/processGenerateSchemaOverride.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/generateDocsSuggestion.ts
  frontend/packages/jobs/src/prompts/generateSchemaOverride/generateSchemaOverride.ts
  frontend/packages/jobs/src/tasks/review/saveReview.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/types/index.ts
  frontend/packages/jobs/src/utils/schemaUtils.ts
  frontend/packages/prompt-test/README.md
Labels: Review effort 2/5

#1369 fix: treat schema override content as YAML
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/utils/schemaUtils.ts
  pnpm-lock.yaml
Labels: Review effort 1/5

#1370 Project-detail-design
  frontend/apps/app/features/projects/components/EmptyProjectsState/EmptyProjectsState.module.css
  frontend/apps/app/features/projects/components/EmptyProjectsState/EmptyProjectsState.tsx
  frontend/apps/app/features/projects/components/EmptyProjectsState/index.ts
  frontend/apps/app/features/projects/components/ProjectItem/ProjectItem.module.css
  frontend/apps/app/features/projects/components/ProjectItem/ProjectItem.tsx
  frontend/apps/app/features/projects/components/ProjectItem/index.ts
  frontend/apps/app/features/projects/components/index.ts
  frontend/apps/app/features/projects/pages/ProjectsPage/ProjectsPage.module.css
  frontend/apps/app/features/projects/pages/ProjectsPage/ProjectsPage.tsx
  frontend/packages/ui/src/icons/ProjectIcon.tsx
  frontend/packages/ui/src/icons/SearchIcon.tsx
  frontend/packages/ui/src/icons/index.ts
  frontend/packages/ui/src/illustrations/JackInBox.tsx
  frontend/packages/ui/src/illustrations/index.ts
  frontend/packages/ui/src/index.ts
  frontend/packages/ui/src/logos/GithubLogo.tsx
Labels: Review effort 2/5

#1374 ♻️ Add SchemaPage with ERDEditor, safe override utility, constants
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/schema/[...schemaFilePath]/page.tsx
  frontend/apps/app/app/api/schema/override/route.ts
  frontend/apps/app/features/schemas/constants.ts
  frontend/apps/app/features/schemas/pages/SchemaPage/SchemaPage.tsx
  frontend/apps/app/features/schemas/pages/SchemaPage/components/ERDEditor/ERDEditor.tsx
  frontend/apps/app/features/schemas/pages/SchemaPage/components/ERDEditor/index.ts
  frontend/apps/app/features/schemas/pages/SchemaPage/index.ts
  frontend/apps/app/features/schemas/pages/SchemaPage/utils/safeApplySchemaOverride.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
Labels: Review effort 3/5

#1379 Refactor project list components and improve styling consistency
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/components/EmptyProjectsState/EmptyProjectsState.module.css
  frontend/apps/app/features/projects/components/EmptyProjectsState/EmptyProjectsState.tsx
  frontend/apps/app/features/projects/components/EmptyProjectsState/JackInBox.tsx
  frontend/apps/app/features/projects/components/ProjectItem/ProjectIcon.tsx
  frontend/apps/app/features/projects/components/ProjectItem/ProjectItem.module.css
  frontend/apps/app/features/projects/components/ProjectItem/ProjectItem.tsx
  frontend/apps/app/features/projects/components/SearchInput/SearchInput.module.css
  frontend/apps/app/features/projects/components/SearchInput/SearchInput.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectNewPage/InstallationSelector/InstallationSelector.tsx
  frontend/apps/app/features/projects/pages/ProjectsPage/ProjectsPage.module.css
  frontend/apps/app/package.json
  frontend/packages/ui/src/icons/SearchIcon.tsx
  frontend/packages/ui/src/icons/index.ts
  frontend/packages/ui/src/illustrations/JackInBox.tsx
  frontend/packages/ui/src/illustrations/index.ts
  frontend/packages/ui/src/index.ts
  frontend/packages/ui/src/logos/GithubLogo.tsx
Labels: Review effort 2/5

#1361 ✨ Add Appbar component
  .clinerules/general.md
  frontend/apps/app/app/api/projects/[projectId]/route.ts
  frontend/apps/app/components/AppBar/AppBar.module.css
  frontend/apps/app/components/AppBar/AppBar.tsx
  frontend/apps/app/components/AppBar/index.ts
  frontend/apps/app/components/CommonLayout/ClientAppBar.tsx
  frontend/apps/app/components/CommonLayout/CommonLayout.module.css
  frontend/apps/app/components/CommonLayout/CommonLayout.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/getProject.ts
  frontend/packages/github/src/api.server.ts
  frontend/packages/ui/src/components/Avatar/Avatar.module.css
  frontend/packages/ui/src/components/Avatar/Avatar.tsx
  frontend/packages/ui/src/components/Avatar/UserAvatarIcon.tsx
  frontend/packages/ui/src/components/Avatar/index.ts
  frontend/packages/ui/src/components/IconButton/IconButton.tsx
  frontend/packages/ui/src/components/Tooltip/Tooltip.tsx
  frontend/packages/ui/src/components/index.ts
  frontend/packages/ui/src/icons/index.ts
  frontend/packages/ui/src/styles/Dark/variables.css
Labels: Review effort 3/5

#1367 ✨ Add TableGroupNode when creating a bounding box on ERDContent
  .changeset/open-rats-clean.md
  frontend/packages/erd-core/src/features/erd/components/ERDContent/ERDContent.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/ERDContent.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableGroupBoundingBox/TableGroupBoundingBox.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableGroupBoundingBox/TableGroupBoundingBox.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableGroupBoundingBox/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/hooks/useTableGroupBoundingBox.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/DesktopToolbar.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/GroupButton/GroupButton.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/MobileToolbar/MobileToolbar.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/MobileToolbar/OpenedMobileToolbar.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/Toolbar.tsx
  frontend/packages/erd-core/src/stores/userEditing/store.ts
Labels: Review effort 3/5

#1381 🐛 Update package.json scripts for CSS processing to exclude specific directories
  frontend/apps/app/package.json
Labels: Review effort 1/5

#1382 ✨ Add SchemaHeader component with tabbed ERD/OverrideEditor toggle
  .changeset/common-breads-tell.md
  frontend/apps/app/features/schemas/pages/SchemaPage/SchemaPage.tsx
  frontend/apps/app/features/schemas/pages/SchemaPage/components/SchemaHeader/SchemaHeader.module.css
  frontend/apps/app/features/schemas/pages/SchemaPage/components/SchemaHeader/SchemaHeader.tsx
  frontend/apps/app/features/schemas/pages/SchemaPage/components/SchemaHeader/index.ts
  frontend/apps/app/features/schemas/pages/SchemaPage/constants.ts
  frontend/packages/ui/package.json
  frontend/packages/ui/src/components/Tabs/Tabs.tsx
  frontend/packages/ui/src/components/Tabs/index.ts
  frontend/packages/ui/src/components/index.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#1359 🔧(jobs): Enhance docs suggestion with structured review feedback
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/generateDocsSuggestion.ts
  frontend/packages/jobs/src/tasks/review/generateReview.ts
  frontend/packages/jobs/src/tasks/review/saveReview.ts
  frontend/packages/jobs/src/trigger/jobs.ts
Labels: Review effort 2/5

#1371 Generate knowledge on feedback resolved
  frontend/apps/app/features/migrations/actions/resolveReviewFeedback.ts
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250416155758_create_review_feedback_knowledge_suggestion_mapping.sql
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/index.ts
  frontend/packages/jobs/src/tasks/review/saveReview.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/types/index.ts
  frontend/packages/jobs/src/utils/categoryUtils.ts
Labels: Review effort 3/5

#1385 ✨ Add OverrideEditor component and useYamlEditor hook for YAML editing functionality
  frontend/apps/app/features/schemas/pages/SchemaPage/SchemaPage.module.css
  frontend/apps/app/features/schemas/pages/SchemaPage/SchemaPage.tsx
  frontend/apps/app/features/schemas/pages/SchemaPage/components/OverrideEditor/OverrideEditor.module.css
  frontend/apps/app/features/schemas/pages/SchemaPage/components/OverrideEditor/OverrideEditor.tsx
  frontend/apps/app/features/schemas/pages/SchemaPage/components/OverrideEditor/index.ts
  frontend/apps/app/features/schemas/pages/SchemaPage/components/OverrideEditor/useYamlEditor.tsx
  frontend/apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1393 ✨️ Add SchemaLink component
  frontend/apps/app/components/FormatIcon/FormatIcon.module.css
  frontend/apps/app/components/FormatIcon/FormatIcon.tsx
  frontend/apps/app/components/FormatIcon/icons/PostgresIcon.tsx
  frontend/apps/app/components/FormatIcon/icons/PrismaIcon.tsx
  frontend/apps/app/components/FormatIcon/icons/SchemaRbIcon.tsx
  frontend/apps/app/components/FormatIcon/icons/TblsIcon.tsx
  frontend/apps/app/components/FormatIcon/icons/index.ts
  frontend/apps/app/components/FormatIcon/icons/types.ts
  frontend/apps/app/components/FormatIcon/index.ts
  frontend/apps/app/components/SchemaLink/SchemaLink.module.css
  frontend/apps/app/components/SchemaLink/SchemaLink.tsx
  frontend/apps/app/components/SchemaLink/index.ts
  frontend/apps/app/features/schemas/pages/SchemaPage/components/SchemaHeader/SchemaHeader.module.css
  frontend/apps/app/features/schemas/pages/SchemaPage/components/SchemaHeader/SchemaHeader.tsx
  frontend/apps/app/public/assets/schema-rb-icon.png
  frontend/packages/ui/src/icons/index.ts
Labels: Review effort 2/5

#1399 📝(guidelines): Add Supabase Error Handling Guidelines
  .clinerules/general.md
Labels: Review effort 1/5

#1395 ✨ Add DiffCounts component
  frontend/apps/app/components/DiffCount/DiffCount.module.css
  frontend/apps/app/components/DiffCount/DiffCount.tsx
  frontend/apps/app/components/DiffCount/DiffCounts.module.css
  frontend/apps/app/components/DiffCount/DiffCounts.tsx
  frontend/apps/app/components/DiffCount/index.ts
  frontend/apps/app/features/schemas/pages/SchemaPage/components/SchemaHeader/SchemaHeader.module.css
  frontend/apps/app/features/schemas/pages/SchemaPage/components/SchemaHeader/SchemaHeader.tsx
Labels: Review effort 2/5

#1386 ✨ enhance the Prisma parser to support Constraints
  .changeset/salty-dryers-grab.md
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
Labels: Review effort 2/5

#1402 🔧 Organization setting general page
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/GeneralPage.module.css
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/GeneralPage.tsx
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/index.ts
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/page.tsx
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/layout.module.css
  frontend/apps/app/app/layout.tsx
Labels: Review effort 2/5

#1404 Enhance organization creation form layout and styling
  frontend/apps/app/features/organizations/actions/createOrganizations.ts
  frontend/apps/app/features/organizations/pages/OrganizationNewPage/OrganizationNewPage.module.css
  frontend/apps/app/features/organizations/pages/OrganizationNewPage/OrganizationNewPage.tsx
Labels: Review effort 2/5

#1400 ✨(organizations): Add member invitation functionality
  frontend/apps/app/features/organizations/actions/inviteMember.ts
  frontend/apps/app/features/organizations/pages/OrganizationMembersPage/ClientSearchWrapper.tsx
  frontend/apps/app/features/organizations/pages/OrganizationMembersPage/InviteMemberModal.module.css
  frontend/apps/app/features/organizations/pages/OrganizationMembersPage/InviteMemberModal.tsx
  frontend/packages/ui/src/components/Modal/Modal.module.css
Labels: Review effort 3/5

#1255 Feat/support for many_to_many relationship
  .changeset/seven-dolphins-itch.md
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
  frontend/packages/db-structure/src/schema/factories.ts
Labels: Review effort 3/5

#1419 docs: add Product Required Document
  docs/liam-migration-v1/product-required-document.md
Labels: Review effort 2/5

#1428 🔧 Enable page scrolling in commonLayout
  frontend/apps/app/components/CommonLayout/CommonLayout.module.css
Labels: Review effort 1/5

#1418 ✨(settings): Improve settings tab functionality with proper routing
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/components/SettingsHeader/SettingsHeader.tsx
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/constants.ts
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/layout.tsx
  frontend/apps/app/app/types.ts
  frontend/apps/app/middleware.ts
  frontend/apps/app/utils/routes/routeDefinitions.ts
Labels: Review effort 2/5

#1426 ♻️(database): Rename 'repositories' to 'github_repositories' for clarity
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/getProjectRepository.test.ts
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/getProjectRepository.ts
  frontend/apps/app/app/api/schema/override/route.ts
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/actions/addProject.ts
  frontend/apps/app/features/projects/components/ProjectItem/ProjectItem.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/ContentForSchema.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectBranchesListPage/ProjectBranchesListPage.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/getProject.ts
  frontend/apps/app/features/projects/types/project.ts
  frontend/apps/app/features/schemas/pages/SchemaPage/SchemaPage.tsx
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250421081804_rename_github_tables.sql
  frontend/packages/jobs/src/functions/getInstallationIdFromRepositoryId.ts
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateSchemaOverride.ts
  frontend/packages/jobs/src/tasks/review/__tests__/postComment.test.ts
  frontend/packages/jobs/src/tasks/review/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/tasks/review/generateReview.ts
  frontend/packages/jobs/src/tasks/review/postComment.ts
  frontend/packages/jobs/src/tasks/review/savePullRequest.ts
  frontend/packages/jobs/src/tasks/review/saveReview.ts
Labels: Review effort 2/5

#1429 ♻️(organizations): Remove OrganizationDetailPage in favor of direct project routing
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/page.tsx
  frontend/apps/app/features/organizations/components/OrganizationSwitcher/OrganizationSwitcher.tsx
  frontend/apps/app/features/organizations/pages/OrganizationDetailPage/OrganizationDetailPage.module.css
  frontend/apps/app/features/organizations/pages/OrganizationDetailPage/OrganizationDetailPage.tsx
  frontend/apps/app/features/organizations/pages/OrganizationDetailPage/getOrganizationDetails.ts
  frontend/apps/app/features/organizations/pages/OrganizationDetailPage/index.ts
  frontend/apps/app/features/organizations/pages/OrganizationsPage/OrganizationsPage.tsx
  frontend/apps/app/utils/routes/routeDefinitions.ts
Labels: Review effort 2/5

#1430 🐛(ui): Fix Server Component error by removing onClick prop from SchemaLink
  frontend/apps/app/components/SchemaLink/SchemaLink.tsx
Labels: Review effort 1/5

#1423 ✨(ui): Add loading state to Button component with Spinner
  frontend/apps/app/features/organizations/pages/OrganizationMembersPage/InviteMemberModal.tsx
  frontend/packages/ui/src/components/Button/Button.module.css
  frontend/packages/ui/src/components/Button/Button.tsx
  frontend/packages/ui/src/components/Spinner/Spinner.module.css
  frontend/packages/ui/src/components/Spinner/Spinner.tsx
  frontend/packages/ui/src/components/Spinner/index.ts
Labels: Review effort 2/5

#1403 ♻️(db): Rename membership_invites table to invitations
  .liam/schema-override.yml
  frontend/apps/app/features/organizations/actions/inviteMember.ts
  frontend/apps/app/features/organizations/pages/OrganizationMembersPage/getMembersAndInvites.ts
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250418082113_rename_membership_invites_to_invitations.sql
Labels: Review effort 2/5

#1420 🔧Fix get organization function to server component and ✨add delete organization
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/DeleteConfirmationModal.module.css
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/DeleteConfirmationModal.tsx
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/DeleteOrganizationButton.tsx
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/DeleteOrganizationButtonClient.module.css
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/DeleteOrganizationButtonClient.tsx
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/GeneralPage.module.css
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/GeneralPage.tsx
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/GeneralPageClient.tsx
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/settings/general/page.tsx
  frontend/apps/app/app/(app)/app/organizations/page.tsx
  frontend/apps/app/features/organizations/actions/organizationActions.ts
  frontend/apps/app/features/organizations/actions/organizationClientActions.ts
  frontend/apps/app/features/organizations/pages/OrganizationsPage/OrganizationsPage.tsx
  frontend/apps/app/features/organizations/pages/OrganizationsPage/OrganizationsPageClient.tsx
  frontend/apps/app/features/organizations/services/organizationService.ts
  frontend/packages/ui/src/components/Callout/Callout.module.css
  frontend/packages/ui/src/components/Callout/Callout.tsx
  frontend/packages/ui/src/components/Callout/index.ts
  frontend/packages/ui/src/components/index.ts
Labels: Review effort 3/5

#1434 ♻️(database): Refactor github_repositories table structure and naming
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/getDocumentContent.ts
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/getProjectRepository.test.ts
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/getProjectRepository.ts
  frontend/apps/app/app/api/schema/override/route.ts
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/actions/addProject.ts
  frontend/apps/app/features/projects/components/ProjectItem/ProjectItem.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/ContentForSchema.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectBranchesListPage/ProjectBranchesListPage.tsx
  frontend/apps/app/features/projects/pages/ProjectNewPage/InstallationSelector/InstallationSelector.tsx
  frontend/apps/app/features/projects/pages/ProjectsPage/ServerProjectsDataProvider.tsx
  frontend/apps/app/features/projects/pages/ProjectsPage/getProjects.ts
  frontend/apps/app/features/projects/utils/getOriginalDocumentContent.ts
  frontend/apps/app/features/schemas/pages/SchemaPage/SchemaPage.tsx
  frontend/apps/app/features/schemas/pages/SchemaPage/utils/safeApplySchemaOverride.ts
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250422034040_modify_github_repositories.sql
  frontend/packages/jobs/src/functions/getInstallationIdFromRepositoryId.ts
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateSchemaOverride.ts
  frontend/packages/jobs/src/tasks/review/__tests__/postComment.test.ts
  frontend/packages/jobs/src/tasks/review/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/tasks/review/generateReview.ts
  frontend/packages/jobs/src/tasks/review/postComment.ts
  frontend/packages/jobs/src/tasks/review/savePullRequest.ts
Labels: Review effort 3/5

#1437 🔧 fix: Correct table name in projects query
  frontend/apps/app/features/projects/pages/ProjectsPage/ProjectsPage.tsx
  frontend/apps/app/features/projects/pages/ProjectsPage/getProjects.ts
Labels: Review effort 2/5

#1439 Revert "Remove NOT NULL and UNIQUE constraints from github_repositories migration"
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250422034040_modify_github_repositories.sql
  frontend/packages/jobs/src/tasks/review/savePullRequest.ts
Labels: Review effort 2/5

#1442 🐛 Fix repository reference in BranchDetailPage
  frontend/apps/app/features/projects/pages/BranchDetailPage/BranchDetailPage.tsx
Labels: Review effort 1/5

#1435 ♻️(database): Refactor GitHub PR comments into separate table
  .liam/schema-override.yml
  docs/migrationOpsContext.md
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250422051514_refactor_github_pull_requests.sql
  frontend/packages/jobs/src/tasks/review/__tests__/postComment.test.ts
  frontend/packages/jobs/src/tasks/review/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/tasks/review/postComment.ts
Labels: Review effort 3/5

#1441 📝 Add documentation for github_repository_identifier column
  .liam/schema-override.yml
Labels: Review effort 1/5

#1440 Rewrite schema design guidelines with structured sections and expanded best practices
  docs/schemaPatterns.md
Labels: Review effort 2/5

#1444 chore: group langfuse packages in renovate.json
  renovate.json
Labels: Review effort 1/5

#1451 🔒️ Enable RLS on users table and add policy to allow access to users in the same organization
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/migrations/20250423040522_users_table_policy.sql
Labels: Review effort 2/5

#1455 🔧 Fetch user information and handle not found cases in project pages
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/projects/new/page.tsx
  frontend/apps/app/app/(app)/app/organizations/[organizationId]/projects/page.tsx
Labels: Review effort 2/5

#1454 🐛 fix resolveReviewFeedback.ts query
  frontend/apps/app/features/migrations/actions/resolveReviewFeedback.ts
Labels: Review effort 2/5

#1453 ♻️(db): decouple migrations from GitHub dependencies
  .liam/schema-override.yml
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/getProject.ts
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250423064420_update_migrations_table.sql
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/tasks/review/__tests__/postComment.test.ts
  frontend/packages/jobs/src/tasks/review/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/tasks/review/postComment.ts
  frontend/packages/jobs/src/tasks/review/savePullRequest.ts
Labels: Review effort 4/5
