Repository liam-hq/liam, pull requests merged in 2025-06, with the labels that each got.

#1812 Add Star History section
  README.md
Labels: Review effort 1/5, codex

#1835 Chore: migrate "resolutions" to "pnpm.overrides" for version fixes
  package.json
Labels: Review effort 1/5

#1830 ♻️ refactor: implement chat message processing in a dedicated function
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/lib/chat/chatProcessor.ts
Labels: Review effort 2/5

#1829 🔧 Rely on ubuntu-latest default Ruby instead of explicitly setting version
  .github/workflows/license-report-update.yml
  .github/workflows/license.yml
Labels: Review effort 1/5

#1809 feat: add design session creation and detail view pages
  frontend/apps/app/app/(app)/app/(with-project-and-branch)/projects/[projectId]/sessions/[id]/page.tsx
  frontend/apps/app/app/(app)/app/(with-project-and-branch)/projects/[projectId]/sessions/layout.tsx
  frontend/apps/app/app/(app)/app/(with-project-and-branch)/projects/[projectId]/sessions/new/page.tsx
  frontend/apps/app/app/api/sessions/route.ts
  frontend/apps/app/components/Chat/AgentMessage/AgentMessage.tsx
  frontend/apps/app/components/CommonLayout/AppBar/AppBar.module.css
  frontend/apps/app/components/CommonLayout/AppBar/AppBar.tsx
  frontend/apps/app/components/ProjectLayout/ProjectLayout.tsx
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.module.css
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.tsx
  frontend/apps/app/components/SessionDetailPage/index.ts
  frontend/apps/app/components/SessionDetailPage/services/fetchSchemaData.ts
  frontend/apps/app/components/SessionsNewPage/SessionsNewPage.module.css
  frontend/apps/app/components/SessionsNewPage/SessionsNewPage.tsx
  frontend/apps/app/components/SessionsNewPage/index.ts
Labels: Review effort 3/5

#1831 feat(chat): persist messages to database using Supabase
  frontend/apps/app/app/(app)/app/(with-project-and-branch)/projects/[projectId]/sessions/[id]/page.tsx
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/services/index.ts
  frontend/apps/app/components/Chat/services/messageServiceClient.ts
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.tsx
Labels: Review effort 3/5

#1856 🐛(knip): Fix remaining knip configuration errors
  frontend/apps/app/package.json
  knip.jsonc
  pnpm-lock.yaml
Labels: Review effort 1/5

#1851 Add LangGraph workflow
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/lib/chat/chatProcessor.ts
  frontend/apps/app/lib/chat/workflow/README.md
  frontend/apps/app/lib/chat/workflow/index.ts
  frontend/apps/app/lib/chat/workflow/nodes/answerGenerationNode.ts
  frontend/apps/app/lib/chat/workflow/nodes/finalResponseNode.ts
  frontend/apps/app/lib/chat/workflow/nodes/index.ts
  frontend/apps/app/lib/chat/workflow/nodes/validationNode.ts
  frontend/apps/app/lib/chat/workflow/types.ts
  frontend/apps/app/lib/chat/workflow/workflow.test.ts
  frontend/apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 4/5

#1850 🔧 Refactor: remove unused constants, functions, and types from the jobs package; update package.json and pnpm-lock.yaml to reflect dependency changes
  .changeset/config.json
  .github/workflows/prompt-test.yml
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/app/api/webhook/helloworld/route.ts
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/constants.ts
  frontend/packages/jobs/src/functions/getInstallationIdFromRepositoryId.ts
  frontend/packages/jobs/src/functions/langfuseLangchainHandler.ts
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateSchemaOverride.ts
  frontend/packages/jobs/src/index.ts
  frontend/packages/jobs/src/libs/supabase.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/docsSuggestionSchema.ts
  frontend/packages/jobs/src/prompts/generateDocsSuggestion/generateDocsSuggestion.ts
  frontend/packages/jobs/src/prompts/generateReview/generateReview.ts
  frontend/packages/jobs/src/prompts/generateReview/index.ts
  frontend/packages/jobs/src/prompts/generateReview/reviewSchema.ts
  frontend/packages/jobs/src/prompts/generateSchemaOverride/generateSchemaOverride.ts
  frontend/packages/jobs/src/prompts/index.ts
  frontend/packages/jobs/src/tasks/review/generateReview.ts
  frontend/packages/jobs/src/tasks/review/index.ts
  frontend/packages/jobs/src/tasks/review/postComment.ts
  frontend/packages/jobs/src/tasks/review/savePullRequest.ts
  frontend/packages/jobs/src/tasks/review/saveReview.ts
  frontend/packages/jobs/src/trigger/helloworld.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/types/index.ts
  frontend/packages/jobs/src/utils/categoryUtils.ts
  frontend/packages/jobs/src/utils/githubFileUtils.ts
  frontend/packages/jobs/src/utils/schemaUtils.ts
  frontend/packages/prompt-test/.env
  frontend/packages/prompt-test/.env.local
  frontend/packages/prompt-test/.gitignore
  frontend/packages/prompt-test/README.md
  frontend/packages/prompt-test/biome.jsonc
  frontend/packages/prompt-test/eslint.config.mjs
  frontend/packages/prompt-test/package.json
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1033/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1055/fixture.yaml
  frontend/packages/prompt-test/src/fixtures/github.com/liam-hq/liam/pull/1105/fixture.yaml
  frontend/packages/prompt-test/src/index.ts
  frontend/packages/prompt-test/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1859 Switch Mastra to LangChain
  config/dependency_decisions.yml
  docs/packages-license.md
  frontend/apps/app/.gitignore
  frontend/apps/app/lib/chat/chatProcessor.ts
  frontend/apps/app/lib/chat/workflow/index.ts
  frontend/apps/app/lib/chat/workflow/nodes/answerGenerationNode.ts
  frontend/apps/app/lib/chat/workflow/types.ts
  frontend/apps/app/lib/chat/workflow/workflow.test.ts
  frontend/apps/app/lib/langchain/agents/databaseSchemaAskAgent/agent.ts
  frontend/apps/app/lib/langchain/agents/databaseSchemaAskAgent/index.ts
  frontend/apps/app/lib/langchain/agents/databaseSchemaAskAgent/prompts.ts
  frontend/apps/app/lib/langchain/agents/databaseSchemaBuildAgent/agent.ts
  frontend/apps/app/lib/langchain/agents/databaseSchemaBuildAgent/index.ts
  frontend/apps/app/lib/langchain/agents/databaseSchemaBuildAgent/prompts.ts
  frontend/apps/app/lib/langchain/agents/index.ts
  frontend/apps/app/lib/langchain/index.ts
  frontend/apps/app/lib/langchain/utils/telemetry.ts
  frontend/apps/app/lib/langchain/utils/types.ts
  frontend/apps/app/lib/mastra/agents/databaseSchemaAskAgent.ts
  frontend/apps/app/lib/mastra/agents/databaseSchemaBuildAgent.ts
  frontend/apps/app/lib/mastra/agents/index.ts
  frontend/apps/app/lib/mastra/index.ts
  frontend/apps/app/next.config.ts
  frontend/apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#1877 Add step streaming and text streaming
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/components/Chat/AgentMessage/AgentMessage.module.css
  frontend/apps/app/components/Chat/AgentMessage/AgentMessage.tsx
  frontend/apps/app/components/Chat/Chat.module.css
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/constants/chatConstants.ts
  frontend/apps/app/components/Chat/services/messageHelpers.ts
  frontend/apps/app/components/Chat/types/chatTypes.ts
  frontend/apps/app/components/ChatMessage/ChatMessage.tsx
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.module.css
  frontend/apps/app/lib/chat/chatProcessor.ts
  frontend/apps/app/lib/chat/workflow/constants/progressMessages.ts
  frontend/apps/app/lib/chat/workflow/index.ts
  frontend/apps/app/lib/chat/workflow/nodes/finalResponseNode.ts
  frontend/apps/app/lib/chat/workflow/services/langGraphWorkflow.ts
  frontend/apps/app/lib/chat/workflow/services/stateManager.ts
  frontend/apps/app/lib/chat/workflow/services/workflowSteps.ts
  frontend/apps/app/lib/chat/workflow/streaming/streamingWorkflow.ts
  frontend/apps/app/lib/chat/workflow/types.ts
  frontend/apps/app/lib/langchain/index.ts
  frontend/apps/app/lib/langchain/utils/types.ts
Labels: Review effort 4/5

#1879 storybook: change default background to dark
  frontend/internal-packages/storybook/.storybook/preview.ts
Labels: Review effort 1/5

#1832 feat(chat): enable real-time chat updates with Supabase subscription
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/services/messageServiceClient.ts
  frontend/internal-packages/db/schema/schema.sql
  frontend/internal-packages/db/supabase/migrations/20250529210000_add_indexes_to_messages.sql
  frontend/internal-packages/db/supabase/migrations/20250603220001_supabase_realtime_to_messages.sql
Labels: Review effort 3/5

#1786 Feat/table name tooltip for only truncated text
  .changeset/hip-times-wink.md
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableHeader/TableHeader.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableHeader/TableHeader.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableNode.tsx
  frontend/packages/erd-core/src/features/erd/types.ts
  frontend/packages/erd-core/src/features/erd/utils/highlightNodesAndEdges.test.ts
Labels: Review effort 2/5

#1876 🔄 Refactor: Implement project-independent design sessions
  frontend/apps/app/app/(app)/app/(with-project-and-branch)/projects/[projectId]/sessions/[id]/page.tsx
  frontend/apps/app/app/(app)/app/(with-project-and-branch)/projects/[projectId]/sessions/new/page.tsx
  frontend/apps/app/app/(app)/app/design_sessions/[id]/page.tsx
  frontend/apps/app/app/(app)/app/design_sessions/[id]/services/fetchDesignSessionData.ts
  frontend/apps/app/app/(app)/app/design_sessions/new/page.tsx
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/app/lib/vectorstore/syncSchemaVectorStore.ts
  frontend/apps/app/components/BuildPage/BuildPage.tsx
  frontend/apps/app/components/BuildPage/Panel/Panel.tsx
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.tsx
  frontend/apps/app/components/SessionsNewPage/SessionsNewPage.tsx
  frontend/apps/app/lib/chat/chatProcessor.ts
  frontend/apps/app/lib/chat/workflow/nodes/validationNode.ts
  frontend/apps/app/lib/chat/workflow/workflow.test.ts
Labels: Review effort 3/5

#1873 feat(command palette): install empty CommandPalette for the first step of the CommandPalette feature
  frontend/packages/erd-core/package.json
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
  frontend/packages/ui/src/styles/variables.css
  package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1907 ♻️(sessions): Refactor session creation to use Server Actions
  frontend/apps/app/app/api/sessions/route.ts
  frontend/apps/app/components/SessionsNewPage/SessionsNewPage.tsx
  frontend/apps/app/components/SessionsNewPage/actions/createSession.ts
  frontend/internal-packages/db/src/index.ts
Labels: Review effort 3/5

#1911 chore(seed): add second test user and link both users to organization for easy testing
  frontend/internal-packages/db/supabase/seed.sql
Labels: Review effort 1/5

#1915 ✨(agent): Initialize agent package with TypeScript configuration
  frontend/internal-packages/agent/.gitignore
  frontend/internal-packages/agent/biome.jsonc
  frontend/internal-packages/agent/eslint.config.mjs
  frontend/internal-packages/agent/package.json
  frontend/internal-packages/agent/src/agent.ts
  frontend/internal-packages/agent/src/index.ts
  frontend/internal-packages/agent/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 1/5

#1912 feat(sessions): enhance SessionsNewPage with project and branch selection
  frontend/apps/app/app/(app)/app/design_sessions/new/page.tsx
  frontend/apps/app/components/SessionsNewPage/SessionsNewPage.module.css
  frontend/apps/app/components/SessionsNewPage/SessionsNewPage.tsx
  frontend/apps/app/components/SessionsNewPage/actions/getBranches.ts
Labels: Review effort 3/5

#1941 🧹(deps): Remove unnecessary dependencies and update knip configuration
  frontend/apps/app/package.json
  frontend/apps/docs/package.json
  frontend/internal-packages/configs/package.json
  frontend/internal-packages/jobs/package.json
  frontend/packages/cli/package.json
  frontend/packages/erd-core/package.json
  knip.jsonc
  pnpm-lock.yaml
Labels: Review effort 2/5

#1939 refactor: migrate agent package
  frontend/apps/app/app/(app)/app/design_sessions/[id]/services/fetchDesignSessionData.ts
  frontend/apps/app/app/api/buildingSchemas/versions/route.ts
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/ChatbotButton/ChatbotButton.tsx
  frontend/apps/app/components/ChatbotButton/components/ChatbotDialog/ChatbotDialog.tsx
  frontend/apps/app/lib/langchain/utils/telemetry.ts
  frontend/apps/app/libs/schema/index.ts
  frontend/apps/app/package.json
  frontend/internal-packages/agent/package.json
  frontend/internal-packages/agent/src/agent.ts
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  frontend/internal-packages/agent/src/chat/workflow/README.md
  frontend/internal-packages/agent/src/chat/workflow/constants/progressMessages.ts
  frontend/internal-packages/agent/src/chat/workflow/index.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/answerGenerationNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalResponseNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/index.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/validationNode.ts
  frontend/internal-packages/agent/src/chat/workflow/services/langGraphWorkflow.ts
  frontend/internal-packages/agent/src/chat/workflow/services/stateManager.ts
  frontend/internal-packages/agent/src/chat/workflow/services/workflowSteps.ts
  frontend/internal-packages/agent/src/chat/workflow/streaming/streamingWorkflow.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/db/server.ts
  frontend/internal-packages/agent/src/index.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaAskAgent/agent.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaAskAgent/index.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaAskAgent/prompts.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/agent.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/index.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/prompts.ts
  frontend/internal-packages/agent/src/langchain/agents/index.ts
  frontend/internal-packages/agent/src/langchain/index.ts
  frontend/internal-packages/agent/src/langchain/utils/telemetry.ts
  frontend/internal-packages/agent/src/langchain/utils/types.ts
  frontend/internal-packages/agent/src/utils/__tests__/applyPatchOperations.test.ts
  frontend/internal-packages/agent/src/utils/applyPatchOperations.ts
  frontend/internal-packages/agent/src/utils/convertSchemaToText.ts
  frontend/internal-packages/agent/src/utils/createNewVersion.ts
  frontend/internal-packages/agent/src/utils/operationsSchema.ts
  frontend/internal-packages/agent/src/vectorstore/index.ts
  frontend/internal-packages/agent/src/vectorstore/supabaseVectorStore.ts
  frontend/internal-packages/agent/src/vectorstore/syncSchemaVectorStore.ts
  pnpm-lock.yaml
Labels: Review effort 4/5

#1955 chore: temporarily update contact email due to infrastructure migration
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT_ja.md
  SECURITY.md
Labels: Review effort 1/5

#1956 Update model version in `DatabaseSchemaAskAgent` and `DatabaseSchemaBuildAgent`
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaAskAgent/agent.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/agent.ts
Labels: Review effort 1/5

#1958 refactor: implement non-streaming workflow in LangGraph
  frontend/internal-packages/agent/src/chat/workflow/index.ts
  frontend/internal-packages/agent/src/chat/workflow/services/nonStreamingWorkflow.ts
Labels: Review effort 2/5

#1920 feat(schema): refactor schema fetching logic to unify data source and simplify update handling
  frontend/apps/app/app/(app)/app/design_sessions/[id]/page.tsx
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.tsx
  frontend/apps/app/components/SessionDetailPage/services/buildingSchemaServiceClient.ts
  frontend/internal-packages/agent/src/chat/workflow/services/nonStreamingWorkflow.ts
  frontend/internal-packages/agent/src/index.ts
  frontend/internal-packages/agent/src/utils/fetchSchemaData.ts
Labels: Review effort 4/5

#1950 feat: enhance SessionsNewPage with initial message saving functionality
  frontend/apps/app/components/SessionsNewPage/SessionsNewPage.tsx
  frontend/apps/app/components/SessionsNewPage/actions/createSession.ts
Labels: Review effort 3/5

#1971 Temporarily disable vector store sync (unused & timeout workaround)
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  knip.jsonc
Labels: Review effort 2/5

#1966 ✨(chat): Remove Ask mode and unify to Build-only architecture
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/components/Chat/AgentAvatar/AskAgent.stories.tsx
  frontend/apps/app/components/Chat/AgentAvatar/AskAgent.tsx
  frontend/apps/app/components/Chat/AgentMessage/AgentMessage.stories.tsx
  frontend/apps/app/components/Chat/AgentMessage/AgentMessage.tsx
  frontend/apps/app/components/Chat/AgentMessage/index.ts
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/MessageOptionButton.stories.tsx
  frontend/apps/app/components/Chat/MessageOptionButton.tsx
  frontend/apps/app/components/Chat/MessageOptionButtons.tsx
  frontend/apps/app/components/Chat/constants/chatConstants.ts
  frontend/apps/app/components/Chat/hooks/useRealtimeMessages.ts
  frontend/apps/app/components/Chat/services/aiMessageService.ts
  frontend/apps/app/components/Chat/services/messageServiceClient.ts
  frontend/apps/app/components/Chat/types/chatTypes.ts
  frontend/apps/app/components/ChatInput/ChatInput.tsx
  frontend/apps/app/components/ChatInput/components/ModeToggleSwitch/ModeToggleSwitch.module.css
  frontend/apps/app/components/ChatInput/components/ModeToggleSwitch/ModeToggleSwitch.stories.tsx
  frontend/apps/app/components/ChatInput/components/ModeToggleSwitch/ModeToggleSwitch.tsx
  frontend/apps/app/components/ChatInput/components/ModeToggleSwitch/index.ts
  frontend/apps/app/components/ChatMessage/ChatMessage.tsx
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/validationNode.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/stateManager.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaAskAgent/agent.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaAskAgent/index.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaAskAgent/prompts.ts
  frontend/internal-packages/agent/src/langchain/agents/index.ts
  frontend/internal-packages/agent/src/langchain/index.ts
  frontend/internal-packages/agent/src/langchain/utils/types.ts
Labels: Review effort 4/5

#1977 🔧 ensure Biome format runs on save in VSCode
  .vscode/settings.json
  frontend/internal-packages/configs/biome.jsonc
  frontend/internal-packages/configs/package.json
  knip.jsonc
  pnpm-lock.yaml
Labels: Review effort 2/5

#1973 ✨(chat): Add auto-start AI response for initial user messages
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/constants/chatConstants.ts
  frontend/apps/app/components/Chat/hooks/useRealtimeMessages.ts
Labels: Review effort 3/5

#1988 ♻️ Refactor chat processing to remove streaming support and progress messages
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/components/Chat/constants/chatConstants.ts
  frontend/apps/app/components/Chat/services/aiMessageService.ts
  frontend/apps/app/components/Chat/services/messageHelpers.ts
  frontend/apps/app/components/Chat/types/chatTypes.ts
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  frontend/internal-packages/agent/src/chat/workflow/constants/progressMessages.ts
  frontend/internal-packages/agent/src/chat/workflow/index.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/answerGenerationNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalResponseNode.ts
  frontend/internal-packages/agent/src/chat/workflow/services/streamingWorkflow.ts
  frontend/internal-packages/agent/src/chat/workflow/services/workflow.ts
  frontend/internal-packages/agent/src/chat/workflow/services/workflowSteps.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/stateManager.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
Labels: Review effort 4/5

#1991 ♻️(agent): Implement Repository Pattern for framework independence
  frontend/apps/app/app/(app)/app/design_sessions/[id]/page.tsx
  frontend/apps/app/app/api/buildingSchemas/versions/route.ts
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/utils/agentSupabaseHelper.ts
  frontend/internal-packages/agent/package.json
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/answerGenerationNode.ts
  frontend/internal-packages/agent/src/chat/workflow/services/workflow.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/stateManager.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/db/server.ts
  frontend/internal-packages/agent/src/index.ts
  frontend/internal-packages/agent/src/repositories/factory.ts
  frontend/internal-packages/agent/src/repositories/index.ts
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/agent/src/repositories/types.ts
  frontend/internal-packages/agent/src/utils/createNewVersion.ts
  frontend/internal-packages/agent/src/utils/fetchSchemaData.ts
  frontend/internal-packages/agent/src/vectorstore/supabaseVectorStore.ts
  pnpm-lock.yaml
Labels: Review effort 4/5

#1992 ✨(agent): Implement server-side message saving with agent package integration
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/services/aiMessageService.ts
  frontend/apps/app/components/Chat/services/messageHelpers.ts
  frontend/apps/app/components/Chat/services/messageServiceClient.ts
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalResponseNode.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/stateManager.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/agent/src/repositories/types.ts
Labels: Review effort 4/5

#1994 🔧(turbo): Configure outputLogs errors-only to reduce AI agent token usage
  turbo.json
Labels: Review effort 2/5

#1996 ♻️(agent): Refactor agent workflow to simplify state management and remove redundant code
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  frontend/internal-packages/agent/src/chat/workflow/README.md
  frontend/internal-packages/agent/src/chat/workflow/nodes/answerGenerationNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/index.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/validationNode.ts
  frontend/internal-packages/agent/src/chat/workflow/services/workflow.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/stateManager.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/langchain/index.ts
  frontend/internal-packages/agent/src/langchain/utils/types.ts
Labels: Review effort 4/5

#1997 🔧 Fix Langfuse output logging in job environments by setting flushAt: 1
  frontend/internal-packages/agent/src/langchain/utils/telemetry.ts
Labels: Review effort 2/5

#1998 📚 docs: Update chat workflow README with new multi-agent architecture
  frontend/internal-packages/agent/src/chat/workflow/README.md
Labels: Review effort 2/5

#1999 ✨(messages): Add schema_version message support and fix PostgreSQL RPC function overloading
  frontend/apps/app/components/Chat/hooks/useRealtimeMessages.ts
  frontend/apps/app/components/Chat/services/messageServiceClient.ts
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalResponseNode.ts
  frontend/internal-packages/agent/src/chat/workflow/services/workflow.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/stateManager.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/agent/src/repositories/types.ts
  frontend/internal-packages/db/schema/schema.sql
  frontend/internal-packages/db/supabase/database.types.ts
  frontend/internal-packages/db/supabase/migrations/20250613162759_extend_messages_for_schema_versions.sql
  frontend/internal-packages/db/supabase/migrations/20250613164943_revert_to_message_content_param.sql
Labels: Review effort 4/5

#2014 ✨ feat(command palette): show table options and table preview
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.test.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.tsx
Labels: Review effort 3/5

#2021 fix: resolve parameter mismatch in `update_building_schema` RPC call
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/db/schema/schema.sql
  frontend/internal-packages/db/supabase/database.types.ts
  frontend/internal-packages/db/supabase/migrations/20250616032711_drop_old_update_building_schema.sql
Labels: Review effort 2/5

#2023 Revert "chore: temporarily update contact email due to infrastructure migration"
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT_ja.md
  SECURITY.md
Labels: Review effort 1/5

#2017 feat: Trigger.dev v4 migration with preview branch support
  .github/workflows/trigger_dev_preview.yml
  frontend/internal-packages/jobs/package.json
  frontend/internal-packages/jobs/src/index.ts
  frontend/internal-packages/jobs/src/trigger/chatJobs.ts
  frontend/internal-packages/jobs/src/trigger/jobs.ts
  frontend/internal-packages/jobs/trigger.config.ts
  package.json
  pnpm-lock.yaml
Labels: Review effort 4/5

#2031 ✨ feat: add DeepModelingToggle component
  .gitignore
  frontend/apps/app/features/sessions/components/SessionForm/GitHubSessionFormPresenter/GitHubSessionFormPresenter.module.css
  frontend/apps/app/features/sessions/components/SessionForm/GitHubSessionFormPresenter/GitHubSessionFormPresenter.tsx
  frontend/packages/ui/src/components/DeepModelingToggle/DeepModelingToggle.module.css
  frontend/packages/ui/src/components/DeepModelingToggle/DeepModelingToggle.stories.tsx
  frontend/packages/ui/src/components/DeepModelingToggle/DeepModelingToggle.tsx
  frontend/packages/ui/src/components/DeepModelingToggle/index.ts
  frontend/packages/ui/src/components/index.ts
  frontend/packages/ui/src/icons/index.ts
Labels: Review effort 3/5

#2032 ⚙️(renovate): Add dev-tools automerge group
  renovate.json
Labels: Review effort 2/5

#2034 ✨️ feat: Add MicButton component and refactoring DeepModelingToggle's location
  frontend/apps/app/features/sessions/components/SessionForm/DeepModelingToggle/DeepModelingToggle.module.css
  frontend/apps/app/features/sessions/components/SessionForm/DeepModelingToggle/DeepModelingToggle.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/DeepModelingToggle/DeepModelingToggle.tsx
  frontend/apps/app/features/sessions/components/SessionForm/DeepModelingToggle/index.ts
  frontend/apps/app/features/sessions/components/SessionForm/GitHubSessionFormPresenter/GitHubSessionFormPresenter.tsx
  frontend/apps/app/features/sessions/components/SessionForm/MicButton/MicButton.module.css
  frontend/apps/app/features/sessions/components/SessionForm/MicButton/MicButton.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/MicButton/MicButton.tsx
  frontend/apps/app/features/sessions/components/SessionForm/MicButton/index.ts
  frontend/packages/ui/src/components/DeepModelingToggle/DeepModelingToggle.stories.tsx
  frontend/packages/ui/src/components/DeepModelingToggle/DeepModelingToggle.tsx
  frontend/packages/ui/src/components/index.ts
  frontend/packages/ui/src/icons/index.ts
Labels: Review effort 3/5

#2038 🔥 remove staging branch related configurations
  .github/workflows/trigger_dev_staging.yml
  frontend/internal-packages/db/supabase/config.toml
Labels: Review effort 1/5

#2035 ✨(chat): implement VersionMessage component and integrate with chat system
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/VersionMessage/VersionMessage.module.css
  frontend/apps/app/components/Chat/VersionMessage/VersionMessage.tsx
  frontend/apps/app/components/Chat/VersionMessage/index.ts
  frontend/apps/app/components/Chat/hooks/useRealtimeMessages.ts
  frontend/apps/app/components/Chat/services/messageServiceClient.ts
  frontend/apps/app/components/Chat/types/chatTypes.ts
  frontend/apps/app/components/ChatMessage/ChatMessage.tsx
  frontend/internal-packages/db/src/index.ts
Labels: Review effort 4/5

#2018 Upgrade/usestate hook for perv state
  frontend/apps/app/components/Chat/ProcessIndicator/ProcessIndicator.tsx
  frontend/apps/app/components/PGlitePage/QueryResultBox.tsx
  frontend/apps/docs/components/CopyButton/CopyButton.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/CollapsibleHeader/CollapsibleHeader.tsx
Labels: Review effort 2/5

#2041 🔧 feat: implement workflow node tracking for Trigger.dev
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  frontend/internal-packages/agent/src/chat/workflow/index.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/analyzeRequirementsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalizeArtifactsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/reviewDeliverablesNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/validateSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/index.ts
  frontend/internal-packages/agent/src/utils/nodeLogger.ts
  frontend/internal-packages/jobs/src/trigger/chatJobs.ts
Labels: Review effort 2/5

#2050 🐛 fix: resolve duplicate user messages and remove dbId field
  frontend/apps/app/components/Chat/hooks/useRealtimeMessages.ts
  frontend/apps/app/components/Chat/types/chatTypes.ts
Labels: Review effort 3/5

#2051 ♻️ refact(TableNode): set `overflow: hidden` on TableNode columns component directly instead of CommandPalette component
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableColumnList/TableColumn/TableColumn.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.tsx
Labels: Review effort 2/5

#2052 🐛 fix(TableDetail): hide `DrawerContent` component when table is not set when table is not selected
  .changeset/polite-forks-repair.md
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/TableDetailDrawer/TableDetailDrawer.tsx
Labels: Review effort 2/5

#2059 ♻️ refactor(agent): consolidate chat history formatting into WorkflowState
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalizeArtifactsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
Labels: Review effort 3/5

#2043 ✨(database): Rename messages table to timeline_items for flexible chat architecture
  frontend/apps/app/app/(app)/app/design_sessions/[id]/page.tsx
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/hooks/useRealtimeMessages.ts
  frontend/apps/app/components/Chat/hooks/useRealtimeTimelineItems.ts
  frontend/apps/app/components/Chat/services/aiMessageService.ts
  frontend/apps/app/components/Chat/services/index.ts
  frontend/apps/app/components/Chat/services/messageHelpers.ts
  frontend/apps/app/components/Chat/services/timelineItemHelpers.ts
  frontend/apps/app/components/Chat/services/timelineItemServiceClient.ts
  frontend/apps/app/components/Chat/types/chatTypes.ts
  frontend/apps/app/components/ChatMessage/index.ts
  frontend/apps/app/components/TimelineItem/TimelineItem.module.css
  frontend/apps/app/components/TimelineItem/TimelineItem.tsx
  frontend/apps/app/components/TimelineItem/index.ts
  frontend/apps/app/features/sessions/actions/createSession.ts
  frontend/internal-packages/agent/src/chat/chatProcessor.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalizeArtifactsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/agent/src/repositories/types.ts
  frontend/internal-packages/db/schema/schema.sql
  frontend/internal-packages/db/src/types/supabase-overrides/index.ts
  frontend/internal-packages/db/src/types/supabase-overrides/timeline_items.ts
  frontend/internal-packages/db/supabase/database.types.ts
  frontend/internal-packages/db/supabase/migrations/20250617150551_rename_messages_to_timeline_items.sql
Labels: Review effort 4/5

#2068 🔧 fix(agent): fix createVersion validation error by updating response schema
  frontend/internal-packages/agent/src/repositories/supabase.ts
Labels: Review effort 2/5

#2066 🐛 Fix JSON parsing errors and workflow infinite loops in chat agent
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/prompts.ts
Labels: Review effort 2/5

#2070 🔧: Upgrade Biome to v2 with configuration updates
  frontend/apps/app/app/global-error.tsx
  frontend/apps/app/components/Chat/ProcessIndicator/ProcessIndicator.module.css
  frontend/apps/app/components/ChatInput/ChatInput.module.css
  frontend/apps/app/components/ChatInput/components/MentionSuggestor/MentionSuggestor.tsx
  frontend/apps/app/components/InvitationPage/components/InvitationCard/InvitationCard.module.css
  frontend/apps/app/components/LoginPage/LoginPage.module.css
  frontend/apps/app/components/LoginPage/services/loginByGithub.ts
  frontend/apps/app/components/OrganizationMembersPage/components/InviteMemberModal/actions/sendInvitationEmail.ts
  frontend/apps/app/components/PGlitePage/DDLInputSection.module.css
  frontend/apps/app/components/PGlitePage/DMLInputSection.module.css
  frontend/apps/app/components/PGlitePage/PGlitePlayground.module.css
  frontend/apps/app/components/PGlitePage/PGlitePlayground.tsx
  frontend/apps/app/components/ProjectsPage/components/ProjectsListView/components/ProjectItem/ProjectItem.module.css
  frontend/apps/app/components/TimelineItem/TimelineItem.module.css
  frontend/apps/app/features/sessions/components/SessionForm/DeepModelingToggle/DeepModelingToggle.module.css
  frontend/apps/app/libs/gtm/GtagScript.tsx
  frontend/apps/app/libs/routes/routeDefinitions.ts
  frontend/apps/app/package.json
  frontend/apps/docs/app/global-error.tsx
  frontend/apps/docs/biome.jsonc
  frontend/apps/docs/components/Banner/Banner.tsx
  frontend/apps/docs/components/Heading/Heading.tsx
  frontend/apps/docs/lib/gtm/GtagScript.tsx
  frontend/apps/docs/package.json
  frontend/apps/docs/postcss.config.js
  frontend/internal-packages/agent/package.json
  frontend/internal-packages/configs/biome.jsonc
  frontend/internal-packages/configs/package.json
  frontend/internal-packages/db/package.json
  frontend/internal-packages/e2e/biome.jsonc
  frontend/internal-packages/e2e/package.json
  frontend/internal-packages/figma-to-css-variables/package.json
  frontend/internal-packages/github/package.json
  frontend/internal-packages/jobs/package.json
  frontend/internal-packages/mcp-server/package.json
  frontend/packages/cli/biome.jsonc
  frontend/packages/cli/package.json
  frontend/packages/db-structure/biome.jsonc
  frontend/packages/db-structure/package.json
  frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
  frontend/packages/db-structure/src/parser/tbls/schema.generated.test.ts
  frontend/packages/erd-core/package.json
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableGroupNode/TableGroupNode.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableNode.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/hooks/useQueryParamsChanged.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/DesktopToolbar.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/Toolbar/MobileToolbar/MobileToolbar.module.css
  frontend/packages/pglite-server/biome.jsonc
  frontend/packages/pglite-server/package.json
  frontend/packages/ui/package.json
  frontend/packages/ui/src/components/Button/Button.module.css
  frontend/packages/ui/src/components/Modal/Modal.tsx
  pnpm-lock.yaml
Labels: Review effort 2/5

#2060 ✨(storybook): Add Inter and Montserrat fonts to match main app
  frontend/internal-packages/storybook/.storybook/preview-head.html
Labels: Review effort 2/5

#2091 🐛(erd-core): fix CSS specificity for RelationshipEdge hovered state
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/RelationshipEdge/RelationshipEdge.module.css
Labels: Review effort 1/5

#2084 ✨(db-structure): Add PostgreSQL schema deparser for DDL generation
  frontend/packages/db-structure/src/deparser/postgresql/index.ts
  frontend/packages/db-structure/src/deparser/postgresql/schemaDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/schemaDeparser.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
  frontend/packages/db-structure/src/deparser/type.ts
  frontend/packages/db-structure/src/index.ts
Labels: Review effort 3/5, Possible security concern

#2093 🧪(e2e): improve test reliability by disabling Vercel toolbar for automation
  frontend/internal-packages/e2e/tests/vrt/vrt.test.ts
  frontend/internal-packages/e2e/tests/vrt/vrt.test.ts-snapshots/top-1-chromium-linux.png
Labels: Review effort 2/5

#2098 ✨ feat(command palette): support table display in ERD on option selection
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.test.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
Labels: Review effort 3/5

#2097 ♻️ refactor SessionDetailPage to use server actions for data fetching and introduce SessionDetailPageClient component for client-side rendering
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.tsx
  frontend/apps/app/components/SessionDetailPage/SessionDetailPageClient.tsx
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeBuildlingSchema.ts
  frontend/apps/app/components/SessionDetailPage/services/buildingSchema/client/getBuldingSchema.ts
  frontend/apps/app/components/SessionDetailPage/services/buildingSchema/fetchBuildingSchema.ts
  frontend/apps/app/components/SessionDetailPage/services/buildingSchema/server/getBuildingSchema.ts
  frontend/apps/app/components/SessionDetailPage/services/buildingSchemaServiceClient.ts
  frontend/apps/app/components/SessionDetailPage/services/latestVersion/client/getLatestVersion.ts
  frontend/apps/app/components/SessionDetailPage/services/latestVersion/fetchLatestVersion.ts
  frontend/apps/app/components/SessionDetailPage/services/latestVersion/server/getLatestVersion.ts
  frontend/apps/app/components/SessionDetailPage/types.ts
Labels: Review effort 3/5

#2075 refactor: enhance applyPatchOperations for better error handling and path management
  frontend/packages/db-structure/src/operation/__tests__/applyPatchOperations.test.ts
  frontend/packages/db-structure/src/operation/applyPatchOperations.ts
Labels: Review effort 3/5

#2081 📝(docs): Add code refactoring guidelines to CLAUDE.md
  CLAUDE.md
Labels: Review effort 1/5

#2101 ✨ Implement version management with VersionDropdown and enhance schema handling
  frontend/apps/app/components/SessionDetailPage/SessionDetailPageClient.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/Output.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/Header.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/VersionDropdown.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/VersionDropdown/VersionDropdown.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/VersionDropdown/hooks/useRealtimeVersions.ts
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/VersionDropdown/index.ts
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/VersionDropdown/services/getSchemaVersions.ts
  frontend/apps/app/components/SessionDetailPage/services/buildCurrentSchema.ts
  frontend/apps/app/components/SessionDetailPage/services/buildingSchema/fetchBuildingSchema.ts
  frontend/apps/app/components/SessionDetailPage/types.ts
Labels: Review effort 4/5

#2107 feat: implement ADD COLUMN operation support
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
  frontend/packages/db-structure/src/deparser/type.ts
  frontend/packages/db-structure/src/operation/index.ts
  frontend/packages/db-structure/src/operation/pathValidators.ts
  frontend/packages/db-structure/src/operation/schema/column.ts
  frontend/packages/db-structure/src/operation/schema/index.ts
  frontend/packages/db-structure/src/operation/schema/table.ts
Labels: Review effort 3/5

#2109 feat: implement REMOVE COLUMN operation support
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
  frontend/packages/db-structure/src/operation/schema/column.ts
Labels: Review effort 2/5, Possible security concern

#2110 refactor: extract shared path schemas to reduce duplication
  frontend/packages/db-structure/src/operation/schema/column.ts
  frontend/packages/db-structure/src/operation/schema/table.ts
Labels: Review effort 2/5

#2133 ♻️ Migrating from lz-string to pako
  frontend/internal-packages/e2e/tests/e2e/navigation.test.ts
  frontend/packages/erd-core/package.json
  frontend/packages/erd-core/src/stores/userEditing/Provider.tsx
  frontend/packages/erd-core/src/utils/compressToEncodedURIComponent.ts
  frontend/packages/erd-core/src/utils/compressionString.test.ts
  frontend/packages/erd-core/src/utils/decompressFromEncodedURIComponent.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#2138 ✨ feat: add unified ActionButton component for session forms
  frontend/apps/app/features/sessions/components/SessionForm/ActionButton/ActionButton.module.css
  frontend/apps/app/features/sessions/components/SessionForm/ActionButton/ActionButton.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/ActionButton/ActionButton.tsx
  frontend/apps/app/features/sessions/components/SessionForm/ActionButton/index.ts
  frontend/apps/app/features/sessions/components/SessionForm/GitHubSessionFormPresenter/GitHubSessionFormPresenter.tsx
  frontend/apps/app/features/sessions/components/SessionForm/SessionFormActions/SessionFormActions.module.css
  frontend/apps/app/features/sessions/components/SessionForm/SessionFormActions/SessionFormActions.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/SessionFormActions/SessionFormActions.tsx
  frontend/apps/app/features/sessions/components/SessionForm/URLSessionFormPresenter/URLSessionFormPresenter.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/UploadSessionFormPresenter.tsx
  frontend/packages/ui/src/icons/index.ts
Labels: Review effort 3/5

#2135 🐛(db-structure): fix operations schema v.custom() validation for LangChain structured outputs
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/agent.ts
  frontend/packages/db-structure/src/operation/pathValidators.ts
  frontend/packages/db-structure/src/operation/schema/column.ts
  frontend/packages/db-structure/src/operation/schema/index-operations.ts
  frontend/packages/db-structure/src/operation/schema/table.ts
Labels: Review effort 2/5

#2134 ♻️ refactor: implement structured output for PMAgent
  frontend/internal-packages/agent/src/langchain/agents/pmAgent/agent.ts
Labels: Review effort 3/5

#2149 refactor: use PATH_PATTERNS constants for regex patterns
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.ts
Labels: Review effort 2/5

#2151 feat: implement RENAME TABLE operation support
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
  frontend/packages/db-structure/src/operation/schema/table.ts
Labels: Review effort 2/5

#2165 :bug: Resolve ESLint module error by renaming config file
  .clinerules/general.md
  frontend/packages/pglite-server/eslint.config.mjs
Labels: Review effort 1/5

#2154 schema-bench package(part 1: add the package and `nameSimilarity` function)
  frontend/internal-packages/schema-bench/.gitignore
  frontend/internal-packages/schema-bench/README.md
  frontend/internal-packages/schema-bench/biome.jsonc
  frontend/internal-packages/schema-bench/eslint.config.mjs
  frontend/internal-packages/schema-bench/package.json
  frontend/internal-packages/schema-bench/src/index.ts
  frontend/internal-packages/schema-bench/src/nameSimilarity/index.ts
  frontend/internal-packages/schema-bench/src/nameSimilarity/nameSimilarity.test.ts
  frontend/internal-packages/schema-bench/src/nameSimilarity/nameSimilarity.ts
  frontend/internal-packages/schema-bench/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#2163 🧪 test(command palette): create E2E test of CommandPalette component
  frontend/internal-packages/e2e/tests/e2e/commandPalette.test.ts
Labels: Review effort 2/5

#2155 feat: implement ADD and REMOVE CONSTRAINT operation support
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
  frontend/packages/db-structure/src/operation/schema/constraint.ts
  frontend/packages/db-structure/src/operation/schema/index.ts
Labels: Review effort 3/5, Possible security concern

#2170 fix: remove unused progressMessages state from Chat component
  frontend/apps/app/components/Chat/AgentMessage/AgentMessage.tsx
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/services/aiMessageService.ts
  frontend/apps/app/components/TimelineItem/TimelineItem.tsx
Labels: Review effort 2/5

#2177 add: supported database doc files
  frontend/apps/docs/content/docs/parser/supported-formats/clickhouse.mdx
  frontend/apps/docs/content/docs/parser/supported-formats/cloudspanner.mdx
  frontend/apps/docs/content/docs/parser/supported-formats/dynamodb.mdx
  frontend/apps/docs/content/docs/parser/supported-formats/mariadb.mdx
  frontend/apps/docs/content/docs/parser/supported-formats/mongodb.mdx
  frontend/apps/docs/content/docs/parser/supported-formats/redshift.mdx
  frontend/apps/docs/content/docs/parser/supported-formats/snowflake.mdx
Labels: Review effort 1/5

#2171 ✅(db-structure): Add parser verification to PostgreSQL deparser tests
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/schemaDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/testUtils.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
Labels: Review effort 2/5

#2161 schema-bench package part3: implement schema evaluation logic `evaluate` function with scoring metrics
  frontend/internal-packages/schema-bench/README.md
  frontend/internal-packages/schema-bench/package.json
  frontend/internal-packages/schema-bench/src/evaluate/evaluate.test.ts
  frontend/internal-packages/schema-bench/src/evaluate/evaluate.ts
  frontend/internal-packages/schema-bench/src/evaluate/index.ts
  frontend/internal-packages/schema-bench/src/index.ts
  pnpm-lock.yaml
Labels: Review effort 4/5

#2190 ♻️ refactor: Rename timelineItems to realtimeTimelineItems for clarity
  frontend/apps/app/components/Chat/Chat.tsx
Labels: Review effort 1/5

#2180 ✨ feat: Add attachment preview with drag & drop support
  frontend/apps/app/features/sessions/components/SessionForm/AttachButton/AttachButton.tsx
  frontend/apps/app/features/sessions/components/SessionForm/AttachmentPreview/AttachmentPreview.module.css
  frontend/apps/app/features/sessions/components/SessionForm/AttachmentPreview/AttachmentPreview.tsx
  frontend/apps/app/features/sessions/components/SessionForm/AttachmentPreview/index.ts
  frontend/apps/app/features/sessions/components/SessionForm/GitHubSessionFormPresenter/GitHubSessionFormPresenter.module.css
  frontend/apps/app/features/sessions/components/SessionForm/GitHubSessionFormPresenter/GitHubSessionFormPresenter.tsx
  frontend/apps/app/features/sessions/components/SessionForm/SessionFormActions/SessionFormActions.tsx
  frontend/packages/ui/src/icons/index.ts
Labels: Review effort 3/5

#2193 ♻️(db-structure): Remove deprecated relationships field from schema
  frontend/apps/app/app/erd/p/[...slug]/page.tsx
  frontend/apps/app/components/ChatInput/ChatInput.stories.tsx
  frontend/apps/app/components/ChatInput/components/MentionSuggestor/MentionSuggestor.stories.tsx
  frontend/apps/app/components/ChatInput/components/MentionSuggestor/utils/getAllMentionCandidates.ts
  frontend/apps/app/components/SchemaPage/SchemaPage.tsx
  frontend/apps/app/components/SessionDetailPage/services/buildCurrentSchema.ts
  frontend/apps/app/features/sessions/actions/createSession.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/schema-bench/README.md
  frontend/internal-packages/schema-bench/package.json
  frontend/internal-packages/schema-bench/src/evaluate/evaluate.test.ts
  frontend/internal-packages/schema-bench/src/evaluate/evaluate.ts
  frontend/internal-packages/storybook/vercel.json
  frontend/packages/cli/src/App.tsx
  frontend/packages/db-structure/src/deparser/postgresql/schemaDeparser.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnCheckDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnCommentDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnDefaultDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnNameDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnNotNullDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnPrimaryDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnUniqueDiffItem.test.ts
  frontend/packages/db-structure/src/diff/tables/__tests__/buildTableCommentDiffItem.test.ts
  frontend/packages/db-structure/src/diff/tables/__tests__/buildTableDiffItem.test.ts
  frontend/packages/db-structure/src/diff/tables/__tests__/buildTableNameDiffItem.test.ts
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
  frontend/packages/db-structure/src/parser/schemarb/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/mergeSchemas.ts
  frontend/packages/db-structure/src/parser/tbls/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/parser.ts
  frontend/packages/db-structure/src/parser/utils/handleOneToOneRelationships.ts
  frontend/packages/db-structure/src/parser/utils/index.ts
  frontend/packages/db-structure/src/schema/factories.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db-structure/src/schema/mergeSchema.test.ts
  frontend/packages/db-structure/src/schema/mergeSchema.ts
  frontend/packages/db-structure/src/schema/schema.ts
  frontend/packages/db-structure/src/utils/constraintsToRelationships.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/extractSchemaForTable.test.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/extractSchemaForTable.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.test.tsx
  frontend/packages/erd-core/src/stores/schema/SchemaProvider.tsx
  pnpm-lock.yaml
  turbo.json
Labels: Review effort 4/5

#2218 fix: remove permission-actions from release workflow
  .github/workflows/release.yml
Labels: Review effort 1/5

#2222 fix: remove relationships references from agent prompts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/prompts.ts
Labels: Review effort 2/5

#2205 ✨(db-structure): Remove column.primary duplication with constraints
  frontend/apps/app/components/ChatInput/components/MentionSuggestor/utils/getAllMentionCandidates.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/utils/convertSchemaToText.ts
  frontend/internal-packages/schema-bench/src/evaluate/evaluate.ts
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/schemaDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
  frontend/packages/db-structure/src/diff/buildSchemaDiff.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnCheckDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnCommentDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnDefaultDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnNameDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnNotNullDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/__tests__/buildColumnPrimaryDiffItem.test.ts
  frontend/packages/db-structure/src/diff/columns/buildColumnPrimaryDiffItem.ts
  frontend/packages/db-structure/src/diff/types.ts
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/operation/constants.ts
  frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
  frontend/packages/db-structure/src/parser/schemarb/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/parser.ts
  frontend/packages/db-structure/src/schema/factories.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db-structure/src/schema/mergeSchema.test.ts
  frontend/packages/db-structure/src/schema/schema.ts
  frontend/packages/db-structure/src/utils/constraintsToRelationships.test.ts
  frontend/packages/db-structure/src/utils/isPrimaryKey.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableColumnList/TableColumn/TableColumn.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableColumnList/TableColumnList.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Columns/Columns.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Columns/ColumnsItem/ColumnsItem.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/TableDetail.tsx
Labels: Review effort 4/5

#2225 feat: implement complete PostgreSQL schema deparser with indexes and constraints
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.ts
  frontend/packages/db-structure/src/deparser/postgresql/schemaDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/schemaDeparser.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
Labels: Review effort 4/5

#2164 🐛 fix: fix hydration error with Next.js NuqsAdapter
  .changeset/all-hoops-refuse.md
  frontend/apps/app/app/erd/p/[...slug]/erdViewer.tsx
  frontend/apps/app/components/SchemaPage/components/ERDEditor/ERDEditor.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/ERD/ERD.tsx
  frontend/packages/cli/src/App.tsx
  frontend/packages/erd-core/package.json
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
  frontend/packages/erd-core/src/nextjs/index.ts
  frontend/packages/erd-core/src/nextjs/providers/ERDRendererProvider.tsx
  frontend/packages/erd-core/src/nextjs/providers/index.ts
  frontend/packages/erd-core/src/providers/ERDRendererProvider.tsx
  frontend/packages/erd-core/src/providers/index.ts
Labels: Review effort 3/5

#2241 🔧(scripts): Simplify test script naming for AI agents
  .github/workflows/frontend-ci.yml
  CLAUDE.md
  package.json
  turbo.json
Labels: Review effort 2/5

#2237 refactor: centralize message saving in workflow to prevent duplicates
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/hooks/useAutoStartExecuted.ts
  frontend/apps/app/features/sessions/actions/createSession.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/index.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/saveUserMessageNode.ts
  frontend/internal-packages/agent/src/chat/workflow/services/workflow.ts
Labels: Review effort 4/5

#2261 ✅ Add comprehensive tests for schema-bench workspace functionality
  frontend/internal-packages/schema-bench/src/workspace/evaluation/evaluation.test.ts
  frontend/internal-packages/schema-bench/src/workspace/setup/setup.test.ts
Labels: Review effort 3/5

#2209 ✨ feat: implement styling UploadSessionFormPresenter component
  frontend/apps/app/components/FormatIcon/icons/SchemaRbIcon.tsx
  frontend/apps/app/components/SchemaPage/components/ERDEditor/ERDEditor.tsx
  frontend/apps/app/features/sessions/components/SessionForm/ActionButton/ActionButton.tsx
  frontend/apps/app/features/sessions/components/SessionForm/AttachmentsContainer/AttachmentsContainer.module.css
  frontend/apps/app/features/sessions/components/SessionForm/AttachmentsContainer/AttachmentsContainer.tsx
  frontend/apps/app/features/sessions/components/SessionForm/AttachmentsContainer/index.ts
  frontend/apps/app/features/sessions/components/SessionForm/FormatSelectDropdown/FormatSelectDropdown.module.css
  frontend/apps/app/features/sessions/components/SessionForm/FormatSelectDropdown/FormatSelectDropdown.tsx
  frontend/apps/app/features/sessions/components/SessionForm/FormatSelectDropdown/index.ts
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/DropZone.module.css
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/DropZone.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/FileIcon.module.css
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/FileIcon.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/SchemaFileSection.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/UploadSessionFormPresenter.module.css
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/UploadSessionFormPresenter.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/UploadSessionFormPresenter.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/utils/fileValidation.ts
  frontend/apps/app/features/sessions/components/SessionForm/hooks/useFileAttachments.ts
  frontend/apps/app/features/sessions/components/SessionForm/hooks/useFileDragAndDrop.ts
  frontend/apps/app/package.json
  frontend/apps/app/types/images.d.ts
  frontend/internal-packages/storybook/.storybook/main.ts
  frontend/packages/ui/src/icons/index.ts
  pnpm-lock.yaml
Labels: Review effort 4/5

#2210 ✨ feat(command palette): create CommandPalette trigger button and prepare to implement on the AppBar
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.test.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPaletteProvider/Provider.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPaletteProvider/context.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPaletteProvider/hooks.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPaletteProvider/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPaletteTriggerButton/CommandPaletteTriggerButton.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPaletteTriggerButton/CommandPaletteTriggerButton.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPaletteTriggerButton/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
Labels: Review effort 3/5

#2278 ✨ feat(command palette): allow ESC button to close the dialog
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.test.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.tsx
Labels: Review effort 2/5
