Repository liam-hq/liam, pull requests merged in 2025-03, with the labels that each got.

#749 🐛 Add sticky position to CollapsibleHeader
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/CollapsibleHeader/CollapsibleHeader.module.css
Labels: Review effort 1/5

#798 🐛 integrate user editing state into related tables component
  .changeset/empty-baboons-doubt.md
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/RelatedTables/RelatedTables.tsx
Labels: Review effort 1/5

#797 🐛 Display Related Tables for Nodes without Relations
  .changeset/violet-dolphins-reflect.md
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/TableDetail.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/extractDBStructureForTable.test.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/extractDBStructureForTable.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/hooks/useInitialAutoLayout.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/utils/hasNonRelatedChildNodes.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/utils/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/utils/updateNodesHiddenState.ts
  frontend/packages/erd-core/src/features/erd/constants.ts
  frontend/packages/erd-core/src/features/erd/utils/convertDBStructureToNodes.ts
Labels: Review effort 3/5

#800 ✨ Add migration web as minimum scaffolds
  docs/packages-license.md
  frontend/apps/migration-web/.env.template
  frontend/apps/migration-web/.gitignore
  frontend/apps/migration-web/app/api/review/route.ts
  frontend/apps/migration-web/app/favicon.ico
  frontend/apps/migration-web/app/globals.css
  frontend/apps/migration-web/app/layout.tsx
  frontend/apps/migration-web/app/page.module.css
  frontend/apps/migration-web/app/page.tsx
  frontend/apps/migration-web/app/review/page.module.css
  frontend/apps/migration-web/app/review/page.tsx
  frontend/apps/migration-web/biome.jsonc
  frontend/apps/migration-web/components/ReviewWindow.module.css
  frontend/apps/migration-web/components/ReviewWindow.tsx
  frontend/apps/migration-web/next.config.ts
  frontend/apps/migration-web/package.json
  frontend/apps/migration-web/public/.keep
  frontend/apps/migration-web/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#801 🔧 Add Supabase for migration web
  frontend/apps/migration-web/package.json
  frontend/apps/migration-web/supabase/.gitignore
  frontend/apps/migration-web/supabase/config.toml
  frontend/apps/migration-web/supabase/migrations/20250303091039_remote_schema.sql
  pnpm-lock.yaml
Labels: Review effort 2/5

#802 🔧 fix changeset version type
  .changeset/afraid-forks-report.md
Labels: Review effort 1/5

#804 ✨ Add Langfuse integration for migration web tracing
  frontend/apps/migration-web/.env.template
  frontend/apps/migration-web/.gitignore
  frontend/apps/migration-web/app/api/review/route.ts
  frontend/apps/migration-web/lib/index.ts
  frontend/apps/migration-web/lib/langfuse.ts
  frontend/apps/migration-web/package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#803 🔧 Increase Playwright CI retry attempts to 5
  frontend/packages/e2e/playwright.config.ts
Labels: Review effort 1/5

#805 ✨ Add knowledge retrieval by using RAG
  config/dependency_decisions.yml
  frontend/apps/migration-web/.env.template
  frontend/apps/migration-web/app/api/retrieve/route.ts
  frontend/apps/migration-web/app/api/vectorize/route.ts
  frontend/apps/migration-web/app/globals.css
  frontend/apps/migration-web/app/knowledge_retrieval/page.module.css
  frontend/apps/migration-web/app/knowledge_retrieval/page.tsx
  frontend/apps/migration-web/app/layout.tsx
  frontend/apps/migration-web/app/vectorize/page.module.css
  frontend/apps/migration-web/app/vectorize/page.tsx
  frontend/apps/migration-web/components/Header.module.css
  frontend/apps/migration-web/components/Header.tsx
  frontend/apps/migration-web/components/KnowledgeRetrievalWindow.module.css
  frontend/apps/migration-web/components/KnowledgeRetrievalWindow.tsx
  frontend/apps/migration-web/components/TextVectorizer.module.css
  frontend/apps/migration-web/components/TextVectorizer.tsx
  frontend/apps/migration-web/components/UrlVectorizer.module.css
  frontend/apps/migration-web/components/UrlVectorizer.tsx
  frontend/apps/migration-web/lib/index.ts
  frontend/apps/migration-web/lib/supabase.ts
  frontend/apps/migration-web/lib/vectorStore.ts
  frontend/apps/migration-web/lib/vectorization.ts
  frontend/apps/migration-web/package.json
  frontend/apps/migration-web/supabase/migrations/20250304050615_remote_schema.sql
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Review effort 4/5

#799 📝 docs: add ADR for using ``libpg-query`` for PostgreSQL SQL parsing
  docs/adr/20241128-use-libpg-query-for-postgreSQL-SQL-parsing.md
Labels: Review effort 1/5

#806 ✨ Allow sidebar width adjustment & cleanup toggle logic
  .changeset/little-poems-pump.md
  frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx
  frontend/apps/erd-web/app/erd/p/[...slug]/page.tsx
  frontend/packages/cli/src/App.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/AppBar/MenuButton/MenuButton.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/LeftPane/LeftPane.tsx
  frontend/packages/ui/package.json
  frontend/packages/ui/src/components/Resizable/Resizable.module.css
  frontend/packages/ui/src/components/Resizable/Resizable.tsx
  frontend/packages/ui/src/components/Resizable/index.ts
  frontend/packages/ui/src/components/Sidebar/Sidebar.module.css
  frontend/packages/ui/src/components/Sidebar/Sidebar.tsx
  frontend/packages/ui/src/components/index.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#808 ✨ Enhance database schema review with RAG context retrieval
  frontend/apps/migration-web/app/api/review/route.ts
  frontend/apps/migration-web/lib/types/review.ts
Labels: Review effort 2/5

#816 Fix broken links in issue templates
  .github/ISSUE_TEMPLATE/1_bug_report.yml
  .github/ISSUE_TEMPLATE/2_doc_issue.yml
Labels: Review effort 1/5

#818 🔧 fix: pnpm-lock
  docs/packages-license.md
  pnpm-lock.yaml
Labels: Review effort 1/5

#814 ✨ Add Prisma schema
  frontend/apps/migration-web/.gitignore
  frontend/apps/migration-web/package.json
  frontend/apps/migration-web/prisma/migrations/20250306063813_first_prisma_migration/migration.sql
  frontend/apps/migration-web/prisma/migrations/migration_lock.toml
  frontend/apps/migration-web/prisma/schema.prisma
Labels: Review effort 3/5

#820 Fix/truncated button change size on hover 794
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx
  frontend/packages/ui/src/components/Sidebar/Sidebar.module.css
  frontend/packages/ui/src/components/Sidebar/Sidebar.tsx
Labels: Review effort 2/5

#825 💄Fixed an issue where the length of the TableNameButton text would change when hovering
  .changeset/eight-parrots-relate.md
  frontend/packages/ui/src/components/Sidebar/Sidebar.module.css
Labels: Review effort 1/5

#828 setup supabase
  docs/packages-license.md
  frontend/packages/supabase/package.json
  frontend/packages/supabase/src/index.ts
  frontend/packages/supabase/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#826 🔧 Add initial memory bank documentation for Liam Migration project
  .gitignore
  memory-bank/productContext.md
  memory-bank/progress.md
  memory-bank/projectbrief.md
  memory-bank/systemPatterns.md
  memory-bank/techContext.md
Labels: Review effort 2/5

#829 🚀 feat(supabase): Add Prisma ORM and initial Project model
  docs/packages-license.md
  frontend/packages/supabase/package.json
  frontend/packages/supabase/prisma/migrations/20250310052227_add_project/migration.sql
  frontend/packages/supabase/prisma/migrations/migration_lock.toml
  frontend/packages/supabase/prisma/schema.prisma
  frontend/packages/supabase/supabase/.gitignore
  frontend/packages/supabase/supabase/config.toml
  pnpm-lock.yaml
Labels: Review effort 2/5

#833 🔧 Migrate to Prisma for All Database Operations & Rename Package to @liam-hq/db
  frontend/packages/db/.env.template
  frontend/packages/db/.gitignore
  frontend/packages/db/package.json
  frontend/packages/db/prisma/migrations/20250310052227_add_project/migration.sql
  frontend/packages/db/prisma/migrations/migration_lock.toml
  frontend/packages/db/prisma/schema.prisma
  frontend/packages/db/src/index.ts
  frontend/packages/db/supabase/.gitignore
  frontend/packages/db/supabase/config.toml
  frontend/packages/db/tsconfig.json
  frontend/packages/supabase/src/index.ts
  frontend/packages/supabase/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#831 ✨ Add GitHub webhook integration for pull request events
  docs/packages-license.md
  frontend/apps/erd-web/app/api/webhook/github/route.ts
  frontend/apps/erd-web/libs/github/api.ts
  frontend/apps/erd-web/libs/github/config.ts
  frontend/apps/erd-web/package.json
  frontend/apps/erd-web/types/github.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#834 🐛 Disable Prisma client import and initialization
  frontend/packages/db/src/index.ts
Labels: Review effort 1/5

#819 🔧 fix: update vite and fumadocs-mdx to latest versions
  .changeset/blue-maps-vanish.md
  docs/packages-license.md
  frontend/apps/docs/app/global.css
  frontend/apps/docs/package.json
  frontend/apps/docs/postcss.config.js
  frontend/apps/docs/tailwind.config.js
  frontend/apps/erd-web/next.config.ts
  frontend/packages/cli/package.json
  frontend/packages/db-structure/package.json
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/erd-core/package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#830 🚀 feat(migration): Add feature flag for migration page
  docs/packages-license.md
  frontend/apps/erd-web/.env.development
  frontend/apps/erd-web/app/.well-known/vercel/flags/route.ts
  frontend/apps/erd-web/app/app/page.tsx
  frontend/apps/erd-web/libs/flags/index.ts
  frontend/apps/erd-web/libs/index.ts
  frontend/apps/erd-web/package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#835 :rocket: setup auth basic
  docs/packages-license.md
  frontend/apps/erd-web/.env.development
  frontend/apps/erd-web/app/app/confirm/route.ts
  frontend/apps/erd-web/app/app/login/actions.ts
  frontend/apps/erd-web/app/app/login/page.tsx
  frontend/apps/erd-web/app/app/page.tsx
  frontend/apps/erd-web/app/error/page.tsx
  frontend/apps/erd-web/libs/db/server.ts
  frontend/apps/erd-web/middleware.ts
  frontend/apps/erd-web/package.json
  frontend/packages/db/package.json
  frontend/packages/db/src/index.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#838 ✨ Add pull request table
  docs/packages-license.md
  frontend/apps/erd-web/app/api/webhook/github/route.ts
  frontend/apps/erd-web/libs/github/api.ts
  frontend/packages/db/prisma/migrations/20250310092931_add_pull_request/migration.sql
  frontend/packages/db/prisma/migrations/20250311002649_change_pull_request_columns/migration.sql
  frontend/packages/db/prisma/schema.prisma
  pnpm-lock.yaml
Labels: Review effort 2/5

#841 🔧 (db): setup env file
  .env.template
  .gitignore
  CONTRIBUTING.md
  frontend/packages/db/.env
  frontend/packages/db/.env.template
  frontend/packages/db/package.json
Labels: Review effort 2/5, Possible security concern

#850 test: Disable Vercel Toolbar in VRT screenshots
  frontend/packages/e2e/tests/vrt/vrt.test.ts
Labels: Review effort 1/5

#839 ✨ Add new project creation feature in ERD web app
  frontend/apps/app/app/(app)/app/confirm/route.ts
  frontend/apps/app/app/(app)/app/layout.tsx
  frontend/apps/app/app/(app)/app/login/actions.ts
  frontend/apps/app/app/(app)/app/login/page.tsx
  frontend/apps/app/app/(app)/app/page.tsx
  frontend/apps/app/app/(app)/app/projects/new/page.tsx
  frontend/apps/app/app/globals.css
  frontend/apps/app/components/CommonLayout/CommonLayout.module.css
  frontend/apps/app/components/CommonLayout/CommonLayout.tsx
  frontend/apps/app/components/CommonLayout/index.ts
  frontend/apps/app/features/projects/actions/addProject.ts
  frontend/apps/app/features/projects/actions/index.ts
  frontend/apps/app/features/projects/pages/NewProjectPage/Form.tsx
  frontend/apps/app/features/projects/pages/NewProjectPage/NewProjectPage.module.css
  frontend/apps/app/features/projects/pages/NewProjectPage/NewProjectPage.tsx
  frontend/apps/app/features/projects/pages/NewProjectPage/index.ts
  frontend/apps/app/features/projects/pages/index.ts
Labels: Review effort 2/5

#853 🔧 fix asset prefix
  frontend/apps/app/.env.production
Labels: Review effort 1/5

#849 ✨: Enable Feature Flag
  frontend/apps/app/.env.development
  frontend/apps/app/app/(app)/app/page.tsx
  frontend/apps/app/middleware.ts
Labels: Review effort 2/5

#851 ✨ Add migration-web projects
  frontend/apps/app/app/(app)/app/projects/page.tsx
  frontend/apps/app/features/projects/pages/ProjectsPage/ProjectsPage.module.css
  frontend/apps/app/features/projects/pages/ProjectsPage/ProjectsPage.tsx
  frontend/apps/app/features/projects/pages/ProjectsPage/index.ts
  frontend/apps/app/features/projects/pages/index.ts
Labels: Review effort 2/5

#852 ♻️ Add environment variable validation for GitHub webhook
  frontend/apps/app/.env.development
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/instrumentation.ts
Labels: Review effort 2/5

#846 Add Trigger.dev and jobs
  config/dependency_decisions.yml
  docs/packages-license.md
  frontend/apps/app/.env.development
  frontend/apps/app/.gitignore
  frontend/apps/app/package.json
  frontend/apps/app/src/trigger/jobs.ts
  frontend/apps/app/trigger.config.ts
  package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#865 Add Slack notification for release workflow failures
  .github/workflows/release.yml
Labels: Review effort 1/5

#857 📝 Update development guidelines for frontend implementation
  .clinerules
  .cursorrules
Labels: Review effort 1/5

#855 ✨ Add-project-detail-page
  frontend/apps/app/app/(app)/app/projects/[id]/page.tsx
  frontend/apps/app/features/projects/actions/addProject.ts
  frontend/apps/app/features/projects/pages/NewProjectPage/Form.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.module.css
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/index.ts
  frontend/apps/app/features/projects/pages/index.ts
Labels: Review effort 2/5

#867 doc: Add src/trigger/flow.md
  frontend/apps/app/src/trigger/flow.md
Labels: Review effort 1/5

#854 Add repository table
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/libs/github/config.ts
  frontend/apps/app/libs/github/webhooks/index.ts
  frontend/apps/app/libs/github/webhooks/installation.ts
  frontend/apps/app/libs/github/webhooks/pull-request.ts
  frontend/apps/app/types/github.ts
  frontend/packages/db/prisma/migrations/20250311080742_add_repository_model/migration.sql
  frontend/packages/db/prisma/schema.prisma
Labels: Review effort 3/5

#856 ✨ Implement GitHub OAuth Authentication Flow
  frontend/apps/app/app/(app)/app/auth/callback/[provider]/route.ts
  frontend/apps/app/app/(app)/app/login/actions.ts
  frontend/apps/app/app/(app)/app/login/page.tsx
Labels: Review effort 2/5

#858 ✨ Add Migration model to Prisma schema
  frontend/packages/db/prisma/migrations/20250311115613_add_migration/migration.sql
  frontend/packages/db/prisma/migrations/20250312082348_delete_description_column/migration.sql
  frontend/packages/db/prisma/schema.prisma
Labels: Review effort 2/5

#873 🔧 Configure Supabase GitHub OAuth authentication
  .env.template
  frontend/packages/db/package.json
  frontend/packages/db/supabase/config.toml
Labels: Review effort 2/5

#870 🔧 Enabled `.env.local` environment variable loading in trigger.config
  frontend/apps/app/trigger.config.ts
Labels: Review effort 1/5

#877 Add helloWorldTask and webhook route for processing Hello World task
  frontend/apps/app/app/api/webhook/helloworld/route.ts
  frontend/apps/app/src/trigger/helloworld.ts
Labels: Review effort 1/5

#880 🔧 Refactor review generation types and process
  frontend/apps/app/src/functions/processGenerateReview.ts
  frontend/apps/app/src/trigger/jobs.ts
  frontend/apps/app/src/types.ts
  frontend/apps/app/src/types/index.ts
Labels: Review effort 2/5

#871 Add script to generate migration file for supabase
  frontend/packages/db/package.json
  frontend/packages/db/scripts/migrate-dev.sh
  frontend/packages/db/supabase/migrations/20250312095418_import_initial_ddl.sql
Labels: Review effort 2/5

#878 ✨ Add OverallReview model to Prisma schema
  frontend/packages/db/prisma/migrations/20250313054231_add_overall_review/migration.sql
  frontend/packages/db/prisma/schema.prisma
  frontend/packages/db/supabase/migrations/20250313054246_add_overall_review.sql
Labels: Review effort 1/5

#881 ✨ Add MigrationDetailPage component and associated styles
  frontend/apps/app/app/(app)/app/projects/[projectId]/migrations/[migrationId]/page.tsx
  frontend/apps/app/app/(app)/app/projects/[projectId]/page.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.module.css
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/index.ts
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.tsx
Labels: Review effort 2/5

#879 🔧 Update env-file configuration and documentation
  .env.template
  .github/workflows/vercel-deploy-erd.yml
  .gitignore
  CONTRIBUTING.md
  config/dependency_decisions.yml
  docs/packages-license.md
  frontend/apps/app/.env
  frontend/apps/app/.env.development
  package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#882 🔧 Update package.json to modify build and release scripts
  package.json
Labels: Review effort 1/5

#869 Add processSavePullRequest function and integrate it into the savePullRequestTask
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/libs/github/api.ts
  frontend/apps/app/libs/github/webhooks/pull-request.ts
  frontend/apps/app/src/functions/processSavePullRequest.ts
  frontend/apps/app/src/trigger/flow.md
  frontend/apps/app/src/trigger/jobs.ts
  frontend/apps/app/src/types/index.ts
  frontend/apps/app/types/github.ts
Labels: Review effort 3/5

#888 🔧 A build that has been executed twice has been changed to once
  .github/workflows/vercel-deploy-erd.yml
  frontend/apps/app/package.json
  frontend/apps/app/scripts/update_dist_content.js
Labels: Review effort 1/5

#886 ✨ Implement postComment function for handling PR comments
  frontend/apps/app/src/functions/postComment.ts
  frontend/apps/app/src/trigger/jobs.ts
  memory-bank/progress.md
  memory-bank/systemPatterns.md
  memory-bank/techContext.md
Labels: Review effort 2/5

#875 ✨ Enable Project Creation from GitHub App Installed Repositories
  frontend/apps/app/app/(app)/app/projects/new/page.tsx
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/features/projects/pages/NewProjectPage/Form.tsx
  frontend/apps/app/features/projects/pages/NewProjectPage/NewProjectPage.module.css
  frontend/apps/app/features/projects/pages/NewProjectPage/NewProjectPage.tsx
  frontend/apps/app/features/projects/pages/NewProjectPage/index.ts
  frontend/apps/app/features/projects/pages/ProjectNewPage/InstallationSelector/InstallationSelector.module.css
  frontend/apps/app/features/projects/pages/ProjectNewPage/InstallationSelector/InstallationSelector.tsx
  frontend/apps/app/features/projects/pages/ProjectNewPage/InstallationSelector/index.ts
  frontend/apps/app/features/projects/pages/ProjectNewPage/ProjectNewPage.module.css
  frontend/apps/app/features/projects/pages/ProjectNewPage/ProjectNewPage.tsx
  frontend/apps/app/features/projects/pages/ProjectNewPage/RepositoryItem/RepositoryItem.module.css
  frontend/apps/app/features/projects/pages/ProjectNewPage/RepositoryItem/RepositoryItem.tsx
  frontend/apps/app/features/projects/pages/ProjectNewPage/RepositoryItem/index.ts
  frontend/apps/app/features/projects/pages/ProjectNewPage/index.ts
  frontend/apps/app/features/projects/pages/index.ts
  frontend/apps/app/libs/db/client.ts
  frontend/apps/app/libs/github/api.browser.ts
  frontend/apps/app/libs/github/api.server.ts
  frontend/apps/app/libs/github/types.ts
  frontend/apps/app/libs/github/webhooks/pull-request.ts
  frontend/apps/app/package.json
  frontend/apps/app/src/functions/postComment.ts
  frontend/apps/app/src/functions/processSavePullRequest.ts
  frontend/packages/db/src/index.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#885 🔧 implement saveReviewTask and add test
  docs/packages-license.md
  frontend/apps/app/app/.well-known/vercel/flags/route.ts
  frontend/apps/app/package.json
  frontend/apps/app/src/functions/__tests__/processSaveReview.test.ts
  frontend/apps/app/src/functions/processSavePullRequest.ts
  frontend/apps/app/src/functions/processSaveReview.ts
  frontend/apps/app/src/trigger/jobs.ts
  frontend/apps/app/src/types/index.ts
  frontend/apps/app/vitest.config.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#892 🐛 bug fix: Update payload handling for webhook signature verification
  frontend/apps/app/app/api/webhook/github/route.ts
Labels: Review effort 2/5

#890 fix: some fixies for savePullRequest
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/src/functions/processSavePullRequest.ts
  frontend/apps/app/src/trigger/jobs.ts
  frontend/apps/app/src/types/index.ts
Labels: Review effort 2/5

#894 🔧 Add Prisma plugin for Next.js monorepo support
  docs/packages-license.md
  frontend/apps/app/next.config.ts
  frontend/apps/app/package.json
  frontend/apps/app/types/prisma-plugin.d.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#896 Add-gitHub-app-installation-link
  frontend/apps/app/app/(app)/app/page.tsx
  frontend/apps/app/features/projects/pages/ProjectNewPage/InstallationSelector/InstallationSelector.tsx
Labels: Review effort 2/5

#900 🔧 fetch repository details in GitHub webhook handler
  frontend/apps/app/app/api/webhook/github/route.ts
Labels: Review effort 2/5

#897 ✨ Add ProjectRepositoryMapping model and related migrations
  frontend/packages/db/prisma/migrations/20250314074412_add/migration.sql
  frontend/packages/db/prisma/migrations/20250314074636_delete_project_relation/migration.sql
  frontend/packages/db/prisma/schema.prisma
  frontend/packages/db/supabase/migrations/20250314074428_add.sql
  frontend/packages/db/supabase/migrations/20250314074651_delete_project_relation.sql
Labels: Review effort 2/5

#899 🔧 Refactor getAuthCallbackUrl function to handle VERCEL_URL environment variable
  frontend/apps/app/app/(app)/app/login/actions.ts
Labels: Review effort 1/5

#895 🔧 Add migration url to postComment job
  frontend/apps/app/.env.development
  frontend/apps/app/src/functions/__tests__/postComment.test.ts
  frontend/apps/app/src/functions/__tests__/processSaveReview.test.ts
  frontend/apps/app/src/functions/postComment.ts
  frontend/apps/app/src/functions/processSaveReview.ts
Labels: Review effort 2/5

#901 🐛 Fix ts error
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.tsx
  frontend/apps/app/package.json
  frontend/apps/app/src/functions/__tests__/postComment.test.ts
Labels: Review effort 2/5

#902 🔧 Update Prisma schema to include additional binary target
  frontend/packages/db/prisma/schema.prisma
Labels: Review effort 1/5

#903 ✨ Updated addProject action to handle repository creation and mapping
  frontend/apps/app/features/projects/actions/addProject.ts
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectNewPage/InstallationSelector/InstallationSelector.tsx
Labels: Review effort 3/5

#904 🔧 Make ``projectId`` nullable in ``OverallReview`` table.
  frontend/apps/app/package.json
  frontend/apps/app/src/functions/__tests__/postComment.test.ts
  frontend/apps/app/src/functions/processSaveReview.ts
  frontend/apps/app/src/trigger/jobs.ts
  frontend/packages/db/prisma/migrations/20250314091509_make_overall_review_project_id_nullable/migration.sql
  frontend/packages/db/prisma/schema.prisma
  pnpm-lock.yaml
Labels: Review effort 2/5

#905 creation of migration record
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/src/functions/processSavePullRequest.ts
  frontend/apps/app/src/trigger/jobs.ts
Labels: Review effort 2/5

#906 🔧 Configure Prisma extension in trigger.config.ts
  frontend/apps/app/package.json
  frontend/apps/app/trigger.config.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#907 Extract projectId from repository mapping and update task payload
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/features/projects/actions/addProject.ts
  frontend/apps/app/src/trigger/jobs.ts
  frontend/apps/app/src/types/index.ts
Labels: Review effort 2/5

#910 Pin third-party GitHub Actions versions with Full Changeset Hash
  .github/actions/pnpm-setup/action.yml
  .github/dependabot.yml
  .github/workflows/figma-to-css-variables.yml
  .github/workflows/frontend-ci.yml
  .github/workflows/license.yml
  .github/workflows/prompt-evaluation.yml
  .github/workflows/release.yml
  .github/workflows/vercel-deploy-erd.yml
Labels: Review effort 2/5

#916 ✨ Add WatchSchemaFilePattern model to Project schema
  frontend/packages/db/prisma/migrations/20250317054258_add_watch_schema_file_pattern/migration.sql
  frontend/packages/db/prisma/schema.prisma
  frontend/packages/db/supabase/migrations/20250317054314_add_watch_schema_file_pattern.sql
Labels: Review effort 2/5

#908 ✨ Add --output-dir option to specify output directory
  .changeset/rare-rings-warn.md
  frontend/apps/docs/content/docs/cli/ci-cd.mdx
  frontend/apps/docs/content/docs/cli/index.mdx
  frontend/packages/cli/src/cli/erdCommand/buildCommand/index.ts
  frontend/packages/cli/src/cli/erdCommand/index.test.ts
  frontend/packages/cli/src/cli/erdCommand/index.ts
  frontend/packages/db-structure/package.json
  frontend/packages/db-structure/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#909 ✨ Set table show mode in related tables to TABLE_NAME
  .changeset/wicked-feet-jog.md
  frontend/packages/erd-core/src/features/erd/components/ERDContent/ERDContent.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableHeader/TableHeader.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableNode.tsx
  frontend/packages/erd-core/src/features/erd/types.ts
Labels: Review effort 1/5

#920 🔧 Rename script command from "dev:trigger" to "trigger:dev" in package.json for consistency
  frontend/apps/app/package.json
Labels: Review effort 1/5

#919 🔧 Update database connection URL in Prisma schema to use POSTGRES_URL
  frontend/packages/db/prisma/schema.prisma
Labels: Review effort 1/5

#912 e2e test to run when deploying with vercel
  .github/workflows/e2e_tests.yml
  .github/workflows/vercel-deploy-erd.yml
Labels: Review effort 2/5

#918 ✨ Add checkSchemaChanges function
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/app/api/webhook/github/utils/__tests__/checkSchemaChanges.test.ts
  frontend/apps/app/app/api/webhook/github/utils/checkSchemaChanges.ts
  frontend/apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#925 🔧 Update Prisma schema to use non-pooling database URL
  frontend/packages/db/prisma/schema.prisma
Labels: Review effort 1/5

#926 🐛 Fix/install-id-pr-files
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/app/api/webhook/github/utils/__tests__/checkSchemaChanges.test.ts
  frontend/apps/app/app/api/webhook/github/utils/checkSchemaChanges.ts
Labels: Review effort 2/5

#923 🔧 Update instrumentation.ts to validate environment variables
  frontend/apps/app/instrumentation.ts
Labels: Review effort 1/5

#924 🔧 Fix e2e test execution conditions in production
  .github/workflows/e2e_tests.yml
Labels: Review effort 1/5

#930 🔧 Add Sentry authToken configuration to Next.js config files
  frontend/apps/app/next.config.ts
  turbo.json
Labels: Review effort 1/5

#936 🔧 Chore: Add Supabase reset script to package.json
  frontend/packages/db/package.json
Labels: Review effort 1/5

#938 🔧 Update GitHub webhook signature validation for local development
  frontend/apps/app/app/api/webhook/github/route.ts
Labels: Review effort 1/5

#935 ✨ Add the contents of the schema file to the review generation process.
  frontend/apps/app/libs/github/api.server.ts
  frontend/apps/app/src/functions/processGenerateReview.ts
  frontend/apps/app/src/functions/processSavePullRequest.ts
  frontend/apps/app/src/trigger/jobs.ts
  frontend/apps/app/src/types/index.ts
Labels: Review effort 3/5

#945 Implement Migration Detail Page and Update Styles
  frontend/apps/app/app/(app)/app/migrations/[migrationId]/page.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.module.css
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.tsx
Labels: Review effort 2/5

#929 🔧 Update GitHub auth configuration to use environment variables directly
  frontend/apps/app/libs/github/config.ts
  frontend/packages/db/supabase/config.toml
Labels: Review effort 1/5

#949 🔧 Add `title` column to `DocVersion` model in Prisma schema and corresponding SQL migrations
  frontend/packages/db/prisma/migrations/20250321012007_add_title_to_doc_version/migration.sql
  frontend/packages/db/prisma/schema.prisma
  frontend/packages/db/supabase/migrations/20250321012022_add_title_to_doc_version.sql
Labels: Review effort 2/5

#950 🔧 Update authentication callback URL to use VERCEL_BRANCH_URL
  frontend/apps/app/app/(app)/app/login/actions.ts
Labels: Review effort 1/5

#953 🔧 Remove .env.development file
  .env.template
  frontend/apps/app/.env.development
Labels: Review effort 1/5

#946 ✨ Add docs content to review agent
  frontend/apps/app/src/functions/processGenerateReview.ts
Labels: Review effort 2/5

#956 ✨ Update CONTRIBUTING.md to clarify environment variable setup for maintainers and other contributors
  CONTRIBUTING.md
Labels: Review effort 1/5

#959 ♻️ Remove deprecated GitHub webhook handling for pull requests
  frontend/apps/app/libs/github/webhooks/index.ts
  frontend/apps/app/libs/github/webhooks/pull-request.ts
Labels: Review effort 1/5

#941 ✨ Link schemas in the repository and continuously update the ERD
  frontend/apps/app/app/(app)/app/projects/[projectId]/erd/[branchOrCommit]/[...slug]/erdViewer.tsx
  frontend/apps/app/app/(app)/app/projects/[projectId]/erd/[branchOrCommit]/[...slug]/page.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.module.css
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/libs/github/api.server.ts
  frontend/apps/app/src/functions/processSavePullRequest.ts
Labels: Review effort 3/5

#957 🐛 Enhance tests for long SQL statements and fix errorOffset handling
  .changeset/large-ligers-warn.md
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/processSQLInChunks.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/processSQLInChunks.ts
Labels: Review effort 2/5

#966 ✨ Add .env.local to .gitignore and create .env.local file for local env
  CONTRIBUTING.md
  frontend/apps/app/.env.local
  frontend/apps/app/.gitignore
  package.json
Labels: Review effort 1/5

#965 Bump next from 15.1.2 to 15.2.3 & $ pmpn i; pnpm fmt; pnpm i
  docs/packages-license.md
  frontend/apps/app/package.json
  frontend/apps/docs/package.json
  pnpm-lock.yaml
Labels: Review effort 1/5

#973 ASSET_PREFIX check (on VERCEL_ENV === 'production')
  frontend/apps/app/next.config.ts
  frontend/apps/docs/next.config.mjs
Labels: Review effort 1/5

#975 🐛 Fix incorrect migration URL path
  frontend/apps/app/src/functions/postComment.ts
Labels: Review effort 1/5

#967 📄 Add new ADR: Document decision to adopt CSS Modules as a styling method
  frontend/apps/docs/content/docs/contributing/adr/20241003-use-css-modules-for-styling.mdx
Labels: Review effort 1/5

#968 📄 Add new ADR for using React Flow in ERD visualization implementation
  frontend/apps/docs/content/docs/contributing/adr/20241112-use-react-flow-for-erd-visualization.mdx
Labels: Review effort 1/5

#972 feat(db-structure): add schema overrides function
  frontend/packages/db-structure/src/schema/dbStructure.ts
  frontend/packages/db-structure/src/schema/overrideDbStructure.test.ts
  frontend/packages/db-structure/src/schema/overrideDbStructure.ts
Labels: Review effort 3/5

#977 🔧 Match `next-config` settings with docs so that `sourcemap` can be sent.
  frontend/apps/app/next.config.ts
Labels: Review effort 1/5

#983 🔧 format package.json
  .github/workflows/frontend-ci.yml
  package.json
Labels: Review effort 1/5

#979 📝: add ADR for Node.js-based unified DB schema parsing documentation
  frontend/apps/docs/content/docs/contributing/adr/20241206-node-js-based-unified-db-schema-parsing.mdx
Labels: Review effort 2/5

#980 📝: add decision record for adopting Fumadocs as documentation site framework
  frontend/apps/docs/content/docs/contributing/adr/20241128-use-fumadocs-for-documentation-site.mdx
Labels: Review effort 1/5

#944 🔧 Direct Supabase Client Integration: Redefining Data Access Without Prisma
  .github/workflows/frontend-ci.yml
  frontend/apps/app/features/projects/pages/ProjectsPage/ProjectsPage.tsx
  frontend/packages/db/package.json
  frontend/packages/db/src/index.ts
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250319115250_remote_schema.sql
Labels: Review effort 3/5

#990 feat(supabase): Add staging remote configuration
  frontend/packages/db/supabase/config.toml
Labels: Review effort 1/5

#984 🗃️ add initial seed data for Project and Repository tables
  frontend/packages/db/supabase/seed.sql
Labels: Review effort 1/5

#995 Calling `$ pnpm test:turbo` now also runs tests under `frontend/apps/app`.
  frontend/apps/app/package.json
  frontend/apps/app/src/functions/__tests__/postComment.test.ts
  frontend/apps/app/src/functions/__tests__/processSaveReview.test.ts
Labels: Review effort 2/5

#999 🔨 add migration command to package.json for Supabase
  frontend/packages/db/package.json
Labels: Review effort 1/5

#1001 fix: update project link path in CommonLayout and remove collaborators section
  frontend/apps/app/components/CommonLayout/CommonLayout.tsx
Labels: Review effort 1/5

#993 feat(database): implement base of KnowledgeSuggestion
  frontend/apps/app/app/(app)/app/projects/[projectId]/knowledge-suggestions/[id]/page.tsx
  frontend/apps/app/app/(app)/app/projects/[projectId]/knowledge-suggestions/page.tsx
  frontend/apps/app/features/projects/actions/approveKnowledgeSuggestion.ts
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/index.ts
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionsListPage/KnowledgeSuggestionsListPage.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionsListPage/index.ts
  frontend/apps/app/src/functions/getInstallationIdFromRepositoryId.ts
  frontend/apps/app/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/apps/app/src/trigger/jobs.ts
  frontend/apps/app/src/types/index.ts
  frontend/packages/db/prisma/migrations/20250327035547_add_knowledge_suggestion/migration.sql
  frontend/packages/db/prisma/schema.prisma
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250327035602_add-knowledge-suggestion.sql
  frontend/packages/github/src/api.server.ts
  memory-bank/progress.md
Labels: Review effort 4/5

#1003 🔧 Enable Vitest tests with Supabase DB access and enhance CI workflow
  .env.template
  .github/workflows/frontend-ci.yml
  frontend/apps/app/features/projects/pages/ProjectsPage/ProjectsPage.tsx
  frontend/apps/app/features/projects/pages/ProjectsPage/getProjects.test.ts
  frontend/apps/app/features/projects/pages/ProjectsPage/getProjects.ts
  frontend/apps/app/vitest.config.ts
  frontend/apps/app/vitest.setup.ts
  scripts/extract-supabase-anon-key.sh
Labels: Review effort 2/5

#989 chore: update biome configuration to disable noUndeclaredDependencies linting rule
  biome.jsonc
Labels: Review effort 1/5

#996 ✨ Display merged dbStructure with DBOverride in ERDViewer
  frontend/apps/app/app/(app)/app/projects/[projectId]/erd/[branchOrCommit]/[...slug]/constants.ts
  frontend/apps/app/app/(app)/app/projects/[projectId]/erd/[branchOrCommit]/[...slug]/page.tsx
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db/supabase/migrations/20250326101212_table_permission.sql
Labels: Review effort 3/5

#1004 🔥 Add docs suggestion generation
  frontend/apps/app/src/functions/processGenerateDocsSuggestion.ts
  frontend/apps/app/src/trigger/jobs.ts
Labels: Review effort 3/5

#1012 🔧 Update CI workflow to streamline Supabase types generation
  .github/workflows/frontend-ci.yml
Labels: Review effort 2/5

#1000 🔧 Add branch name to overall review table
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/src/functions/__tests__/postComment.test.ts
  frontend/apps/app/src/functions/__tests__/processSaveReview.test.ts
  frontend/apps/app/src/functions/processSavePullRequest.ts
  frontend/apps/app/src/functions/processSaveReview.ts
  frontend/apps/app/src/trigger/jobs.ts
  frontend/apps/app/src/types/index.ts
  frontend/packages/db/prisma/migrations/20250327033040_add_branch_name_to_overall_review/migration.sql
  frontend/packages/db/prisma/schema.prisma
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250327034651_add_branch_name_to_overall_review.sql
  frontend/packages/github/src/types.ts
Labels: Review effort 2/5

#1013 ✨ Add GitHubDocFilePath model and migration scripts
  frontend/packages/db/prisma/migrations/20250327101710_add_github_doc_file_path_with_unique_constraint/migration.sql
  frontend/packages/db/prisma/schema.prisma
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250327101743_add_github_doc_file_path_with_unique_constraint.sql
Labels: Review effort 2/5

#1009 ✨ Display ERD using override file loaded from the specified branch or commit
  .liam/schema-meta.json
  frontend/apps/app/app/(app)/app/projects/[projectId]/erd/[branchOrCommit]/[...slug]/constants.ts
  frontend/apps/app/app/(app)/app/projects/[projectId]/erd/[branchOrCommit]/[...slug]/page.tsx
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/schema/index.ts
Labels: Review effort 2/5

#994 Refactor trigger-related workflows into dedicated `@liam-hq/jobs` package
  .github/workflows/trigger_dev_production.yml
  .github/workflows/trigger_dev_staging.yml
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/app/api/webhook/github/utils/__tests__/checkSchemaChanges.test.ts
  frontend/apps/app/app/api/webhook/github/utils/checkSchemaChanges.ts
  frontend/apps/app/app/api/webhook/helloworld/route.ts
  frontend/apps/app/package.json
  frontend/apps/app/tsconfig.json
  frontend/apps/docs/content/docs/contributing/repository-architecture.mdx
  frontend/packages/jobs/.gitignore
  frontend/packages/jobs/biome.jsonc
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/functions/__tests__/postComment.test.ts
  frontend/packages/jobs/src/functions/__tests__/processSaveReview.test.ts
  frontend/packages/jobs/src/functions/getInstallationIdFromRepositoryId.ts
  frontend/packages/jobs/src/functions/langfuseLangchainHandler.ts
  frontend/packages/jobs/src/functions/postComment.ts
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateReview.ts
  frontend/packages/jobs/src/functions/processSavePullRequest.ts
  frontend/packages/jobs/src/functions/processSaveReview.ts
  frontend/packages/jobs/src/index.ts
  frontend/packages/jobs/src/jobs/helloworld.ts
  frontend/packages/jobs/src/trigger/flow.md
  frontend/packages/jobs/src/trigger/helloworld.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  frontend/packages/jobs/src/types/index.ts
  frontend/packages/jobs/trigger.config.ts
  frontend/packages/jobs/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#1018 Add automated schema.sql consistency check in CI
  .github/workflows/frontend-ci.yml
  frontend/packages/db/package.json
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/scripts/generate-schema-ddl.sh
Labels: Review effort 2/5

#1020 fix(github-webhook): handle timingSafeEqual error when signature length differs
  frontend/apps/app/app/api/webhook/github/route.ts
Labels: Review effort 1/5

#1016 ✨ Implement DocsDetailPage component and related functionality
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/DocsDetailPage.module.css
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/DocsDetailPage.tsx
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/getDocumentContent.ts
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/getProjectRepository.test.ts
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/getProjectRepository.ts
  frontend/apps/app/app/(app)/app/projects/[projectId]/ref/[branchOrCommit]/docs/[...docFilePath]/page.tsx
Labels: Review effort 2/5

#1019 ✨ Add branch List page
  frontend/apps/app/app/(app)/app/projects/[projectId]/branches/page.tsx
  frontend/apps/app/features/projects/pages/ProjectBranchesListPage/ProjectBranchesListPage.module.css
  frontend/apps/app/features/projects/pages/ProjectBranchesListPage/ProjectBranchesListPage.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.tsx
  frontend/packages/github/src/api.server.ts
Labels: Review effort 2/5

#1024 🐛 Move trigger:dev script
  docs/packages-license.md
  frontend/apps/app/package.json
  frontend/packages/jobs/.env
  frontend/packages/jobs/.gitignore
  frontend/packages/jobs/package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1023 📝 update migration review documentation template for clarity and structure
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
Labels: Review effort 1/5

#1025 Refactor Supabase type and schema checks in CI
  .github/workflows/frontend-ci.yml
  frontend/packages/db/package.json
Labels: Review effort 2/5

#1027 ✨ Add .env.local file for jobs package configuration
  frontend/packages/jobs/.env.local
Labels: Review effort 1/5

#1021 ✨ implement type-safe URL generator with parameter validation
  frontend/apps/app/app/(app)/app/page.tsx
  frontend/apps/app/app/(app)/app/projects/[projectId]/erd/[branchOrCommit]/[...slug]/page.tsx
  frontend/apps/app/components/CommonLayout/CommonLayout.tsx
  frontend/apps/app/features/migrations/pages/MigrationDetailPage/MigrationDetailPage.tsx
  frontend/apps/app/features/projects/actions/addProject.ts
  frontend/apps/app/features/projects/actions/approveKnowledgeSuggestion.ts
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionDetailPage/KnowledgeSuggestionDetailPage.tsx
  frontend/apps/app/features/projects/pages/KnowledgeSuggestionsListPage/KnowledgeSuggestionsListPage.tsx
  frontend/apps/app/features/projects/pages/ProjectDetailPage/ProjectDetailPage.tsx
  frontend/apps/app/features/projects/pages/ProjectsPage/ProjectsPage.tsx
  frontend/apps/app/utils/routes/index.ts
  frontend/apps/app/utils/routes/paramsSchema.ts
  frontend/apps/app/utils/routes/routeDefinitions.ts
  frontend/apps/app/utils/routes/urlgen.ts
Labels: Review effort 3/5

#1030 ✨ Implement createFileContent function and update knowledge suggestion processing to support branch-specific file creation
  frontend/packages/github/src/api.server.ts
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  frontend/packages/jobs/src/functions/processGenerateDocsSuggestion.ts
  frontend/packages/jobs/src/trigger/jobs.ts
Labels: Review effort 3/5

#1026 ✨ Enhance processGenerateReview function to fetch review-enabled document content from GitHub
  frontend/packages/jobs/src/functions/processGenerateReview.ts
Labels: Review effort 2/5

#1034 🔧 Remove unused "types" field from package.json in the GitHub package
  frontend/packages/github/package.json
Labels: Review effort 1/5

#1033 ✨ Add branchName and use it in process of knowledge suggestion
  frontend/apps/app/features/projects/actions/approveKnowledgeSuggestion.ts
  frontend/packages/db/prisma/migrations/20250328105323_add_branch_name_to_knowledge_suggestion/migration.sql
  frontend/packages/db/prisma/schema.prisma
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250328105339_add_branch_name_to_knowledge_suggestion.sql
  frontend/packages/github/src/api.server.ts
  frontend/packages/jobs/src/functions/processCreateKnowledgeSuggestion.ts
  memory-bank/progress.md
Labels: Review effort 2/5

#964 💄 Show Indexes instead of Unique
  .changeset/slimy-fishes-applaud.md
  frontend/apps/erd-web/.next/trace
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
  frontend/packages/db-structure/src/parser/__tests__/testcase.ts
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
  frontend/packages/db-structure/src/parser/schemarb/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/schemarb/singularize.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/mergeDBStructures.ts
  frontend/packages/db-structure/src/parser/tbls/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/parser.ts
  frontend/packages/db-structure/src/schema/dbStructure.ts
  frontend/packages/db-structure/src/schema/factories.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db-structure/src/schema/overrideDbStructure.test.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indexes/Indexes.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indexes/IndexesItem/IndexesItem.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indexes/IndexesItem/IndexesItem.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indexes/IndexesItem/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indexes/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indices/Indices.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indices/Indices.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Indices/index.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/RelatedTables/RelatedTables.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/TableDetail.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Unique/Unique.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Unique/Unique.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Unique/index.ts
  frontend/packages/ui/src/icons/FileText.tsx
  frontend/packages/ui/src/icons/index.ts
Labels: Review effort 2/5

#1041 🔧 Update vrt screenshot
  .github/workflows/e2e_tests.yml
  frontend/packages/e2e/tests/vrt/vrt.test.ts-snapshots/top-1-Mobile-Safari-linux.png
  frontend/packages/e2e/tests/vrt/vrt.test.ts-snapshots/top-1-chromium-linux.png
Labels: Review effort 1/5

#1028 refactor: simplify dump command
  frontend/packages/db/package.json
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/scripts/generate-schema-ddl.sh
Labels: Review effort 2/5

#1045 ⬆️ Update dependency @xyflow/react to v12.5.0
  .changeset/chatty-kangaroos-return.md
  docs/packages-license.md
  frontend/packages/erd-core/package.json
  frontend/packages/erd-core/src/features/reactflow/hooks/useCustomReactflow.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#1044 Use stable ref for erd-sample build script
  frontend/apps/app/app/page.tsx
  frontend/apps/erd-sample/package.json
Labels: Review effort 1/5

#1054 Revert "⬆️ Update dependency @xyflow/react to v12.5.0"
  .changeset/chatty-kangaroos-return.md
  docs/packages-license.md
  frontend/packages/erd-core/package.json
  frontend/packages/erd-core/src/features/reactflow/hooks/useCustomReactflow.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#1035 🔧 Remove unused Doc and DocVersion models from the database schema
  frontend/packages/db/prisma/migrations/20250328121434_remove_doc_tables/migration.sql
  frontend/packages/db/prisma/schema.prisma
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250328121449_remove_doc_tables.sql
  memory-bank/progress.md
Labels: Review effort 2/5
