Repository liam-hq/liam, pull requests merged in 2025-05, with the labels that each got.

#1569 【PoC】UI/agent select
  frontend/apps/app/features/schemas/components/Chatbot/AgentSelect.module.css
  frontend/apps/app/features/schemas/components/Chatbot/AgentSelect.tsx
  frontend/apps/app/features/schemas/components/Chatbot/ChatInput.module.css
  frontend/apps/app/features/schemas/components/Chatbot/ChatInput.tsx
  frontend/apps/app/features/schemas/components/Chatbot/ChatbotDrawer/ChatbotDrawer.tsx
  frontend/apps/app/features/schemas/components/Chatbot/icons/BuildJack.svg
  frontend/apps/app/features/schemas/components/Chatbot/icons/BuildJackIcon.tsx
  frontend/apps/app/features/schemas/components/Chatbot/icons/FixJack.svg
  frontend/apps/app/features/schemas/components/Chatbot/icons/FixJackIcon.tsx
  frontend/apps/app/features/schemas/components/Chatbot/icons/LearnJack.svg
  frontend/apps/app/features/schemas/components/Chatbot/icons/LearnJackIcon.tsx
  frontend/apps/app/features/schemas/components/Chatbot/icons/index.ts
Labels: Review effort 3/5

#1572 🐛(layout): Update parameter parsing in layout components to await params
  frontend/apps/app/app/(app)/app/(with-project)/projects/[projectId]/layout.tsx
  frontend/apps/app/app/(app)/app/(with-project-and-branch)/projects/[projectId]/ref/[branchOrCommit]/layout.tsx
  frontend/apps/app/app/(app)/app/(with-project-and-branch)/projects/[projectId]/ref/[branchOrCommit]/page.tsx
Labels: Review effort 1/5

#1575 【PoC】UI/voice
  frontend/apps/app/features/schemas/components/Chatbot/ChatInput.module.css
  frontend/apps/app/features/schemas/components/Chatbot/ChatInput.tsx
Labels: Review effort 2/5

#1408 ✨ enhance the schema.rb parser to support Constraints
  .changeset/wet-zoos-add.md
  frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
  frontend/packages/db-structure/src/parser/schemarb/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/schema/factories.ts
  frontend/packages/db-structure/src/schema/index.ts
Labels: Review effort 3/5

#1579 💄 add avatars to chat messages
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/features/schemas/components/Chatbot/ChatMessage.module.css
  frontend/apps/app/features/schemas/components/Chatbot/ChatMessage.tsx
  frontend/apps/app/features/schemas/components/Chatbot/ChatbotDrawer/ChatbotDrawer.tsx
  frontend/apps/app/features/schemas/components/Chatbot/hooks/useAuthUser.ts
  frontend/apps/app/features/schemas/components/Chatbot/icons/BuildJack.svg
  frontend/apps/app/features/schemas/components/Chatbot/icons/BuildJackIcon.tsx
  frontend/apps/app/features/schemas/components/Chatbot/icons/FixJack.svg
  frontend/apps/app/features/schemas/components/Chatbot/icons/LearnJack.svg
  frontend/apps/app/features/schemas/components/Chatbot/icons/LearnJackIcon.tsx
Labels: Review effort 3/5

#1581 add: fix the left pane with when mobile device
  .changeset/old-seahorses-peel.md
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
Labels: Review effort 2/5

#1583 Lint warning fix
  frontend/apps/app/app/api/chat/route.ts
  frontend/packages/cli/src/cli/initCommand/index.ts
  frontend/packages/db-structure/src/parser/prisma/convertToPostgresColumnType.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/processSQLInChunks.ts
  frontend/packages/db-structure/src/parser/tbls/parser.ts
  frontend/packages/db-structure/src/schema/overrideSchema.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#1607 fix notify_supabase_failure.yml `The workflow is not valid.`
  .github/workflows/notify_supabase_failure.yml
Labels: Review effort 1/5

#1610 ✅ Add tests for organization_members RLS policies from PR #1598
  frontend/packages/db/supabase/tests/database/03-organization_members_rls.test.sql
Labels: Review effort 2/5

#1613 🔧(test): Update toolbar test for improved reliability
  frontend/packages/e2e/tests/e2e/toolbar.test.ts
Labels: Review effort 1/5

#1614 Permit the licenses `Artistic-2.0` and `Zlib`
  config/dependency_decisions.yml
Labels: Review effort 1/5

#1606 ✨ feat: introduce Storybook
  config/dependency_decisions.yml
  frontend/apps/app/.gitignore
  frontend/apps/app/components/UserFeedbackComponent.stories.tsx
  frontend/apps/app/package.json
  frontend/apps/app/types/storybook.d.ts
  frontend/internal-packages/storybook/.gitignore
  frontend/internal-packages/storybook/.storybook/README.md
  frontend/internal-packages/storybook/.storybook/langfuseWeb.mock.ts
  frontend/internal-packages/storybook/.storybook/main.ts
  frontend/internal-packages/storybook/.storybook/preview-head.html
  frontend/internal-packages/storybook/.storybook/preview.ts
  frontend/internal-packages/storybook/README.md
  frontend/internal-packages/storybook/package.json
  frontend/packages/configs/eslint/base.js
  frontend/packages/ui/package.json
  frontend/packages/ui/src/components/Button/Button.stories.tsx
  pnpm-lock.yaml
  turbo.json
Labels: Review effort 2/5

#1620 ✨ Fix Storybook build and configure Vercel deployment
  frontend/internal-packages/storybook/.storybook/main.ts
  frontend/internal-packages/storybook/.storybook/public/.gitkeep
  frontend/internal-packages/storybook/package.json
  frontend/internal-packages/storybook/public/.gitkeep
  frontend/internal-packages/storybook/vercel.json
Labels: Review effort 2/5

#1617 🔧 Fix job error
  frontend/apps/app/app/api/webhook/github/route.ts
  frontend/apps/app/app/api/webhook/github/utils/checkSchemaChanges.ts
  frontend/apps/app/libs/db/server.ts
  frontend/packages/jobs/package.json
Labels: Review effort 2/5

#1621 ✨️ feat(UI): Implement NewThreadButton for chat interface
  frontend/apps/app/components/Chat/NewThreadButton/NewThreadButton.stories.tsx
  frontend/apps/app/components/Chat/NewThreadButton/NewThreadButton.tsx
  frontend/packages/ui/src/components/IconButton/IconButton.module.css
  frontend/packages/ui/src/components/IconButton/IconButton.stories.tsx
  frontend/packages/ui/src/components/IconButton/IconButton.tsx
  frontend/packages/ui/src/components/Tooltip/Tooltip.stories.tsx
Labels: Review effort 2/5

#1627 ✨️ feat(chat): implement ThreadListButton component
  frontend/apps/app/components/Chat/ThreadListButton/ThreadListButton.stories.tsx
  frontend/apps/app/components/Chat/ThreadListButton/ThreadListButton.tsx
  frontend/packages/ui/src/icons/index.ts
Labels: Review effort 1/5

#1600 ✅️ feat(ci): post E2E test status manually using GitHub CLI
  .github/workflows/e2e_tests.yml
Labels: Review effort 2/5

#1623 📝 add Directory Structure Guidelines to AI Coding rules
  .clinerules/general.md
Labels: Review effort 2/5

#1638 Now `notify_supabase_failure.yml` reports only main branch
  .github/workflows/notify_supabase_failure.yml
Labels: Review effort 1/5

#1641 ♻️ relocate auth page components from `features/` to `components/`
  frontend/apps/app/app/app/login/page.tsx
  frontend/apps/app/components/LoginPage/EmailForm.tsx
  frontend/apps/app/components/LoginPage/LoginPage.module.css
  frontend/apps/app/components/LoginPage/LoginPage.tsx
  frontend/apps/app/components/LoginPage/SignInGithubButton.tsx
  frontend/apps/app/components/LoginPage/index.ts
  frontend/apps/app/components/LoginPage/services/loginByEmail.ts
  frontend/apps/app/components/LoginPage/services/loginByGithub.ts
Labels: Review effort 2/5

#1635 :recycle: Extract UserMessage component from ChatMessage
  frontend/apps/app/components/Chat/UserMessage/UserMessage.module.css
  frontend/apps/app/components/Chat/UserMessage/UserMessage.stories.tsx
  frontend/apps/app/components/Chat/UserMessage/UserMessage.tsx
  frontend/apps/app/components/Chat/UserMessage/index.ts
  frontend/apps/app/features/schemas/components/Chatbot/ChatMessage.tsx
Labels: Review effort 2/5

#1587 ✨ Enhance the PostgreSQL parser to support Constraints
  .changeset/olive-women-notice.md
  frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
Labels: Review effort 3/5

#1633 ♻️ relocate invitation page components from `features/` to `components/`
  frontend/apps/app/app/(app)/app/(root)/invitations/tokens/[token]/page.tsx
  frontend/apps/app/components/InvitationPage/InvitationPage.tsx
  frontend/apps/app/components/InvitationPage/components/InvitationCard/InvitationCard.module.css
  frontend/apps/app/components/InvitationPage/components/InvitationCard/InvitationCard.tsx
  frontend/apps/app/components/InvitationPage/components/InvitationCard/actions/acceptInvitation.ts
  frontend/apps/app/components/InvitationPage/components/InvitationCard/index.ts
  frontend/apps/app/components/InvitationPage/index.ts
  frontend/apps/app/components/InvitationPage/services/getInvitationData.ts
  frontend/apps/app/features/invitations/actions/index.ts
Labels: Review effort 2/5

#1650 💄 refactor(UserMessage): update to semantic color variables and remove width constraint
  frontend/apps/app/components/Chat/UserMessage/UserMessage.module.css
Labels: Review effort 1/5

#1588 add: hover to the table column.
  .changeset/angry-colts-move.md
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableColumnList/TableColumn/TableColumn.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableColumnList/TableColumn/TableColumn.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableColumnList/TableColumnList.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableNode.module.css
Labels: Review effort 2/5

#1653 ✨ feat(chat): add AgentMessage component
  frontend/apps/app/components/Chat/AgentMessage/AgentMessage.module.css
  frontend/apps/app/components/Chat/AgentMessage/AgentMessage.stories.tsx
  frontend/apps/app/components/Chat/AgentMessage/AgentMessage.tsx
  frontend/apps/app/components/Chat/AgentMessage/index.ts
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/UserMessage/UserMessage.module.css
  frontend/apps/app/components/Chat/UserMessage/UserMessage.stories.tsx
  frontend/apps/app/components/Chat/UserMessage/UserMessage.tsx
  frontend/apps/app/components/ChatMessage/ChatMessage.module.css
  frontend/apps/app/components/ChatMessage/ChatMessage.tsx
  frontend/apps/app/components/ChatbotButton/components/ChatbotDialog/ChatbotDialog.tsx
  frontend/apps/app/package.json
  frontend/packages/ui/src/index.ts
  frontend/packages/ui/src/styles/globals.css
  frontend/packages/ui/src/styles/index.ts
  frontend/packages/ui/src/styles/syntax-highlight.css
  frontend/packages/ui/src/styles/syntax-theme.ts
  package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1666 ♻️ Refactor Chat Schema Handling and Remove Adaptation Logic
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/components/BuildPage/BuildPage.tsx
  frontend/apps/app/components/BuildPage/Panel/Panel.tsx
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/ChatbotButton/ChatbotButton.tsx
  frontend/apps/app/components/ChatbotButton/components/ChatbotDialog/ChatbotDialog.tsx
  frontend/apps/app/features/chats/services/adaptSchemaForChatbot.ts
  frontend/apps/app/features/chats/services/index.ts
Labels: Review effort 2/5

#1669 ✨ implement schema diff visualization with merge editor
  frontend/apps/app/components/BuildPage/Panel/Panel.tsx
  frontend/apps/app/components/BuildPage/Panel/SchemaEditor/SchemaEditor.tsx
  frontend/apps/app/components/BuildPage/Panel/SchemaEditor/useEditor.tsx
  frontend/apps/app/components/BuildPage/Panel/SchemaEditor/useMergeEditor.tsx
  frontend/apps/app/components/BuildPage/Panel/after.ts
  frontend/apps/app/components/BuildPage/Panel/before.ts
  frontend/apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#1663 ✨ Add MessageOptionButton component for selectable options in chat inteface
  frontend/apps/app/components/Chat/AgentMessage/AgentMessage.stories.tsx
  frontend/apps/app/components/Chat/MessageOptionButton.module.css
  frontend/apps/app/components/Chat/MessageOptionButton.stories.tsx
  frontend/apps/app/components/Chat/MessageOptionButton.tsx
  frontend/apps/app/components/Chat/MessageOptionButtons.tsx
Labels: Review effort 2/5

#1677 ✨ Add ChatInput component with auto-resize and state handling
  frontend/apps/app/components/ChatInput/CancelButton/CancelButton.module.css
  frontend/apps/app/components/ChatInput/CancelButton/CancelButton.stories.tsx
  frontend/apps/app/components/ChatInput/CancelButton/CancelButton.tsx
  frontend/apps/app/components/ChatInput/CancelButton/index.ts
  frontend/apps/app/components/ChatInput/ChatInput.module.css
  frontend/apps/app/components/ChatInput/ChatInput.stories.tsx
  frontend/apps/app/components/ChatInput/ChatInput.tsx
  frontend/apps/app/components/ChatInput/SendButton/SendButton.module.css
  frontend/apps/app/components/ChatInput/SendButton/SendButton.stories.tsx
  frontend/apps/app/components/ChatInput/SendButton/SendButton.tsx
  frontend/apps/app/components/ChatInput/SendButton/index.ts
  frontend/packages/ui/src/icons/index.ts
Labels: Review effort 3/5

#1590 Prisma Parser - Support @@map
  .changeset/breezy-beers-unite.md
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
Labels: Review effort 1/5

#1664 🔧 Remove `langchain` and add `vercel-ai-sdk` & `mastra`
  config/dependency_decisions.yml
  frontend/apps/app/.gitignore
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/instrumentation.ts
  frontend/apps/app/lib/mastra/agents/databaseSchemaAgent.ts
  frontend/apps/app/lib/mastra/index.ts
  frontend/apps/app/libs/langfuse/langfuseHandler.ts
  frontend/apps/app/next.config.ts
  frontend/apps/app/package.json
  frontend/apps/app/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#1699 ✨️ feat(chat): Add ModeToggleSwitch below ChatInput for mode selection
  frontend/apps/app/components/ChatInput/ChatInput.module.css
  frontend/apps/app/components/ChatInput/ChatInput.tsx
  frontend/apps/app/components/ModeToggleSwitch/ModeToggleSwitch.module.css
  frontend/apps/app/components/ModeToggleSwitch/ModeToggleSwitch.stories.tsx
  frontend/apps/app/components/ModeToggleSwitch/ModeToggleSwitch.tsx
Labels: Review effort 2/5

#1670 ✨ add table diff view to BuildPage panel
  .changeset/long-hands-joke.md
  .changeset/sweet-coins-wash.md
  frontend/apps/app/components/BuildPage/Panel/Panel.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/DiffView.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/DiffView.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableItem/TableItem.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableItem/TableItem.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableItem/index.ts
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/index.ts
  frontend/apps/app/components/BuildPage/Panel/TablesList/SingleView/SingleView.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/SingleView/SingleView.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/SingleView/index.ts
  frontend/apps/app/components/BuildPage/Panel/TablesList/TablesList.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/TablesList.tsx
  frontend/apps/app/components/BuildPage/Panel/after.ts
  frontend/packages/db-structure/package.json
  frontend/packages/db-structure/src/diff/buildSchemaDiff.ts
  frontend/packages/db-structure/src/diff/constants.ts
  frontend/packages/db-structure/src/diff/index.ts
  frontend/packages/db-structure/src/diff/tables/__tests__/buildTableCommentDiffItem.test.ts
  frontend/packages/db-structure/src/diff/tables/__tests__/buildTableDiffItem.test.ts
  frontend/packages/db-structure/src/diff/tables/__tests__/buildTableNameDiffItem.test.ts
  frontend/packages/db-structure/src/diff/tables/buildTableCommentDiffItem.ts
  frontend/packages/db-structure/src/diff/tables/buildTableDiffItem.ts
  frontend/packages/db-structure/src/diff/tables/buildTableNameDiffItem.ts
  frontend/packages/db-structure/src/diff/types.ts
  frontend/packages/db-structure/src/diff/utils/__tests__/getChangeStatus.test.ts
  frontend/packages/db-structure/src/diff/utils/getChangeStatus.ts
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db-structure/src/schema/schema.ts
  frontend/packages/ui/package.json
  frontend/packages/ui/src/components/Switch/Switch.tsx
  frontend/packages/ui/src/components/Switch/index.ts
  frontend/packages/ui/src/components/index.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#1705 add: hover css for activated talbe name in left pane
  .changeset/fresh-shirts-vanish.md
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.module.css
  frontend/packages/ui/src/styles/Dark/variables.css
Labels: Review effort 1/5

#1723 🔧 chore: modify complexity threshold of db-structure package
  frontend/packages/db-structure/biome.jsonc
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
Labels: Review effort 1/5

#1722 🔧 chore: modify VSCode settings for Biome
  .vscode/extensions.json
  .vscode/settings.json
Labels: Review effort 1/5

#1701 Add ask agent and build agent personality & classifyQuestion logic
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/lib/mastra/agents/databaseSchemaAgent.ts
  frontend/apps/app/lib/mastra/agents/databaseSchemaAskAgent.ts
  frontend/apps/app/lib/mastra/agents/databaseSchemaBuildAgent.ts
  frontend/apps/app/lib/mastra/agents/index.ts
  frontend/apps/app/lib/mastra/agents/utils/questionClassifier.ts
  frontend/apps/app/lib/mastra/index.ts
Labels: Review effort 2/5

#1720 ✨ add index diffs to BuildPage panel
  .changeset/fast-dancers-talk.md
  .changeset/plenty-toys-wave.md
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/DiffView.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableDiffBlock.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableDiffBlock.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ColumnItem/ColumnItem.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ColumnItem/ColumnItem.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ColumnItem/index.ts
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/Diff.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/IndexItem/IndexItem.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/IndexItem/IndexItem.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/IndexItem/index.ts
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/TableItem.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/TableItem.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/index.ts
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/index.ts
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableItem/TableItem.tsx
  frontend/apps/app/components/BuildPage/Panel/after.ts
  frontend/packages/db-structure/src/diff/buildSchemaDiff.ts
  frontend/packages/db-structure/src/diff/constants.ts
  frontend/packages/db-structure/src/diff/index.ts
  frontend/packages/db-structure/src/diff/indexes/buildIndexColumnsDiffItem.ts
  frontend/packages/db-structure/src/diff/indexes/buildIndexDiffItem.ts
  frontend/packages/db-structure/src/diff/indexes/buildIndexNameDiffItem.ts
  frontend/packages/db-structure/src/diff/indexes/buildIndexTypeDiffItem.ts
  frontend/packages/db-structure/src/diff/indexes/buildIndexUniqueDiffItem.ts
  frontend/packages/db-structure/src/diff/types.ts
  frontend/packages/db-structure/src/diff/utils/getChangeStatus.ts
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db-structure/src/schema/schema.ts
  frontend/packages/ui/package.json
  frontend/packages/ui/src/components/Collapsible/Collapsible.tsx
  frontend/packages/ui/src/components/Collapsible/index.ts
  frontend/packages/ui/src/components/index.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#1730 feat: implement building schema versioning with JSON Patch support
  frontend/apps/app/app/api/buildingSchemas/versions/route.ts
  frontend/apps/app/libs/schema/__tests__/applyPatchOperations.test.ts
  frontend/apps/app/libs/schema/applyPatchOperations.ts
  frontend/apps/app/libs/schema/createNewVersion.ts
  frontend/apps/app/libs/schema/index.ts
  frontend/apps/app/libs/schema/operationsSchema.ts
  frontend/apps/app/package.json
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250520100200_add_schemas_tables.sql
  pnpm-lock.yaml
Labels: Review effort 3/5

#1732 chore: add unique constraint on design_session_id in building_schemas
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250521190001_add_unique_constraint_to_building_schemas.sql
Labels: Review effort 1/5

#1733 feat: add RPC function for transactional schema updates with versioning
  frontend/apps/app/libs/schema/createNewVersion.ts
  frontend/packages/db/schema/schema.sql
  frontend/packages/db/supabase/database.types.ts
  frontend/packages/db/supabase/migrations/20250521190230_add_update_building_schema.sql
  frontend/packages/db/supabase/tests/database/04-update_building_schema.test.sql
Labels: Review effort 3/5

#1750 ♻️ Feature/simple mode switch
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/ProcessIndicator/ProcessIndicator.tsx
  frontend/apps/app/components/ChatInput/ChatInput.tsx
  frontend/apps/app/components/ModeToggleSwitch/ModeToggleSwitch.tsx
  frontend/apps/app/lib/mastra/agents/databaseSchemaAskAgent.ts
  frontend/apps/app/lib/mastra/agents/databaseSchemaBuildAgent.ts
  frontend/apps/app/lib/mastra/agents/index.ts
  frontend/apps/app/lib/mastra/agents/utils/questionClassifier.ts
Labels: Review effort 2/5

#1731 ✨ add constaint diffs to BuildPage panel
  .changeset/swift-hairs-push.md
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableDiffBlock.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ConstraintList/ConstraintItem/CheckConstraintItem.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ConstraintList/ConstraintItem/ConstraintItem.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ConstraintList/ConstraintItem/ForeignConstraintItem.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ConstraintList/ConstraintItem/PrimaryConstraintItem.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ConstraintList/ConstraintItem/UniqueConstraintItem.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ConstraintList/ConstraintItem/getChangeStatusStyle.ts
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ConstraintList/ConstraintItem/index.ts
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ConstraintList/ConstraintList.module.css
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ConstraintList/ConstraintList.tsx
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ConstraintList/index.ts
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/TableItem.tsx
  frontend/apps/app/components/BuildPage/Panel/after.ts
  frontend/packages/db-structure/package.json
  frontend/packages/db-structure/src/diff/buildSchemaDiff.ts
  frontend/packages/db-structure/src/diff/constants.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintColumnNameDiffItem.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintDeleteConstraintDiffItem.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintDetailDiffItem.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintDiffItem.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintNameDiffItem.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintTargetColumnNameDiffItem.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintTargetTableNameDiffItem.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintUpdateConstraintDiffItem.ts
  frontend/packages/db-structure/src/diff/index.ts
  frontend/packages/db-structure/src/diff/types.ts
  frontend/packages/db-structure/src/diff/utils/getChangeStatus.ts
  frontend/packages/db-structure/src/index.ts
  frontend/packages/db-structure/src/schema/index.ts
  frontend/packages/db-structure/src/schema/schema.ts
  frontend/packages/ui/src/components/GridTable/GridTable.tsx
  pnpm-lock.yaml
Labels: Review effort 4/5

#1757 🐛 update default value display logic to handle boolean types
  frontend/apps/app/components/BuildPage/Panel/TablesList/DiffView/TableDiffBlock/TableItem/ColumnItem/ColumnItem.tsx
Labels: Review effort 1/5

#1721 【AI Agent】Add embedding structure
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/app/lib/schema/convertSchemaToText.ts
  frontend/apps/app/app/lib/vectorstore/supabaseVectorStore.ts
  frontend/apps/app/app/lib/vectorstore/syncSchemaVectorStore.ts
  frontend/apps/app/components/BuildPage/BuildPage.tsx
  frontend/apps/app/components/BuildPage/Panel/Panel.tsx
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/ChatbotButton/ChatbotButton.tsx
  frontend/apps/app/components/ChatbotButton/components/ChatbotDialog/ChatbotDialog.tsx
  frontend/apps/app/components/SchemaPage/SchemaPage.tsx
  frontend/apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 4/5

#1700 Feat/Improve table name tooltip behavior to only show on truncated text
  .changeset/great-oranges-heal.md
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableHeader/TableHeader.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableHeader/TableHeader.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableNode.tsx
Labels: Review effort 2/5

#1768 ✅ test: increase timeout for toolbar zoom button tests
  frontend/packages/e2e/tests/e2e/toolbar.test.ts
Labels: Review effort 1/5

#1781 chore: remove outdated changeset files for UI and DB structure updates
  .changeset/fast-dancers-talk.md
  .changeset/long-hands-joke.md
  .changeset/old-ducks-carry.md
  .changeset/plenty-toys-wave.md
  .changeset/sweet-coins-wash.md
  .changeset/swift-hairs-push.md
Labels: Review effort 1/5

#1782 🔧 remove @liam-hq/storybook to dependencies
  .changeset/config.json
Labels: Review effort 1/5

#1801 📝(docs): Add Ruby on Rails community resource and fix MySQL translation link
  frontend/apps/docs/content/docs/community-resources.mdx
Labels: Review effort 1/5

#1823 Revert "Merge pull request #1816 from liam-hq/renovate/fumadocs"
  frontend/apps/docs/package.json
  pnpm-lock.yaml
Labels: Review effort 1/5

#1822 📝 tweak: update CONTRIBUTING.md add storybook url
  CONTRIBUTING.md
Labels: Review effort 1/5

#1803 Implement a new job to analyze connected repositories
  frontend/apps/app/components/ProjectNewPage/components/InstallationSelector/actions/addProject.ts
  frontend/packages/jobs/package.json
  frontend/packages/jobs/src/functions/processRepositoryAnalysis.ts
  frontend/packages/jobs/src/index.ts
  frontend/packages/jobs/src/trigger/jobs.ts
  pnpm-lock.yaml
Labels: Review effort 4/5

#1811 update code to set the default left pane size
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/ERDRenderer.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/LeftPane/LeftPane.module.css
Labels: Review effort 2/5
