Repository liam-hq/liam, pull requests merged in 2025-02, with the labels that each got.

#682 Update pull_request_template.md for PR-Agent
  .github/pull_request_template.md
Labels: Review effort [1-5]: 1

#676 Add Visual Regression Testing
  .github/workflows/vercel-deploy-erd.yml
  frontend/packages/e2e/.gitignore
  frontend/packages/e2e/tests/e2e/page.test.ts
  frontend/packages/e2e/tests/vrt/vrt.test.ts
  frontend/packages/e2e/tests/vrt/vrt.test.ts-snapshots/top-1-chromium-linux.png
Labels: Review effort [1-5]: 2

#680 🎨 Add Mr.Jack svg to NetworkError
  .changeset/fresh-shirts-stare.md
  frontend/apps/erd-web/app/erd/p/[...slug]/erdViewer.tsx
  frontend/apps/erd-web/app/erd/p/[...slug]/page.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay/ErrorDisplay.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay/MrJack.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay/NetworkErrorDisplay.module.css
  frontend/packages/erd-core/src/components/ERDRenderer/ErrorDisplay/NetworkErrorDisplay.tsx
Labels: Review effort [1-5]: 2

#690 ✨ Add touch device detection for ERD selection behavior
  .changeset/real-hairs-reply.md
  frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
  frontend/packages/erd-core/src/utils/index.ts
  frontend/packages/erd-core/src/utils/isTouchDevice.ts
Labels: Review effort [1-5]: 2

#687 ✅ Add test for copy link button functionality
  frontend/packages/e2e/tests/e2e/page.test.ts
Labels: Review effort [1-5]: 1

#686 📚 Add e2e readme
  frontend/packages/e2e/README.md
Labels: Review effort [1-5]: 1

#695 ✅ fix: E2E VRT
  frontend/packages/e2e/tests/vrt/vrt.test.ts
Labels: Review effort [1-5]: 1

#696 🐛 Version bump failed, re-run
  .changeset/brave-timers-drum.md
Labels: Review effort [1-5]: 1

#694 ✅ Add test for table node highlight interaction
  frontend/packages/e2e/tests/e2e/page.test.ts
  frontend/packages/erd-core/src/components/ERDRenderer/convertDBStructureToNodes.ts
Labels: Review effort [1-5]: 1

#697 ✅ Add E2E tests for toolbar zoom controls
  frontend/packages/e2e/tests/e2e/toolbar.test.ts
  frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/DesktopToolbar.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/MobileToolbar/MobileToolbar.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/ZoomControls/ZoomControls.tsx
Labels: Review effort [1-5]: 2

#707 🔧 Add manual workflow dispatch to Vercel deployment workflows
  .github/workflows/vercel-deploy-erd.yml
  .github/workflows/vercel-deploy.yml
Labels: Review effort [1-5]: 1

#703 ✅ Add global setup for cookie acceptance in E2E tests
  frontend/packages/e2e/.gitignore
  frontend/packages/e2e/global-setup.ts
  frontend/packages/e2e/playwright.config.ts
  frontend/packages/e2e/tests/e2e/toolbar.test.ts
  frontend/packages/e2e/tests/vrt/vrt.test.ts
Labels: Review effort [1-5]: 2

#705 ✅ Add E2E tests for Show Mode menu in desktop toolbar
  frontend/packages/e2e/tests/e2e/toolbar.test.ts
  frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/ShowModeMenu/ShowModeMenu.tsx
Labels: Review effort [1-5]: 2

#710 🔨 Trigger package release test workflow after publishing
  .github/workflows/release.yml
  .github/workflows/released_package_test.yml
Labels: Review effort [1-5]: 2

#713 🐛 Fix hydration error in Mobile
  .changeset/olive-bees-visit.md
  frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
  frontend/packages/erd-core/src/hooks/index.ts
  frontend/packages/erd-core/src/hooks/useIsTouchDevice.ts
  frontend/packages/erd-core/src/utils/index.ts
  frontend/packages/erd-core/src/utils/isTouchDevice.ts
Labels: Review effort [1-5]: 2

#715 🐛 fix toolbar flaky tests
  frontend/packages/e2e/tests/e2e/toolbar.test.ts
  frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/Spinner/Spinner.tsx
Labels: Review effort [1-5]: 2

#711 ✅add navigation test
  frontend/packages/e2e/tests/e2e/navigation.test.ts
  frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/VisibilityButton.tsx
  frontend/packages/ui/src/components/Sidebar/Sidebar.tsx
Labels: Review effort [1-5]: 2

#716 🚀 Optimize Playwright browser caching in E2E workflow
  .github/workflows/_run_e2e_test.yml
Labels: Review effort 1/5

#718 ✅ Add E2E tests for edge interactions
  frontend/packages/e2e/tests/e2e/page.test.ts
Labels: Review effort 2/5

#719 ✅ Wait for loading status to be hidden before taking screenshots in VRT
  frontend/packages/e2e/tests/vrt/vrt.test.ts
Labels: Review effort 1/5

#712 ♻️ Refactor tests to support mobile
  .github/workflows/_run_e2e_test.yml
  frontend/packages/e2e/.gitignore
  frontend/packages/e2e/playwright.config.ts
  frontend/packages/e2e/tests/e2e/navigation.test.ts
  frontend/packages/e2e/tests/e2e/page.test.ts
  frontend/packages/e2e/tests/e2e/toolbar.test.ts
  frontend/packages/e2e/tests/vrt/vrt.test.ts-snapshots/top-1-Mobile-Safari-linux.png
Labels: Review effort 2/5

#728 Fix package execution check(🐛 fix outputs name) and slack notification to liam-hq team
  .github/workflows/release.yml
  .github/workflows/released_package_test.yml
Labels: Review effort 2/5

#729 🐛 add step to install WebKit system dependencies
  .github/workflows/_run_e2e_test.yml
Labels: Review effort 1/5

#730 ✅ Add e2e test for fitview button functionality
  frontend/packages/e2e/tests/e2e/toolbar.test.ts
  frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/FitviewButton/FitviewButton.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/MobileToolbar/OpenedMobileToolbar.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/Toolbar/TidyUpButton/TidyUpButton.tsx
Labels: Review effort 2/5

#733 ✅ Enhance E2E navigation tests with table selection and back/forward navigation scenarios
  frontend/packages/e2e/tests/e2e/navigation.test.ts
Labels: Review effort 2/5

#735 ✅ Add E2E test for Tidy Up button functionality in toolbar
  frontend/packages/e2e/tests/e2e/toolbar.test.ts
Labels: Review effort 2/5

#738 tweak: Make #726 patch
  .changeset/expose-reactflow-functions.md
Labels: Review effort 1/5

#739 ✨ Pre-calculate layout for Related Tables before displaying in Main Area
  .changeset/gorgeous-lobsters-complain.md
Labels: Review effort 1/5

#720 🔧 【docs】update turbo json outputs setting
  turbo.json
Labels: Review effort 1/5

#742 ✅ Fix flaky test on node highlighting
  frontend/packages/e2e/tests/e2e/page.test.ts
Labels: Review effort 1/5

#744 【Do not merge】【docs】🔥 Remove Vercel deployment workflow
  .github/workflows/vercel-deploy.yml
Labels: Review effort 1/5

#747 🔨 Add `actions:write` permission to `release.yml`
  .github/workflows/release.yml
Labels: Review effort 1/5

#746 🐛 Exclude hidden and showMode query parameters from ERDContent rendering in RelatedTables
  .changeset/young-owls-relate.md
  frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/RelatedTables/RelatedTables.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/TableNode/TableDetail/TableDetail.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/types.ts
  frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useInitialAutoLayout.ts
  frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/useTableSelection/useTableSelection.ts
  frontend/packages/erd-core/src/components/ERDRenderer/ERDRenderer.tsx
  frontend/packages/erd-core/src/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx
Labels: Review effort 2/5

#731 🔧 chore playwright settings
  frontend/packages/e2e/biome.jsonc
  frontend/packages/e2e/package.json
  frontend/packages/e2e/playwright.config.ts
  frontend/packages/e2e/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#732 🔧 Fix tag commit retrieval by adding a separator to the git command
  frontend/packages/cli/vite-plugins/set-env.ts
Labels: Review effort 2/5

#750 【erd-sample】Remove `erd-sample` from Vercel deployment workflow
  .github/workflows/vercel-deploy-erd.yml
Labels: Review effort 1/5

#754 🐛 Fix file operations to support Windows compatibility
  .changeset/dry-crews-whisper.md
  frontend/packages/cli/src/cli/erdCommand/buildCommand/index.ts
Labels: Review effort 2/5

#757 Update liam erd logo
  README.md
  assets/logo-dark.png
  assets/logo-light.png
  frontend/apps/docs/components/LiamLogo/LiamLogo.tsx
Labels: Review effort 2/5

#760 ✨ Add format detection to CLI build command
  .changeset/twenty-swans-sin.md
  frontend/packages/cli/src/cli/erdCommand/buildCommand/index.ts
  frontend/packages/cli/src/cli/erdCommand/runPreprocess.ts
Labels: Review effort 2/5

#766 feat: Add dark mode support to ERDContent
  frontend/packages/erd-core/src/components/ERDRenderer/ERDContent/ERDContent.tsx
Labels: Review effort 1/5

#761 Add permissions to Dependency Review workflow
  .github/workflows/dependency_review.yml
Labels: Review effort 1/5

#770 📝 add troubleshooting pages
  frontend/apps/docs/content/docs/parser/meta.json
  frontend/apps/docs/content/docs/parser/troubleshooting.mdx
  frontend/apps/docs/content/docs/web/index.mdx
  frontend/apps/docs/content/docs/web/meta.json
  frontend/apps/docs/content/docs/web/troubleshooting.mdx
Labels: Review effort 2/5

#767 ✨ Support field name mapping with @map in Prisma
  .changeset/gold-lions-clean.md
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
Labels: Review effort 2/5

#782 Revert "Fix: Rollup error in initCommand/index.ts"
  frontend/packages/cli/src/cli/initCommand/index.ts
Labels: Review effort 1/5

#788 Update project name to "Liam ERD" in README and components
  README.md
  frontend/apps/docs/components/LiamLogo/LiamLogo.tsx
  frontend/packages/ui/src/components/CookieConsent/CookieConsent.tsx
Labels: Review effort 1/5

#792 feat(table-menu): add tooltip for truncated table names
  .changeset/afraid-forks-report.md
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/LeftPane/TableNameMenuButton/TableNameMenuButton.tsx
Labels: Review effort 2/5
