Repository liam-hq/liam, pull requests merged in 2025-07, with the labels that each got.

#2235 feat: support Rails inline index syntax in schema.rb parser
  .changeset/rails-inline-index-support.md
  frontend/packages/db-structure/src/parser/schemarb/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
Labels: Review effort 3/5

#2310 💄 style(command palette): set border-radius to preview background wrapper
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.module.css
Labels: Review effort 1/5

#2309 💄 style(command palette): fix list item text styles
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.tsx
Labels: Review effort 2/5

#2308 🔥 Remove some slow tests
  frontend/packages/cli/src/cli/smoke.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
  frontend/packages/db-structure/src/parser/types.ts
Labels: Review effort 2/5

#2331 ✨ feat: add RemoveButton component to UI library
  frontend/packages/ui/src/components/Code/Code.module.css
  frontend/packages/ui/src/components/RemoveButton/RemoveButton.module.css
  frontend/packages/ui/src/components/RemoveButton/RemoveButton.tsx
  frontend/packages/ui/src/components/RemoveButton/index.ts
  frontend/packages/ui/src/components/index.ts
Labels: Review effort 2/5

#2335 ✅ add unit tests for convertSchemaToNodes function
  frontend/packages/db-structure/src/index.ts
  frontend/packages/erd-core/src/features/erd/utils/convertSchemaToNodes.test.ts
Labels: Review effort 2/5

#2305 📝(test): Add test principles documentation and Claude test commands
  .claude/commands/check-test-coverage.md
  .claude/commands/implement-regression-tests.md
  .claude/commands/plan-regression-tests.md
  docs/test-principles.md
Labels: Review effort 2/5

#2342 ✨ feat: update allowed tools in Claude workflow
  .github/workflows/claude.yml
Labels: Review effort 2/5, Possible security concern

#2336 Address PR #2263 review feedback
  frontend/internal-packages/schema-bench/src/cli/evaluate-schema.ts
  frontend/internal-packages/schema-bench/src/cli/setup-workspace.ts
  frontend/internal-packages/schema-bench/src/shared/formatError.ts
  frontend/internal-packages/schema-bench/src/workspace/evaluation/evaluation.ts
Labels: Review effort 3/5

#2351 feat: enable Biome useDateNow rule
  frontend/internal-packages/configs/biome.jsonc
  frontend/packages/erd-core/src/features/erd/components/ERDContent/ERDContent.tsx
Labels: Review effort 2/5

#2229 【PoC】Implement artifact and real-time display system
  .changeset/config.json
  frontend/apps/app/components/SessionDetailPage/SessionDetailPageClient.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/Output.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Artifact/ArtifactContainer.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Artifact/hooks/useRealtimeArtifact.ts
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Artifact/index.ts
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Artifact/utils/formatArtifactToMarkdown.ts
  frontend/apps/app/components/SessionDetailPage/mock.ts
  frontend/apps/app/package.json
  frontend/internal-packages/agent/package.json
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalizeArtifactsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/utils/transformWorkflowStateToArtifact.ts
  frontend/internal-packages/agent/src/chat/workflow/workflow.test.ts
  frontend/internal-packages/agent/src/langchain/agents/qaGenerateUsecaseAgent/agent.ts
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/agent/src/repositories/types.ts
  frontend/internal-packages/artifact/biome.jsonc
  frontend/internal-packages/artifact/package.json
  frontend/internal-packages/artifact/src/index.ts
  frontend/internal-packages/artifact/src/schemas/artifact.ts
  frontend/internal-packages/artifact/tsconfig.json
  frontend/internal-packages/db/schema/schema.sql
  frontend/internal-packages/db/src/types/supabase-overrides/artifacts.ts
  frontend/internal-packages/db/src/types/supabase-overrides/index.ts
  frontend/internal-packages/db/supabase/database.types.ts
  frontend/internal-packages/db/supabase/migrations/20250626114915_add_artifacts_table.sql
  pnpm-lock.yaml
Labels: Review effort 4/5

#2338 🔒 refactor: move user authentication to server-side for chat API
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/components/Chat/Chat.tsx
  frontend/apps/app/components/Chat/hooks/useRealtimeTimelineItems.ts
  frontend/apps/app/components/Chat/services/aiMessageService.ts
  frontend/apps/app/components/Chat/services/timelineItemServiceClient.ts
Labels: Review effort 3/5

#2359 📝 Add CSS variable usage guidelines and claude rule command
  .claude/commands/add-claude-rule.md
  CLAUDE.md
Labels: Review effort 2/5

#2355 ✨ feat(cli): add Oh-My-Logo like Logo banner to `init`
  .changeset/bright-banner-glow.md
  frontend/packages/cli/package.json
  frontend/packages/cli/rollup.config.js
  frontend/packages/cli/src/cli/banner.ts
  frontend/packages/cli/src/cli/initCommand/index.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#2368 📝 Add gitmoji usage guideline and reference table to commit instructions
  .claude/commands/commit.md
Labels: Review effort 2/5

#2367 🎨 Remove unnecessary min-height from ProcessIndicator components
  frontend/apps/app/components/Chat/ProcessIndicator/ProcessIndicator.module.css
  frontend/apps/app/components/Chat/ProcessIndicator/ProcessIndicator.tsx
Labels: Review effort 2/5

#2389 💬 fix(command palette): option group title
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.tsx
Labels: Review effort 1/5

#2362 ✅ Add comprehensive test coverage for icon components
  frontend/packages/ui/src/icons/__tests__/CardinalityZeroOrManyLeftIcon.test.tsx
  frontend/packages/ui/src/icons/__tests__/CardinalityZeroOrOneLeftIcon.test.tsx
  frontend/packages/ui/src/icons/__tests__/CardinalityZeroOrOneRightIcon.test.tsx
  frontend/packages/ui/src/icons/__tests__/DiamondFillIcon.test.tsx
  frontend/packages/ui/src/icons/__tests__/DiamondIcon.test.tsx
  frontend/packages/ui/src/icons/__tests__/ErdIcon.test.tsx
  frontend/packages/ui/src/icons/__tests__/FacebookIcon.test.tsx
  frontend/packages/ui/src/icons/__tests__/GotoIcon.test.tsx
  frontend/packages/ui/src/icons/__tests__/InfoIcon.test.tsx
Labels: Review effort 2/5

#2332 ♻️ refactor: reorganize Upload form with improved architecture
  frontend/apps/app/features/sessions/components/SessionForm/AttachmentsContainer/AttachmentsContainer.tsx
  frontend/apps/app/features/sessions/components/SessionForm/FormatSelectDropdown/FormatSelectDropdown.module.css
  frontend/apps/app/features/sessions/components/SessionForm/FormatSelectDropdown/FormatSelectDropdown.tsx
  frontend/apps/app/features/sessions/components/SessionForm/SchemaInfoSection/SchemaInfoSection.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/DropZone.module.css
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/SchemaFileSection.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/UploadSessionFormPresenter.module.css
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/UploadSessionFormPresenter.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/utils/fileValidation.ts
  frontend/apps/app/features/sessions/components/SessionForm/hooks/useFileAttachments.ts
  frontend/apps/app/features/sessions/components/SessionForm/utils/urlValidation.ts
Labels: Review effort 4/5

#2399 Improve serve command example
  .changeset/puny-falcons-cough.md
  frontend/apps/docs/content/docs/cli/ci-cd.mdx
  frontend/apps/docs/content/docs/cli/index.mdx
  frontend/packages/cli/src/cli/erdCommand/buildCommand/index.ts
  frontend/packages/cli/src/cli/initCommand/index.ts
  frontend/packages/cli/vite.config.ts
Labels: Review effort 2/5

#2360 feat: add LangSmith tracing support to @liam-hq/agent package
  .env.template
  frontend/internal-packages/agent/package.json
  knip.jsonc
  pnpm-lock.yaml
Labels: Review effort 2/5

#2405 📝 Update Claude command documentation
  .claude/commands/commit.md
  .claude/commands/create-pull-request.md
Labels: Review effort 1/5

#2387 ✨ feat(command palette): support ⌘ + click to open selected table in new tab
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.module.css
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.test.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.tsx
Labels: Review effort 3/5

#2299 [🧪 Experimental] Add Drizzle ORM schema parser support
  .changeset/four-sheep-drum.md
  frontend/apps/app/next.config.ts
  frontend/apps/app/package.json
  frontend/packages/cli/package.json
  frontend/packages/cli/rollup.config.js
  frontend/packages/cli/src/cli/erdCommand/runPreprocess.test.ts
  frontend/packages/cli/src/cli/index.test.ts
  frontend/packages/cli/src/cli/initCommand/index.ts
  frontend/packages/db-structure/package.json
  frontend/packages/db-structure/src/parser/drizzle/astUtils.ts
  frontend/packages/db-structure/src/parser/drizzle/columnParser.ts
  frontend/packages/db-structure/src/parser/drizzle/convertToPgType.ts
  frontend/packages/db-structure/src/parser/drizzle/converter.ts
  frontend/packages/db-structure/src/parser/drizzle/enumParser.ts
  frontend/packages/db-structure/src/parser/drizzle/expressionParser.ts
  frontend/packages/db-structure/src/parser/drizzle/index.test.ts
  frontend/packages/db-structure/src/parser/drizzle/index.ts
  frontend/packages/db-structure/src/parser/drizzle/mainParser.ts
  frontend/packages/db-structure/src/parser/drizzle/tableParser.ts
  frontend/packages/db-structure/src/parser/drizzle/types.ts
  frontend/packages/db-structure/src/parser/index.ts
  frontend/packages/db-structure/src/parser/supportedFormat/detectFormat.ts
  frontend/packages/db-structure/src/parser/supportedFormat/schema.ts
  knip.jsonc
  pnpm-lock.yaml
Labels: Review effort 4/5

#2422 ♻️ Refactor storybook types and chat components directory structure
  frontend/apps/app/components/SessionDetailPage/components/Chat/NewSessionButton/NewSessionButton.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/ThreadListButton/ThreadListButton.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/ChatInput/ChatInput.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/ChatInput/components/CancelButton/CancelButton.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/ChatInput/components/MentionSuggestor/MentionSuggestor.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/ChatInput/components/SendButton/SendButton.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/AgentMessage.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/AgentAvatar/BuildAgent.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/MessageOptionButtons/MessageOptionButton.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/MessageOptionButtons/MessageOptionButton.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/MessageOptionButtons/MessageOptionButtons.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/ProcessIndicator/ProcessIndicator.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/ProcessIndicator/ProcessIndicator.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/ProcessIndicator/ProcessIndicatorAnimation.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/UserMessage/UserMessage.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/UserMessage/UserMessage.tsx
  frontend/apps/app/features/sessions/components/SessionForm/ActionButton/ActionButton.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/AttachButton/AttachButton.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/DeepModelingToggle/DeepModelingToggle.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/GitHubSessionFormPresenter/GitHubSessionFormPresenter.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/MicButton/MicButton.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/SchemaInfoSection/SchemaInfoSection.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/SessionFormActions/SessionFormActions.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/SessionFormPresenter.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/SessionModeSelector/SessionModeSelector.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/URLSessionFormPresenter/UrlSessionFormPresenter.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/UploadSessionFormPresenter.stories.tsx
  frontend/apps/app/features/sessions/components/SessionForm/ViewErrorsCollapsible/ViewErrorsCollapsible.stories.tsx
  frontend/apps/app/types/storybook.d.ts
  frontend/internal-packages/storybook/.storybook/main.ts
  frontend/packages/ui/src/components/ArrowTooltip/ArrowTooltip.stories.tsx
  frontend/packages/ui/src/components/Button/Button.stories.tsx
  frontend/packages/ui/src/components/Code/Code.stories.tsx
  frontend/packages/ui/src/components/IconButton/IconButton.stories.tsx
  frontend/packages/ui/src/components/Tooltip/Tooltip.stories.tsx
Labels: Review effort 3/5

#2425 feat: implement DDL execution retry mechanism
  frontend/internal-packages/agent/src/chat/workflow/constants.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.retry.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/executeDdlNode.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/deepModeling.ts
Labels: Review effort 3/5

#2421 improve: unify constraint definitions to use `columnNames` array
  .changeset/dirty-ends-mix.md
  frontend/internal-packages/agent/src/deepModeling.test.ts
  frontend/internal-packages/schema-bench/src/evaluate/evaluate.test.ts
  frontend/internal-packages/schema-bench/src/evaluate/evaluate.ts
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/schemaDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintColumnNameDiffItem.ts
  frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
  frontend/packages/db-structure/src/parser/__tests__/testcase.ts
  frontend/packages/db-structure/src/parser/drizzle/converter.ts
  frontend/packages/db-structure/src/parser/drizzle/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
  frontend/packages/db-structure/src/parser/schemarb/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/parser.ts
  frontend/packages/db-structure/src/schema/factories.ts
  frontend/packages/db-structure/src/schema/mergeSchema.test.ts
  frontend/packages/db-structure/src/schema/schema.ts
  frontend/packages/db-structure/src/utils/constraintsToRelationships.test.ts
  frontend/packages/db-structure/src/utils/constraintsToRelationships.ts
  frontend/packages/db-structure/src/utils/isPrimaryKey.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Constraints/PrimaryKeyConstraintsItem/PrimaryKeyConstraintsItem.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Constraints/Unique/UniqueConstraintsItem.tsx
  frontend/packages/erd-core/src/features/erd/utils/convertSchemaToNodes.test.ts
Labels: Review effort 4/5

#2427 ♻️ Refactor TimelineItem component structure and styling
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/TimelineItem.module.css
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/TimelineItem.tsx
Labels: Review effort 2/5

#2407 ✨ Add scroll to bottom functionality and fix VersionMessage layout shift
  frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/VersionMessage/VersionMessage.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/useScrollToBottom.ts
Labels: Review effort 3/5

#2455 🐛 fix (command palette): modify href to retains the current search params
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPalette.tsx
Labels: Review effort 2/5

#2454 feat: add split-pr command for managing large pull requests
  .claude/commands/split-pr.md
Labels: Review effort 2/5

#2444 🔧 feat: Add support for multiple PostgreSQL schemas in Drizzle parser with proper FK resolution
  .changeset/cruel-cats-decide.md
  frontend/packages/db-structure/src/parser/drizzle/astUtils.ts
  frontend/packages/db-structure/src/parser/drizzle/converter.ts
  frontend/packages/db-structure/src/parser/drizzle/index.test.ts
  frontend/packages/db-structure/src/parser/drizzle/mainParser.ts
  frontend/packages/db-structure/src/parser/drizzle/tableParser.ts
Labels: Review effort 4/5

#2453 ✨ Add assistant logging to workflow nodes
  CLAUDE.md
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/TimelineItem.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/AgentMessage.module.css
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/LogMessage.module.css
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/LogMessage.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/LogMessage.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/index.ts
  frontend/apps/app/features/timelineItems/services/timelineItemServiceClient.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/analyzeRequirementsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.integration.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.retry.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/executeDdlNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalizeArtifactsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/generateUsecaseNode.ts
  frontend/internal-packages/agent/src/chat/workflow/utils/timelineLogger.ts
  frontend/internal-packages/agent/src/repositories/types.ts
  frontend/internal-packages/db/schema/schema.sql
  frontend/internal-packages/db/supabase/database.types.ts
  frontend/internal-packages/db/supabase/migrations/20250709074727_add_assistant_log_to_timeline_item_type.sql
Labels: Review effort 3/5

#2452 ♿ Improve focus styles for session form components
  frontend/apps/app/features/sessions/components/SessionForm/ActionButton/ActionButton.module.css
  frontend/apps/app/features/sessions/components/SessionForm/AttachButton/AttachButton.module.css
  frontend/apps/app/features/sessions/components/SessionForm/AttachmentsContainer/AttachmentsContainer.module.css
  frontend/apps/app/features/sessions/components/SessionForm/AttachmentsContainer/AttachmentsContainer.tsx
  frontend/apps/app/features/sessions/components/SessionForm/BranchesDropdown/BranchesDropdown.module.css
  frontend/apps/app/features/sessions/components/SessionForm/DeepModelingToggle/DeepModelingToggle.module.css
  frontend/apps/app/features/sessions/components/SessionForm/FormatSelectDropdown/FormatSelectDropdown.module.css
  frontend/apps/app/features/sessions/components/SessionForm/MicButton/MicButton.module.css
  frontend/apps/app/features/sessions/components/SessionForm/ProjectsDropdown/ProjectsDropdown.module.css
  frontend/apps/app/features/sessions/components/SessionForm/SessionFormPresenter.module.css
  frontend/apps/app/features/sessions/components/SessionForm/SessionFormPresenter.tsx
  frontend/apps/app/features/sessions/components/SessionForm/SessionModeSelector/SessionModeSelector.module.css
  frontend/apps/app/features/sessions/components/SessionForm/SessionModeSelector/SessionModeSelector.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/DropZone.module.css
  frontend/packages/ui/src/components/Button/Button.module.css
  frontend/packages/ui/src/components/RemoveButton/RemoveButton.module.css
Labels: Review effort 3/5

#2361 Add automated PR creation workflows with Claude AI integration
  .github/workflows/claude-pr-creator.yml
  .github/workflows/process-scheduled-issues.yml
Labels: Review effort 4/5, Possible security concern

#2423 refactor: Migrate agent workflow to LangGraphJS configurable pattern
  frontend/internal-packages/agent/src/chat/workflow/nodes/analyzeRequirementsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.integration.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.retry.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/executeDdlNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalizeArtifactsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/generateUsecaseNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/prepareDmlNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/reviewDeliverablesNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/saveUserMessageNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/validateSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/getConfigurable.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/chat/workflow/utils/transformWorkflowStateToArtifact.ts
  frontend/internal-packages/agent/src/deepModeling.test.ts
  frontend/internal-packages/agent/src/deepModeling.ts
  frontend/internal-packages/jobs/src/trigger/deepModelingWorkflowTask.ts
Labels: Review effort 4/5

#2476 🔧 Add permission denial for schema.sql file editing
  .claude/settings.json
  CLAUDE.md
Labels: Review effort 2/5

#2477 🔧 Fix ESLint consistent-type-assertions rule to prohibit all type assertions
  .cursorrules
  CLAUDE.md
  frontend/apps/app/eslint-suppressions.json
  frontend/internal-packages/agent/eslint-suppressions.json
  frontend/internal-packages/configs/eslint/base.js
  frontend/internal-packages/e2e/eslint-suppressions.json
  frontend/internal-packages/jobs/eslint-suppressions.json
  frontend/internal-packages/schema-bench/eslint-suppressions.json
  frontend/packages/db-structure/eslint-suppressions.json
  frontend/packages/erd-core/eslint-suppressions.json
Labels: Review effort 2/5

#2467 feat: add DML Generation Agent basic structure
  frontend/internal-packages/agent/src/langchain/agents/dmlGenerationAgent/agent.test.ts
  frontend/internal-packages/agent/src/langchain/agents/dmlGenerationAgent/agent.ts
Labels: Review effort 2/5

#2487 feat: add command to update PR descriptions to match project template
  .claude/commands/update-pr-description.md
Labels: Review effort 2/5

#2493 🔧 Fix: Add missing pnpm setup step to Claude PR creator workflow
  .github/workflows/claude-pr-creator.yml
Labels: Review effort 1/5

#2469 feat: add workflow state for DML
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
Labels: Review effort 1/5

#2474 feat: add prepareDmlNode input validation and logging
  frontend/internal-packages/agent/src/chat/workflow/nodes/prepareDmlNode.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/prepareDmlNode.ts
Labels: Review effort 2/5

#2501 🔧 Improve trigger.dev cleanup workflow robustness
  .github/workflows/trigger_dev_preview_cleanup.yml
Labels: Review effort 2/5

#2475 PR 6: Add prepareDmlNode Use Case Formatting
  frontend/internal-packages/agent/src/chat/workflow/nodes/prepareDmlNode.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/prepareDmlNode.ts
Labels: Review effort 3/5

#2507 feat: Add Enter key submission to SessionForm components with improved form reference
  frontend/apps/app/features/sessions/components/SessionForm/GitHubSessionFormPresenter/GitHubSessionFormPresenter.tsx
  frontend/apps/app/features/sessions/components/SessionForm/URLSessionFormPresenter/UrlSessionFormPresenter.tsx
  frontend/apps/app/features/sessions/components/SessionForm/UploadSessionFormPresenter/UploadSessionFormPresenter.tsx
  frontend/apps/app/features/sessions/components/SessionForm/hooks/useEnterKeySubmission.ts
Labels: Review effort 2/5

#2509 ♻️ Refactor SessionDetailPage to simplify data fetching and improve component organization
  frontend/apps/app/app/(app)/app/design_sessions/[id]/page.tsx
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.tsx
  frontend/apps/app/components/SessionDetailPage/SessionDetailPageClient.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/services/aiMessageService.ts
  frontend/apps/app/components/SessionDetailPage/services/designSessionWithTimelineItems/fetchDesignSessionWithTimelineItems.ts
  frontend/apps/app/components/SessionDetailPage/services/designSessionWithTimelineItems/server/getDesignSessionWithTimelineItems.ts
  frontend/apps/app/components/SessionDetailPage/services/designSessionWithTimelineItems/types.ts
  frontend/apps/app/eslint-suppressions.json
  frontend/apps/app/features/timelineItems/hooks/useRealtimeTimelineItems.ts
  frontend/apps/app/features/timelineItems/services/timelineItemServiceClient.ts
  frontend/apps/app/features/timelineItems/types.ts
  frontend/apps/app/utils/agentSupabaseHelper.ts
Labels: Review effort 4/5

#2517 🔧 Update CodeRabbit configuration to disable high-level summaries
  .coderabbit.yaml
Labels: Review effort 1/5

#2483 PR 8: Update validateSchemaNode to Accept DML
  frontend/internal-packages/agent/src/chat/workflow/nodes/prepareDmlNode.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/validateSchemaNode.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/validateSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
Labels: Review effort 3/5, Possible security concern

#2485 PR 9: Add Combined DDL/DML Execution
  frontend/internal-packages/agent/src/chat/workflow/nodes/validateSchemaNode.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/validateSchemaNode.ts
Labels: Review effort 3/5

#2520 ♻️ Refactor database schema design workflow to use function agents and messages
  frontend/internal-packages/agent/eslint-suppressions.json
  frontend/internal-packages/agent/src/chat/workflow/nodes/analyzeRequirementsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.integration.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.retry.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/generateUsecaseNode.ts
  frontend/internal-packages/agent/src/deepModeling.test.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/agent.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/index.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/prompts.ts
  frontend/internal-packages/agent/src/langchain/agents/index.ts
  frontend/internal-packages/agent/src/langchain/utils/types.ts
Labels: Review effort 4/5

#2529 ♻️ Refactor SessionDetailPage components based on CodeRabbit feedback
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeTimelineItems/useRealtimeTimelineItems.ts
  frontend/apps/app/components/SessionDetailPage/schema.ts
  frontend/apps/app/components/SessionDetailPage/services/convertTimelineItemToTimelineItemEntry.ts
  frontend/apps/app/components/SessionDetailPage/services/designSessionWithTimelineItems/fetchDesignSessionWithTimelineItems.ts
Labels: Review effort 2/5

#2555 fix: correct field name mismatch in design agent response schema
  frontend/internal-packages/agent/src/deepModeling.test.ts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/prompts.ts
Labels: Review effort 2/5

#2556 ♻️ Refactor: reorganize drizzle parser for multi-database support
  .changeset/kind-zebras-divide.md
  frontend/packages/db-structure/biome.jsonc
  frontend/packages/db-structure/src/parser/drizzle/index.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/__tests__/index.test.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/astUtils.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/columnParser.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/convertToPgType.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/converter.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/enumParser.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/expressionParser.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/index.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/mainParser.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/tableParser.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/types.ts
  frontend/packages/db-structure/tsconfig.json
  frontend/packages/db-structure/vitest.config.ts
Labels: Review effort 3/5

#2533 💄 style(command palette): set border-radius of option
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPaletteContent/CommandPaletteContent.module.css
Labels: Review effort 1/5

#2562 fix: remove non-existent 'primary' property references from database schema prompts
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/prompts.ts
Labels: Review effort 2/5

#2558 PR1: fix: improve design agent prompt to prevent invalid JSON patch operations
  frontend/internal-packages/agent/src/langchain/agents/databaseSchemaBuildAgent/prompts.ts
Labels: Review effort 2/5

#2567 ♻️ Refactor to fetch data on API call instead of passing from props
  frontend/apps/app/app/api/chat/route.ts
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.tsx
  frontend/apps/app/components/SessionDetailPage/SessionDetailPageClient.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/services/__tests__/timelineItemHelpers.test.ts
  frontend/apps/app/components/SessionDetailPage/components/Chat/services/aiMessageService.ts
  frontend/apps/app/components/SessionDetailPage/components/Chat/services/timelineItemHelpers.ts
  frontend/internal-packages/jobs/src/index.ts
  frontend/internal-packages/jobs/src/trigger/deepModelingWorkflowTask.ts
Labels: Review effort 4/5

#2527 Composite fk
  .changeset/mighty-dragons-explain.md
  frontend/internal-packages/schema-bench/src/evaluate/evaluate.test.ts
  frontend/internal-packages/schema-bench/src/evaluate/evaluate.ts
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/schemaDeparser.test.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintColumnNameDiffItem.ts
  frontend/packages/db-structure/src/diff/constraints/buildConstraintTargetColumnNameDiffItem.ts
  frontend/packages/db-structure/src/parser/__snapshots__/index.test.ts.snap
  frontend/packages/db-structure/src/parser/drizzle/postgres/__tests__/index.test.ts
  frontend/packages/db-structure/src/parser/drizzle/postgres/converter.ts
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/prisma/parser.ts
  frontend/packages/db-structure/src/parser/schemarb/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/index.test.ts
  frontend/packages/db-structure/src/parser/tbls/parser.ts
  frontend/packages/db-structure/src/schema/factories.ts
  frontend/packages/db-structure/src/schema/schema.ts
  frontend/packages/db-structure/src/utils/constraintsToRelationships.test.ts
  frontend/packages/db-structure/src/utils/constraintsToRelationships.ts
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/Constraints/ForeignKeyConstraintsItem/ForeignKeyConstraintsItem.tsx
  frontend/packages/erd-core/src/features/erd/components/ERDContent/components/TableNode/TableDetail/extractSchemaForTable.test.ts
  frontend/packages/erd-core/src/features/erd/utils/convertSchemaToNodes.test.ts
Labels: Review effort 4/5

#2559 PR2: fix: prevent OPERATION_PATH_UNRESOLVABLE errors in JSON patch operations
  frontend/internal-packages/agent/eslint-suppressions.json
  frontend/internal-packages/agent/src/repositories/supabase.test.ts
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/agent/src/utils/pathPreparation.ts
Labels: Review effort 4/5, Possible security concern

#2576 ♻️ Rename createEmptyVersion to createEmptyPatchVersion
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.integration.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.retry.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/prepareDmlNode.test.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/validateSchemaNode.test.ts
  frontend/internal-packages/agent/src/deepModeling.test.ts
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/agent/src/repositories/types.ts
Labels: Review effort 2/5

#2569 feat: Implement automated lint and format checks for Claude Code Actions
  .github/scripts/setup-claude.sh
  .github/workflows/claude-pr-creator.yml
  .github/workflows/claude.yml
Labels: Review effort 2/5, Possible security concern

#2489 Test/upgrade react flow version
  frontend/internal-packages/e2e/playwright.config.ts
  frontend/internal-packages/e2e/tests/e2e/toolbar.test.ts
  frontend/internal-packages/e2e/tests/vrt/vrt.test.ts-snapshots/top-1-Mobile-Safari-linux.png
  frontend/internal-packages/e2e/tests/vrt/vrt.test.ts-snapshots/top-1-chromium-linux.png
  frontend/packages/erd-core/package.json
  frontend/packages/erd-core/src/features/erd/components/ERDContent/hooks/useInitialAutoLayout.ts
  frontend/packages/erd-core/src/features/erd/components/ERDRenderer/CommandPalette/CommandPaletteContent/CommandPaletteContent.tsx
  frontend/packages/erd-core/src/features/reactflow/hooks/useCustomReactflow.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#2588 ✨ Improve workflow loading state management and integrate version selection
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.tsx
  frontend/apps/app/components/SessionDetailPage/SessionDetailPageClient.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/Output.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/Header.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/VersionDropdown/VersionDropdown.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/VersionDropdown/hooks/useRealtimeVersions.ts
  frontend/apps/app/components/SessionDetailPage/components/Output/components/Header/VersionDropdown/services/getSchemaVersions.ts
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeBuildlingSchema.ts
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeVersionsWithSchema/index.ts
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeVersionsWithSchema/services/buildCurrentSchema.ts
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeVersionsWithSchema/services/buildPrevSchema.ts
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeVersionsWithSchema/useRealtimeVersionsWithSchema.ts
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeWorkflowRuns.ts
  frontend/apps/app/components/SessionDetailPage/services/buildPrevSchema/client/buildPrevSchema.ts
  frontend/apps/app/components/SessionDetailPage/services/buildingSchema/client/getBuldingSchema.ts
  frontend/apps/app/components/SessionDetailPage/services/getVersions.ts
  frontend/apps/app/components/SessionDetailPage/services/latestVersion/client/getLatestVersion.ts
  frontend/apps/app/components/SessionDetailPage/services/latestVersion/fetchLatestVersion.ts
  frontend/apps/app/components/SessionDetailPage/services/latestVersion/server/getLatestVersion.ts
  frontend/apps/app/components/SessionDetailPage/types.ts
  frontend/apps/app/eslint-suppressions.json
  frontend/internal-packages/agent/src/deepModeling.ts
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/agent/src/repositories/types.ts
  frontend/internal-packages/db/package.json
  frontend/internal-packages/db/schema/schema.sql
  frontend/internal-packages/db/src/index.ts
  frontend/internal-packages/db/src/schema.ts
  frontend/internal-packages/db/supabase/migrations/20250716101316_enable_realtime_for_building_schema_versions.sql
  pnpm-lock.yaml
Labels: Review effort 4/5

#2284 📝 Add changeset creation guide and update ignore list
  .changeset/config.json
  CONTRIBUTING.md
  docs/changeset-guide.md
Labels: Review effort 2/5

#2598 🎨 Refactor timeline items to use unified type system with role-based agents
  frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/TimelineItem.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/ErrorMessage/ErrorMessageContent.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/ErrorMessage/index.ts
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/VersionMessage/VersionMessage.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/utils/timelineUtils.ts
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeTimelineItems/utils/__tests__/isDuplicateTimelineItem.test.ts
  frontend/apps/app/components/SessionDetailPage/services/convertTimelineItemToTimelineItemEntry.ts
  frontend/apps/app/components/SessionDetailPage/types.ts
Labels: Review effort 4/5

#2568 Implement agent progress design with dynamic timeline animations
  frontend/apps/app/components/MarkdownContent/MarkdownContent.module.css
  frontend/apps/app/components/MarkdownContent/MarkdownContent.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/AnimationControls.module.css
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/AnimationControls.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/TimelineItem.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/AgentMessage.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/AgentAvatar/AgentAvatars.stories.module.css
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/AgentAvatar/AgentAvatars.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/AgentAvatar/BuildAgent.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/AgentAvatar/DbAgent.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/AgentAvatar/PmAgent.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/AgentAvatar/QaAgent.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/components/AgentAvatar/index.ts
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/ErrorMessage/ErrorMessage.module.css
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/ErrorMessage/ErrorMessage.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/ErrorMessage/index.ts
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/LogMessage.module.css
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/LogMessage.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/constants/animationConstants.ts
  frontend/apps/app/components/SessionDetailPage/components/Chat/hooks/useAnimationState.ts
  frontend/apps/app/components/SessionDetailPage/components/Chat/utils/animationUtils.ts
  frontend/apps/app/components/SessionDetailPage/components/Chat/utils/timelineUtils.ts
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeTimelineItems/utils/__tests__/isDuplicateTimelineItem.test.ts
  frontend/apps/app/components/SessionDetailPage/services/convertTimelineItemToTimelineItemEntry.ts
  frontend/apps/app/components/SessionDetailPage/types.ts
  frontend/internal-packages/storybook/.storybook/main.ts
Labels: Review effort 4/5

#2580 feat: add OpenAI executor to schema-bench
  frontend/internal-packages/schema-bench/package.json
  frontend/internal-packages/schema-bench/src/cli/evaluateSchema.ts
  frontend/internal-packages/schema-bench/src/cli/executeOpenai.ts
  frontend/internal-packages/schema-bench/src/cli/setupWorkspace.ts
  frontend/internal-packages/schema-bench/src/cli/utils/error.ts
  frontend/internal-packages/schema-bench/src/cli/utils/index.ts
  frontend/internal-packages/schema-bench/src/cli/utils/workspace.ts
  frontend/internal-packages/schema-bench/src/executors/openai/index.ts
  frontend/internal-packages/schema-bench/src/executors/openai/openaiExecutor.test.ts
  frontend/internal-packages/schema-bench/src/executors/openai/openaiExecutor.ts
  frontend/internal-packages/schema-bench/src/executors/openai/schemaJsonSchema.ts
  frontend/internal-packages/schema-bench/src/executors/openai/types.ts
  frontend/internal-packages/schema-bench/src/index.ts
  pnpm-lock.yaml
Labels: Review effort 4/5, Possible security concern

#2599 🔧(agent): Simplify deepModeling return type to WorkflowState
  frontend/internal-packages/agent/src/chat/workflow/README.md
  frontend/internal-packages/agent/src/chat/workflow/nodes/designSchemaNode.ts
  frontend/internal-packages/agent/src/chat/workflow/nodes/finalizeArtifactsNode.ts
  frontend/internal-packages/agent/src/chat/workflow/shared/langGraphUtils.ts
  frontend/internal-packages/agent/src/chat/workflow/types.ts
  frontend/internal-packages/agent/src/deepModeling.test.ts
  frontend/internal-packages/agent/src/deepModeling.ts
Labels: Review effort 4/5

#2586 ✨ Implement real-time database-driven schema updates display
  frontend/apps/app/components/SessionDetailPage/SessionDetailPage.tsx
  frontend/apps/app/components/SessionDetailPage/SessionDetailPageClient.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/Output.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/ERD/Erd.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/SchemaUpdates/MigrationsViewer/useMigrationsViewer/useMigrationsViewer.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/SchemaUpdates/SchemaUpdates.tsx
  frontend/apps/app/components/SessionDetailPage/components/Output/components/SchemaUpdates/hooks/useSchemaUpdates.ts
  frontend/apps/app/components/SessionDetailPage/components/Output/components/SchemaUpdates/utils/schemaToDdl.ts
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeVersionsWithSchema/useRealtimeVersionsWithSchema.ts
  frontend/apps/app/components/SessionDetailPage/mock.ts
  frontend/apps/app/eslint-suppressions.json
  frontend/apps/app/package.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#2606 💄 Fix long text wrapping in VersionMessage component
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/VersionMessage/VersionMessage.module.css
Labels: Review effort 1/5

#2602 ✨ Add agent message grouping and status indicators to timeline
  frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/Chat.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/TimelineItem.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/AgentMessage/AgentMessage.module.css
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/LogMessage.module.css
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/LogMessage.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/LogMessage/LogMessage.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/utils/timelineUtils.ts
  frontend/apps/app/components/SessionDetailPage/types.ts
Labels: Review effort 4/5

#2592 Add query result display in timeline
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/TimelineItem.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/QueryResultMessage/QueryResultMessage.module.css
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/QueryResultMessage/QueryResultMessage.stories.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/QueryResultMessage/QueryResultMessage.tsx
  frontend/apps/app/components/SessionDetailPage/components/Chat/components/TimelineItem/components/QueryResultMessage/index.ts
  frontend/apps/app/components/SessionDetailPage/hooks/useRealtimeTimelineItems/useRealtimeTimelineItems.ts
  frontend/apps/app/components/SessionDetailPage/services/convertTimelineItemToTimelineItemEntry.ts
  frontend/apps/app/components/SessionDetailPage/services/designSessionWithTimelineItems/fetchDesignSessionWithTimelineItems.ts
  frontend/apps/app/components/SessionDetailPage/types.ts
  frontend/apps/app/eslint-suppressions.json
  frontend/internal-packages/agent/src/chat/workflow/nodes/executeDdlNode.ts
  frontend/internal-packages/agent/src/chat/workflow/utils/queryResultLogger.ts
  frontend/internal-packages/agent/src/deepModeling.test.ts
  frontend/internal-packages/agent/src/repositories/supabase.ts
  frontend/internal-packages/agent/src/repositories/types.ts
  frontend/internal-packages/db/schema/schema.sql
  frontend/internal-packages/db/src/schema.ts
  frontend/internal-packages/db/supabase/database.types.ts
  frontend/internal-packages/db/supabase/migrations/20250717004636_add_query_result_timeline_type.sql
  frontend/internal-packages/db/supabase/migrations/20250722055613_drop-query-results-column.sql
Labels: Review effort 4/5

#2561 refactor: remove no-throw-error from liam-hq/db-structure
  frontend/packages/db-structure/eslint-suppressions.json
  frontend/packages/db-structure/src/deparser/postgresql/operationDeparser.ts
  frontend/packages/db-structure/src/deparser/postgresql/schemaDeparser.ts
  frontend/packages/db-structure/src/deparser/postgresql/utils.ts
  frontend/packages/db-structure/src/parser/prisma/index.test.ts
  frontend/packages/db-structure/src/parser/schemarb/parser.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/converter.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/index.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/processSqlInChunks.test.ts
  frontend/packages/db-structure/src/parser/sql/postgresql/processSqlInChunks.ts
  frontend/packages/db-structure/src/parser/tbls/parser.ts
  frontend/packages/db-structure/src/schema/mergeSchema.ts
Labels: Review effort 4/5
